CALL env.bat
%DEVBASE_DRIVE%
cd %DEVBASE%/APP
SET PATH=%DEVBASE%/OS/%OS_VERSION%/nut/tools/win32;%DEVBASE%/COMPILER/%COMPILER_VERSION%/utils/bin;%DEVBASE%/COMPILER/%COMPILER_VERSION%/bin;%PATH%
PATH
make clean
make all
pause
