type lost.js > mms.js
type lost_mon.js >> mms.js
type lost_alarm.js >> mms.js
type lost_atm.js >> mms.js
type lost_safety.js >> mms.js
type lost_rooms.js >> mms.js
type lost_ev.js >> mms.js
type lost_html.js >> mms.js
type lost_mon_html.js >> mms.js
type lost_alarm_html.js >> mms.js
type lost_atm_html.js >> mms.js
type lost_safety_html.js >> mms.js
type lost_rooms_html.js >> mms.js
type lost_ev_html.js >> mms.js

type lost.js > bt.js
type lost_mon.js >> bt.js
type lost_alarm.js >> bt.js
type lost_atm.js >> bt.js
type lost_safety.js >> bt.js
type lost_rooms.js >> bt.js
type lost_ev.js >> bt.js
type lost_html.js >> bt.js
type lost_mon_html.js >> bt.js
type lost_alarm_html.js >> bt.js
type lost_atm_html.js >> bt.js
type lost_safety_html.js >> bt.js
type lost_rooms_html.js >> bt.js
type lost_ev_html.js >> bt.js
