type com\lost.js > mms.js
type com\lost_mon.js >> mms.js
type com\lost_alarm.js >> mms.js
type com\lost_atm.js >> mms.js
type com\lost_safety.js >> mms.js
type com\lost_rooms.js >> mms.js
type com\lost_ev.js >> mms.js
type mms\lost_html.js >> mms.js
type com\lost_mon_html.js >> mms.js
type com\lost_alarm_html.js >> mms.js
type mms\lost_atm_html.js >> mms.js
type com\lost_safety_html.js >> mms.js
type mms\lost_rooms_html.js >> mms.js
type mms\lost_ev_html.js >> mms.js

type com\lost.js > bt.js
type com\lost_mon.js >> bt.js
type com\lost_alarm.js >> bt.js
type com\lost_atm.js >> bt.js
type com\lost_safety.js >> bt.js
type com\lost_rooms.js >> bt.js
type com\lost_ev.js >> bt.js
type bt\lost_html.js >> bt.js
type com\lost_mon_html.js >> bt.js
type com\lost_alarm_html.js >> bt.js
type bt\lost_atm_html.js >> bt.js
type com\lost_safety_html.js >> bt.js
type bt\lost_rooms_html.js >> bt.js
type bt\lost_ev_html.js >> bt.js
