#ifndef _INCLUDE_CFG_LUANUT_H_
#define _INCLUDE_CFG_LUANUT_H_

//#define LAU_PARSER_NOT_IMPLEMENTED
#define LAU_TABLIB_NOT_IMPLEMENTED
#define LAU_STRLIB_NOT_IMPLEMENTED
//#define LAU_MATHLIB_NOT_IMPLEMENTED
#define LAU_DEBUGLIB_NOT_IMPLEMENTED

//#define LAU_BASELIB_NOT_IMPLEMENTED
#define LAU_LOADLIB_NOT_IMPLEMENTED
#define LAU_IOLIB_NOT_IMPLEMENTED
#define LAU_OSLIB_NOT_IMPLEMENTED

#endif
