Nut/OS: include/arch/arm/atom.h File Reference
atom.h File Reference
Defines
#define NutEnterCritical()
#define NutExitCritical()
#define NutJumpOutCritical() NutExitCritical()
Define Documentation
void NutEnterCritical ()
Value:
{ \
    int temp_; \
    asm volatile (             \
            "@ NutEnterCritical"    "\n\t" \
            "mrs     %0, cpsr"      "\n\t" \
            "orr     %0, %0, #0xC0" "\n\t" \
            "msr     cpsr, %0"      "\n\t" \
            : "=r" (temp_) : : "cc"); \
}
Definition at line 136 of file atom.h.
Referenced by AhdlcAt91Open(), AhdlcAt91Put(), At91EfcCmdEx(), AtCanInput(), Avr32FlashcCmd(), CFChange(), IDEInit(), NicRxAsix(), NutEventBroadcastAsync(), NutEventPostAsync(), NutEventTimeout(), NutEventWait(), NutEventWaitNext(), NutGetTickCount(), NutIrInitSony(), NutMsgQFlush(), NutMsgQGetMessage(), NutMsgQPost(), NutMsgQStopTimer(), NUTPANIC(), NutRegisterKey(), NutRegisterLed(), NutThreadAddPriQueue(), NutThreadCreate(), NutThreadRemoveQueue(), NutThreadResume(), NutThreadSetPriority(), NutThreadYield(), SJAInit(), SJAInput(), TwMasterTransact(), TwSlaveListen(), TwSlaveRespond(), UartAvrFlush(), UartAvrInput(), UsartIOCtl(), UsartRead(), and UsartSize().
void NutExitCritical ()
Value:
{ \
    int temp_; \
    asm volatile (             \
            "@ NutExitCritical"     "\n\t" \
            "mrs     %0, cpsr"      "\n\t" \
            "bic     %0, %0, #0xC0" "\n\t" \
            "msr     cpsr, %0"      "\n\t" \
            : "=r" (temp_) : : "cc"); \
}
Definition at line 147 of file atom.h.
Referenced by AhdlcAt91Open(), AhdlcAt91Put(), At91EfcCmdEx(), AtCanInput(), Avr32FlashcCmd(), CFChange(), IDEInit(), NicRxAsix(), NutEventBroadcastAsync(), NutEventPostAsync(), NutEventTimeout(), NutEventWait(), NutEventWaitNext(), NutGetTickCount(), NutIrInitSony(), NutMsgQFlush(), NutMsgQGetMessage(), NutMsgQPost(), NutMsgQStopTimer(), NutRegisterKey(), NutRegisterLed(), NutThreadAddPriQueue(), NutThreadCreate(), NutThreadRemoveQueue(), NutThreadResume(), NutThreadSetPriority(), NutThreadYield(), SJAInit(), SJAInput(), TwMasterTransact(), TwSlaveListen(), TwSlaveRespond(), UartAvrFlush(), UartAvrInput(), UsartIOCtl(), UsartRead(), and UsartSize().
#define NutJumpOutCritical () NutExitCritical()
Definition at line 160 of file atom.h.
Referenced by NutMsgQGetMessage(), and NutMsgQPost().