Nut/OS: pro/asn1.c File Reference
asn1.c File Reference
#include <sys/types.h>
#include <stdlib.h>
#include <string.h>
#include <memdebug.h>
#include <pro/asn1.h>
Functions
CONST uint8_t * AsnHeaderParse (CONST uint8_t *data, size_t *datalength, uint8_t *type)
Interpret the ID and length of the next object.
uint8_t * AsnHeaderBuild (uint8_t *data, size_t *datalength, uint8_t type, size_t length)
Build an ASN header for an object with a given ID and length.
CONST uint8_t * AsnSequenceParse (CONST uint8_t *data, size_t *datalength, uint8_t type)
Check the type and get the length of the next object.
uint8_t * AsnSequenceBuild (uint8_t *data, size_t *datalength, uint8_t type, size_t length)
Build an ASN header for a sequence with a given type and length.
CONST uint8_t * AsnIntegerParse (CONST uint8_t *data, size_t *datalength, uint8_t *type, long *intp)
Pull a long out of an ASN integer type.
uint8_t * AsnIntegerBuild (uint8_t *data, size_t *datalength, uint8_t type, long *intp)
Build an ASN object containing an integer.
CONST uint8_t * AsnUnsignedParse (CONST uint8_t *data, size_t *datalength, uint8_t *type, uint32_t *intp)
Pull an unsigned long out of an ASN integer type.
uint8_t * AsnUnsignedBuild (uint8_t *data, size_t *datalength, uint8_t type, uint32_t *intp)
Build an ASN object containing an unsigned integer.
CONST uint8_t * AsnOctetStringParse (CONST uint8_t *data, size_t *datalength, uint8_t *type, uint8_t *string, size_t *strlength)
Pulls a string out of an ASN octet string type.
uint8_t * AsnOctetStringBuild (uint8_t *data, size_t *datalength, uint8_t type, CONST uint8_t *string, size_t strlength)
Build an ASN object containing an octet string.
CONST uint8_t * AsnOidParse (CONST uint8_t *data, size_t *datalength, uint8_t *type, OID *objid, size_t *objidlength)
Pulls an object identifier out of an ASN object ID type.
uint8_t * AsnOidBuild (uint8_t *data, size_t *datalength, uint8_t type, CONST OID *objid, size_t objidlength)
Build an ASN object identifier.
CONST uint8_t * AsnNullParse (CONST uint8_t *data, size_t *datalength, uint8_t *type)
Parse an ASN null type.
uint8_t * AsnNullBuild (uint8_t *data, size_t *datalength, uint8_t type)
Build an ASN null object.
CONST uint8_t * AsnBitStringParse (CONST uint8_t *data, size_t *datalength, uint8_t *type, uint8_t *string, size_t *strlength)
Pull a bitstring out of an ASN bitstring type.
uint8_t * AsnBitStringBuild (uint8_t *data, size_t *datalength, uint8_t type, CONST uint8_t *string, size_t strlength)
Build an ASN bit string.
CONST uint8_t * AsnUnsigned64Parse (CONST uint8_t *data, size_t *datalength, uint8_t *type, UNSIGNED64 *cp)
Pull a 64 bit unsigned long out of an ASN integer type.
uint8_t * AsnUnsigned64Build (uint8_t *data, size_t *datalength, uint8_t type, CONST UNSIGNED64 *cp)
Build an ASN object containing a 64 bit unsigned integer.
Function Documentation
CONST uint8_t* AsnHeaderParse (CONST uint8_t * data, size_t * datalength, uint8_t * type)
Interpret the ID and length of the next object.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the ID and length.
type Pointer to the variable that receives the ASN type of the object.
Returns:
A pointer to the first byte following ID and length (aka the start of the data field). Returns NULL on any error.
Definition at line 136 of file asn1.c.
References ASN_EXTENSION_ID, and CONST.
Referenced by AsnSequenceParse(), SnmpAgentProcessRequest(), and SnmpVarParse().
uint8_t* AsnHeaderBuild (uint8_t * data, size_t * datalength, uint8_t type, size_t length)
Build an ASN header for an object with a given ID and length.
This only works on data types < 30, i.e. no extension octets. The maximum length is 0xFFFF;
Parameters:
data Pointer to start of object.
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the encoded ID and length of this object.
type ASN type of the object.
length Length of object.
Returns:
Returns a pointer to the first byte of the contents of this object. Returns NULL on any error.
Definition at line 189 of file asn1.c.
Referenced by AsnBitStringBuild(), AsnIntegerBuild(), AsnNullBuild(), AsnOctetStringBuild(), AsnOidBuild(), AsnUnsigned64Build(), and AsnUnsignedBuild().
CONST uint8_t* AsnSequenceParse (CONST uint8_t * data, size_t * datalength, uint8_t type)
Check the type and get the length of the next object.
Similare to AsnHeaderParse, but tests for expected type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the ID and length.
type The expected ASN type of the object.
Returns:
A pointer to the first byte following ID and length (aka the start of the data field). Returns NULL on any error.
Definition at line 215 of file asn1.c.
References AsnHeaderParse().
Referenced by SnmpAuthParse(), and SnmpVarParse().
uint8_t* AsnSequenceBuild (uint8_t * data, size_t * datalength, uint8_t type, size_t length)
Build an ASN header for a sequence with a given type and length.
This only works on data types < 30, i.e. no extension octets. The maximum length is 0xFFFF;
Parameters:
data Pointer to start of object.
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the encoded ID and length of this object.
type ASN type of the object.
length Length of object.
Returns:
Returns a pointer to the first byte of the contents of this object. Returns NULL on any error.
Definition at line 244 of file asn1.c.
Referenced by SnmpAgentProcessRequest(), SnmpAuthBuild(), and SnmpVarBuild().
CONST uint8_t* AsnIntegerParse (CONST uint8_t * data, size_t * datalength, uint8_t * type, long * intp)
Pull a long out of an ASN integer type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
intp Pointer to the variable that receives the value of the object.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 277 of file asn1.c.
References CONST.
Referenced by SnmpAgentProcessRequest(), and SnmpAuthParse().
uint8_t* AsnIntegerBuild (uint8_t * data, size_t * datalength, uint8_t type, long * intp)
Build an ASN object containing an integer.
Parameters:
data Pointer to start of output buffer
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
intp Value of the object.
Returns:
A pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 323 of file asn1.c.
References AsnHeaderBuild().
Referenced by SnmpAgentProcessRequest(), SnmpAuthBuild(), and SnmpVarBuild().
CONST uint8_t* AsnUnsignedParse (CONST uint8_t * data, size_t * datalength, uint8_t * type, uint32_t * intp)
Pull an unsigned long out of an ASN integer type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
intp Pointer to the variable that receives the value of the object.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 375 of file asn1.c.
References CONST.
uint8_t* AsnUnsignedBuild (uint8_t * data, size_t * datalength, uint8_t type, uint32_t * intp)
Build an ASN object containing an unsigned integer.
Parameters:
data Pointer to start of output buffer
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
intp Value of the object.
Returns:
A pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 425 of file asn1.c.
References AsnHeaderBuild().
Referenced by SnmpVarBuild().
CONST uint8_t* AsnOctetStringParse (CONST uint8_t * data, size_t * datalength, uint8_t * type, uint8_t * string, size_t * strlength)
Pulls a string out of an ASN octet string type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
string Pointer to the variable that receives the value of the object.
strlength Contains the size of the string buffer on entry. On exit, it is returned as the number of bytes stored in the string buffer.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 491 of file asn1.c.
References CONST, and memcpy().
Referenced by SnmpAuthParse().
uint8_t* AsnOctetStringBuild (uint8_t * data, size_t * datalength, uint8_t type, CONST uint8_t * string, size_t strlength)
Build an ASN object containing an octet string.
Parameters:
data Pointer to start of output buffer
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
string Pointer to the value. If NULL, the octet string will be filled with zeros.
strlength Number of bytes in the string value.
Returns:
A pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 533 of file asn1.c.
References AsnHeaderBuild(), memcpy(), and memset().
Referenced by SnmpAuthBuild(), and SnmpVarBuild().
CONST uint8_t* AsnOidParse (CONST uint8_t * data, size_t * datalength, uint8_t * type, OID * objid, size_t * objidlength)
Pulls an object identifier out of an ASN object ID type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
objid Pointer to the variable that receives the object identifier.
objidlength Points to a variable that contains the size of the output buffer on entry. On exit, it is returned as the number of sub IDs stored in the output buffer.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 574 of file asn1.c.
References ASN_BIT8, and CONST.
Referenced by SnmpVarParse().
uint8_t* AsnOidBuild (uint8_t * data, size_t * datalength, uint8_t type, CONST OID * objid, size_t objidlength)
Build an ASN object identifier.
Parameters:
data Pointer to start of the object.
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
objid Pointer to the object identifier.
objidlength Number of sub IDs in the object identifier.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 650 of file asn1.c.
References AsnHeaderBuild(), CONST, free(), malloc(), and MAX_OID_LEN.
Referenced by SnmpVarBuild().
CONST uint8_t* AsnNullParse (CONST uint8_t * data, size_t * datalength, uint8_t * type)
Parse an ASN null type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 775 of file asn1.c.
References CONST.
uint8_t* AsnNullBuild (uint8_t * data, size_t * datalength, uint8_t type)
Build an ASN null object.
Parameters:
data Pointer to start of the object.
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 806 of file asn1.c.
References AsnHeaderBuild().
Referenced by SnmpVarBuild().
CONST uint8_t* AsnBitStringParse (CONST uint8_t * data, size_t * datalength, uint8_t * type, uint8_t * string, size_t * strlength)
Pull a bitstring out of an ASN bitstring type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
string Pointer to the variable that receives the value of the object.
strlength Contains the size of the string buffer on entry. On exit, it is returned as the number of bytes stored in the string buffer.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 831 of file asn1.c.
References CONST, and memcpy().
uint8_t* AsnBitStringBuild (uint8_t * data, size_t * datalength, uint8_t type, CONST uint8_t * string, size_t strlength)
Build an ASN bit string.
Parameters:
data Pointer to start of output buffer
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
string Pointer to the value. If NULL, the octet string will be filled with zeros.
strlength Number of bytes in the string value.
Returns:
A pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 873 of file asn1.c.
References AsnHeaderBuild(), and memcpy().
Referenced by SnmpVarBuild().
CONST uint8_t* AsnUnsigned64Parse (CONST uint8_t * data, size_t * datalength, uint8_t * type, UNSIGNED64 * cp)
Pull a 64 bit unsigned long out of an ASN integer type.
Parameters:
data Pointer to start of the object.
datalength Contains the number of valid bytes following the start of the object. On exit, it is returned as the number of valid bytes following the end of this object.
type Pointer to the variable that receives the ASN type of the object.
intp Pointer to the variable that receives the value of the object.
Returns:
Pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 906 of file asn1.c.
References CONST, UNSIGNED64::high, and UNSIGNED64::low.
uint8_t* AsnUnsigned64Build (uint8_t * data, size_t * datalength, uint8_t type, CONST UNSIGNED64 * cp)
Build an ASN object containing a 64 bit unsigned integer.
Parameters:
data Pointer to start of output buffer
datalength Contains the number of available bytes following the start of the object. On exit, it is returned as the number of available bytes following the end of this object.
type ASN type of the object.
intp Value of the object.
Returns:
A pointer to the first byte past the end of this object (i.e. the start of the next object). Returns NULL on any error.
Definition at line 953 of file asn1.c.
References AsnHeaderBuild().
Referenced by SnmpVarBuild().