Nut/OS: app/caltime/caltime.c File Reference
caltime.c File Reference
#include <dev/board.h>
#include <dev/debug.h>
#include <sys/version.h>
#include <sys/timer.h>
#include <stdlib.h>
#include <stdio.h>
#include <io.h>
#include <string.h>
#include <time.h>
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 373 of file caltime.c.
References _daylight, _fileno(), _ioctl(), _timezone, DEV_CONSOLE, DEV_CONSOLE_NAME, EDIT_MODE_ECHO, EdLineOpen(), freopen(), getchar(), kbhit(), NutRegisterDevice(), NutRegisterRtc(), NutRtcGetStatus(), NutVersionString(), printf, putchar(), puts, RfcTimeParse(), RTC_STATUS_PF, stdin, stdout, stime(), and UART_SETSPEED.