Nut/OS: Counter Class Reference
Counter Class Reference
Public Member Functions
void print (FILE *stream)
Counter (uint8_t initValue=10)
Detailed Description
Examples:
cppdemo/cppdemo.cc.
Definition at line 74 of file cppdemo.cc.
Constructor & Destructor Documentation
Counter::Counter (uint8_t initValue = 10)
Examples:
cppdemo/cppdemo.cc.
Definition at line 89 of file cppdemo.cc.
References TemplateCounter< uint8_t >::m_value.
Member Function Documentation
void Counter::print (FILE * stream)
Examples:
cppdemo/cppdemo.cc.
Definition at line 83 of file cppdemo.cc.
References fprintf(), and TemplateCounter< uint8_t >::value().
Referenced by main().
The documentation for this class was generated from the following file:
app/cppdemo/cppdemo.cc