Nut/OS: TemplateCounter< tp_type > Class Template Reference
TemplateCounter< tp_type > Class Template Reference
Public Member Functions
tp_type value () const
void inc ()
void dec ()
void set (const tp_type &newValue)
Protected Attributes
tp_type m_value
Detailed Description
template<class tp_type>
class TemplateCounter< tp_type >
Examples:
cppdemo/cppdemo.cc.
Definition at line 60 of file cppdemo.cc.
Member Function Documentation
template<class tp_type> tp_type TemplateCounter< tp_type >::value () const [inline]
Examples:
cppdemo/cppdemo.cc.
Definition at line 66 of file cppdemo.cc.
template<class tp_type> void TemplateCounter< tp_type >::inc () [inline]
Examples:
cppdemo/cppdemo.cc.
Definition at line 67 of file cppdemo.cc.
Referenced by main().
template<class tp_type> void TemplateCounter< tp_type >::dec () [inline]
Examples:
cppdemo/cppdemo.cc.
Definition at line 68 of file cppdemo.cc.
Referenced by main().
template<class tp_type> void TemplateCounter< tp_type >::set (const tp_type & newValue) [inline]
Definition at line 69 of file cppdemo.cc.
Referenced by main().
Field Documentation
template<class tp_type> tp_type TemplateCounter< tp_type >::m_value [protected]
Examples:
cppdemo/cppdemo.cc.
Definition at line 63 of file cppdemo.cc.
Referenced by TemplateCounter< uint8_t >::dec(), TemplateCounter< uint8_t >::inc(), TemplateCounter< uint8_t >::set(), and TemplateCounter< uint8_t >::value().
The documentation for this class was generated from the following file:
app/cppdemo/cppdemo.cc