Nut/OS: app/cppdemo/cppdemo.cc File Reference
cppdemo.cc File Reference
#include <cpp/nutcpp.h>
#include <dev/board.h>
#include <sys/version.h>
#include <inttypes.h>
#include <io.h>
#include <stdio.h>
Data Structures
class TemplateCounter< tp_type >
class Counter
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 96 of file cppdemo.cc.
References _fileno(), _ioctl(), TemplateCounter< tp_type >::dec(), DEV_UART0, DEV_UART0_NAME, fopen(), fprintf(), fread(), TemplateCounter< tp_type >::inc(), NutRegisterDevice(), NutVersionString(), Counter::print(), TemplateCounter< tp_type >::set(), and UART_SETSPEED.