Nut/OS: include/dev/eeprom.h File Reference
eeprom.h File Reference
#include <stdint.h>
#include <dev/at24c.h>
Functions
int EEInit (void)
int EEReadData (uint16_t addr, void *data, uint16_t len)
int EEWriteData (uint16_t addr, CONST void *data, uint16_t len)
Function Documentation
int EEInit (void)
Definition at line 53 of file eeprom.c.
References At24cRead(), at24c::EepromSize, at24c::IAddrW, at24c::NumOfPage, NUT_CONFIG_AT24_ADR, at24c::PageSize, at24c::SlaveAddress, and at24c::Timeout.
int EEReadData (uint16_t addr, void * data, uint16_t len)
Definition at line 78 of file eeprom.c.
References At24cRead().
Referenced by NutNvMemLoad().
int EEWriteData (uint16_t addr, CONST void * data, uint16_t len)
Definition at line 71 of file eeprom.c.
References At24cWrite().
Referenced by NutNvMemSave().