Nut/OS: dev/eeprom.c File Reference
eeprom.c File Reference
#include <stdint.h>
#include <dev/twif.h>
#include <dev/at24c.h>
#include <dev/eeprom.h>
Defines
#define _DEV_EEPROM_H_
Functions
int EEInit (void)
int EEWriteData (uint16_t addr, CONST void *data, uint16_t len)
int EEReadData (uint16_t addr, void *data, uint16_t len)
Define Documentation
#define _DEV_EEPROM_H_
Definition at line 43 of file eeprom.c.
Function Documentation
int EEInit (void)
Definition at line 53 of file eeprom.c.
References At24cRead(), at24c::EepromSize, at24c::IAddrW, at24c::NumOfPage, NUT_CONFIG_AT24_ADR, at24c::PageSize, at24c::SlaveAddress, and at24c::Timeout.
int EEWriteData (uint16_t addr, CONST void * data, uint16_t len)
Definition at line 71 of file eeprom.c.
References At24cWrite().
Referenced by NutNvMemSave().
int EEReadData (uint16_t addr, void * data, uint16_t len)
Definition at line 78 of file eeprom.c.
References At24cRead().
Referenced by NutNvMemLoad().