Nut/OS: app/editconf/editconf.c File Reference
editconf.c File Reference
#include <dev/board.h>
#include <sys/confnet.h>
#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <io.h>
#include <arpa/inet.h>
#include <netinet/if_ether.h>
#include "meminfo.h"
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 99 of file editconf.c.
References _fileno(), _ioctl(), _CONFNET::cd_name, _CONFNET::cdn_cip_addr, _CONFNET::cdn_gateway, _CONFNET::cdn_ip_mask, _CONFNET::cdn_mac, confnet, DEV_CONSOLE, DEV_CONSOLE_NAME, DEV_ETHER_NAME, ether_aton(), ether_ntoa(), freopen(), getchar(), inet_addr(), inet_ntoa(), kbhit(), memcpy(), NutNetLoadConfig(), NutNetSaveConfig(), NutRegisterDevice(), printf, puts, ShowHardwareConfiguration(), stdin, stdout, strcpy(), and UART_SETSPEED.