Nut/OS: include/sys/environ.h File Reference
environ.h File Reference
#include <cfg/eeprom.h>
#include <sys/types.h>
Data Structures
struct _NUTENVIRONMENT
Defines
#define ENVIRON_EE_OFFSET 256
#define MAX_ENVIRON_ITEM_SIZE 64
#define ENVIRON_MAGIC 0x00564E45
Typedefs
typedef struct _NUTENVIRONMENT NUTENVIRONMENT
Functions
NUTENVIRONMENT * findenv (CONST char *name)
Find an NUTENVIRONMENT entry by name.
char * nextenv (CONST char *name)
Get the name of the next environment variable.
char * getenv (CONST char *name)
Get the value of an environment variable.
Variables
NUTENVIRONMENT * nut_environ
Define Documentation
#define ENVIRON_EE_OFFSET 256
Definition at line 40 of file environ.h.
Referenced by findenv().
#define MAX_ENVIRON_ITEM_SIZE 64
Definition at line 44 of file environ.h.
Referenced by findenv().
#define ENVIRON_MAGIC 0x00564E45
Definition at line 47 of file environ.h.
Referenced by findenv().
Typedef Documentation
typedef struct _NUTENVIRONMENT NUTENVIRONMENT
Function Documentation
NUTENVIRONMENT* findenv (CONST char * name)
Find an NUTENVIRONMENT entry by name.
Parameters:
name Points to a string, which is the name of the entry.
Returns:
A pointer to the entry with the specified name. If the name cannot be found, then a null pointer is returned.
Definition at line 81 of file environ.c.
References _NUTENVIRONMENT::env_name, _NUTENVIRONMENT::env_next, _NUTENVIRONMENT::env_prev, _NUTENVIRONMENT::env_value, ENVIRON_EE_OFFSET, ENVIRON_MAGIC, free(), malloc(), MAX_ENVIRON_ITEM_SIZE, memset(), NUTASSERT, NutNvMemLoad(), strcmp(), and strcpy().
Referenced by getenv(), nextenv(), setenv(), and unsetenv().
char* nextenv (CONST char * name)
Get the name of the next environment variable.
Parameters:
name Points to a string, which is the name of the previous variable. If this pointer is NULL or points to an empty string, then the name of the first variable is returned.
Returns:
A pointer to a string containing the name of the next variable, or NULL if no more variables are available.
Definition at line 68 of file getenv.c.
References _NUTENVIRONMENT::env_name, _NUTENVIRONMENT::env_next, findenv(), and nut_environ.
char* getenv (CONST char * name)
Get the value of an environment variable.
Parameters:
name Points to a string, which is the name of the variable.
Returns:
A pointer to a string containing the value. If the specified name cannot be found a null pointer will be returned.
Definition at line 45 of file getenv.c.
References _NUTENVIRONMENT::env_value, and findenv().
Referenced by MibRegisterSysVars().
Variable Documentation
NUTENVIRONMENT* nut_environ
Definition at line 43 of file environ.c.
Referenced by nextenv(), setenv(), and unsetenv().