Nut/OS: net/ether_addr.c File Reference
ether_addr.c File Reference
#include <string.h>
#include <netinet/if_ether.h>
Functions
uint8_t * ether_aton (CONST char *str)
Convert an ASCII string to a binary Ethernet address.
char * ether_ntoa (CONST uint8_t *mac)
Convert a binary Ethernet address to an ASCII string.
Function Documentation
uint8_t* ether_aton (CONST char * str)
Convert an ASCII string to a binary Ethernet address.
Note:
This function returns a pointer to internal static storage space that will be overwritten by subsequent calls.
Parameters:
str String to convert.
Returns:
Pointer to a static string that contains the converted binary address.
Definition at line 60 of file ether_addr.c.
References CONST, and memset().
Referenced by main(), and NutNetLoadConfig().
char* ether_ntoa (CONST uint8_t * mac)
Convert a binary Ethernet address to an ASCII string.
Note:
This function returns a pointer to internal static storage space that will be overwritten by subsequent calls.
Parameters:
mac Address to convert.
Returns:
Pointer to a static string that contains the converted ASCII string.
Definition at line 99 of file ether_addr.c.
Referenced by main().