Nut/OS: app/events/events.c File Reference
events.c File Reference
#include <cfg/os.h>
#include <stdio.h>
#include <io.h>
#include <dev/board.h>
#include <sys/thread.h>
#include <sys/timer.h>
#include <sys/event.h>
Functions
void High (void *arg)
void Low (void *arg)
int main (void)
Function Documentation
void High (void * arg)
Examples:
events/events.c.
Definition at line 80 of file events.c.
References NutEventPost(), NutEventWait(), NutSleep(), NutThreadSetPriority(), and puts.
Referenced by main().
void Low (void * arg)
Examples:
events/events.c.
Definition at line 101 of file events.c.
References NutEventPost(), NutEventWait(), NutSleep(), NutThreadSetPriority(), and puts.
Referenced by main().
int main (void)
Definition at line 121 of file events.c.
References _fileno(), _ioctl(), DEV_CONSOLE, DEV_CONSOLE_NAME, freopen(), High(), Low(), NutEventPost(), NutEventWait(), NutRegisterDevice(), NutSleep(), NutThreadCreate(), puts, stdout, and UART_SETSPEED.