Nut/OS: XgNutArchAvr32DevWatchDog
XgNutArchAvr32DevWatchDog
Functions
uint32_t Avr32WatchDogStart (uint32_t ms)
Start the AVR32 hardware watch dog timer.
void Avr32WatchDogRestart (void)
Re-start the AVR32 hardware watch dog timer.
void Avr32WatchDogDisable (void)
Disable the AVR32 hardware watch dog timer.
void Avr32WatchDogEnable (void)
Enable the AT91 hardware watch dog timer.
Function Documentation
uint32_t Avr32WatchDogStart (uint32_t ms)
Start the AVR32 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 79 of file wdt.c.
References Avr32WatchDogDisable(), Avr32WatchDogRestart(), MAX_US_TIMEOUT_PERIOD, MIN_US_TIMEOUT_PERIOD, NUT_HWCLK_SLOW_CLOCK, and NutArchClockGet().
Referenced by NutWatchDogStart().
void Avr32WatchDogRestart (void)
Re-start the AVR32 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 116 of file wdt.c.
Referenced by Avr32WatchDogEnable(), Avr32WatchDogStart(), and NutWatchDogRestart().
void Avr32WatchDogDisable (void)
Disable the AVR32 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 128 of file wdt.c.
Referenced by Avr32WatchDogStart(), and NutWatchDogDisable().
void Avr32WatchDogEnable (void)
Enable the AT91 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 142 of file wdt.c.
References Avr32WatchDogRestart().
Referenced by NutWatchDogEnable().