Nut/OS: SAM7X EMAC
SAM7X EMAC
AT91 Support
SAM7X EMAC registers.
Functions
void EmacRxThread (void *arg)
int EmacOutput (NUTDEVICE *dev, NETBUF *nb)
Send Ethernet packet.
int EmacInit (NUTDEVICE *dev)
Initialize Ethernet hardware.
Variables
NUTDEVICE devAt91Emac
Device information structure.
Detailed Description
SAM7X EMAC registers.
Function Documentation
void EmacRxThread (void * arg)
Definition at line 563 of file at91sam7x_emac.c.
References _NUTDEVICE::dev_dcb, _NUTDEVICE::dev_icb, EMAC_IER, ETHER_IS_UNICAST, ifnet::if_mac, ifnet::if_recv, _NETBUF::nb_dl, _EMACINFO::ni_insane, _EMACINFO::ni_mutex, _EMACINFO::ni_rx_rdy, _EMACINFO::ni_tx_quelen, _EMACINFO::ni_tx_queued, NutEventPost(), NutEventWait(), NutIrqEnable(), NutNetBufFree(), NutSleep(), NutThreadSetPriority(), outr, sig_EMAC, and _NBDATA::sz.
int EmacOutput (NUTDEVICE * dev, NETBUF * nb)
Send Ethernet packet.
Todo:
This routine does not work.
Parameters:
dev Identifies the device to use.
nb Network buffer structure containing the packet to be sent. The structure must have been allocated by a previous call NutNetBufAlloc().
Returns:
0 on success, -1 in case of any errors.
Definition at line 649 of file at91sam7x_emac.c.
References _NUTDEVICE::dev_dcb, _EMACINFO::ni_insane, _EMACINFO::ni_mutex, _EMACINFO::ni_tx_rdy, NutEventPost(), NutEventWait(), _BufDescriptor::stat, and TXS_USED.
int EmacInit (NUTDEVICE * dev)
Initialize Ethernet hardware.
Applications should do not directly call this function. It is automatically executed during during device registration by NutRegisterDevice().
Parameters:
dev Identifies the device to initialize.
Definition at line 706 of file at91sam7x_emac.c.
References _NUTDEVICE::dev_dcb, EmacRxThread(), memset(), NUT_THREAD_NICRXSTACK, NUT_THREAD_STACK_ADD, NUT_THREAD_STACK_MULT, NutRegisterIrqHandler(), NutThreadCreate(), and sig_EMAC.
Variable Documentation
NUTDEVICE devAt91Emac
Initial value:
 {
    0,
    {'e', 't', 'h', '0', 0, 0, 0, 0, 0},
    IFTYP_NET,
    0,
    0,
    &ifn_eth0,
    &dcb_eth0,
    EmacInit,
    0,
    0,
    0,
    0,
    0,
    0,
    0
}
Device information structure.
A pointer to this structure must be passed to NutRegisterDevice() to bind this Ethernet device driver to the Nut/OS kernel. An application may then call NutNetIfConfig() with the name eth0 of this driver to initialize the network interface.
Definition at line 763 of file at91sam7x_emac.c.