Nut/OS: AVR EEPROM
AVR EEPROM
Non-Volatile Memory
AVR on-chip EEPROM support.
Functions
int OnChipNvMemLoad (unsigned int addr, void *buff, size_t siz)
Load data from AVR EEPROM.
int OnChipNvMemSave (unsigned int addr, CONST void *buff, size_t len)
Save data in AVR EEPROM.
Detailed Description
AVR on-chip EEPROM support.
Function Documentation
int OnChipNvMemLoad (unsigned int addr, void * buff, size_t siz)
Load data from AVR EEPROM.
Returns:
Allways 0.
Definition at line 81 of file eeprom.c.
References eeprom_read_block(), and EEPROMReadBytes.
Referenced by NutNvMemLoad().
int OnChipNvMemSave (unsigned int addr, CONST void * buff, size_t len)
Save data in AVR EEPROM.
Returns:
Allways 0.
Definition at line 96 of file eeprom.c.
References eeprom_read_byte(), eeprom_write_byte(), and EEPROMread.
Referenced by NutNvMemSave().