Nut/OS: Watchdog Functions
Watchdog Functions
AT91 Support
AT91 on-chip watchdog timer.
Functions
uint32_t At91WatchDogStart (uint32_t ms, uint32_t xmode)
Start the AT91 hardware watch dog timer.
void At91WatchDogRestart (void)
Re-start the AT91 hardware watch dog timer.
void At91WatchDogDisable (void)
Disable the AT91 hardware watch dog timer.
void At91WatchDogEnable (void)
Enable the AT91 hardware watch dog timer.
Detailed Description
AT91 on-chip watchdog timer.
Function Documentation
uint32_t At91WatchDogStart (uint32_t ms, uint32_t xmode)
Start the AT91 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 69 of file wdt_at91.c.
References At91WatchDogDisable(), At91WatchDogRestart(), NutGetCpuClock(), outr, WD_CKEY, WD_CMR, WD_HPCV, WD_OKEY, WD_OMR, WD_RSTEN, WD_WDCLKS_MCK1024, WD_WDCLKS_MCK128, WD_WDCLKS_MCK32, WD_WDCLKS_MCK8, WD_WDEN, WDT_MR, WDT_WDDBGHLT, WDT_WDIDLEHLT, and WDT_WDRSTEN.
Referenced by At91Reset(), and NutWatchDogStart().
void At91WatchDogRestart (void)
Re-start the AT91 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 135 of file wdt_at91.c.
References outr, WD_CR, WD_RSTKEY, WDT_CR, WDT_KEY, and WDT_WDRSTT.
Referenced by At91WatchDogEnable(), At91WatchDogStart(), and NutWatchDogRestart().
void At91WatchDogDisable (void)
Disable the AT91 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 150 of file wdt_at91.c.
References inr, outr, WD_OKEY, WD_OMR, WD_WDEN, WDT_MR, and WDT_WDDIS.
Referenced by At91WatchDogStart(), and NutWatchDogDisable().
void At91WatchDogEnable (void)
Enable the AT91 hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 168 of file wdt_at91.c.
References At91WatchDogRestart(), inr, outr, WD_OKEY, WD_OMR, and WD_WDEN.
Referenced by NutWatchDogEnable().