Nut/OS: PHAT12 Support
PHAT12 Support
PHAT File System
PHAT12 specific routines.
Defines
#define PHAT12CMASK 0x0FFF
Functions
int Phat12GetClusterLink (NUTDEVICE *dev, uint32_t clust, uint32_t *link)
Get link value of a specified cluster.
int Phat12SetClusterLink (NUTDEVICE *dev, uint32_t clust, uint32_t link)
Set link value of a specified cluster.
int Phat12ReleaseChain (NUTDEVICE *dev, uint32_t first)
Release a cluster chain.
Detailed Description
PHAT12 specific routines.
Define Documentation
#define PHAT12CMASK 0x0FFF
Definition at line 58 of file phat12.h.
Referenced by AllocFirstCluster(), Phat12GetClusterLink(), Phat12ReleaseChain(), Phat12SetClusterLink(), PhatFilePosSet(), PhatFileRead(), and PhatFileWrite().
Function Documentation
int Phat12GetClusterLink (NUTDEVICE * dev, uint32_t clust, uint32_t * link)
Get link value of a specified cluster.
Parameters:
dev Specifies the file system device.
clust Get the link of this cluster.
link Pointer to a variable which will receive the link.
Returns:
0 on success or -1 on failure.
Definition at line 100 of file phat12.c.
References _NUTDEVICE::dev_dcb, PHAT12CMASK, PHATEOC, PhatSectorLoad(), _PHATSECTBUF::sect_data, _PHATVOL::vol_buf, and _PHATVOL::vol_sectsz.
Referenced by Phat12ReleaseChain(), PhatFilePosSet(), PhatFileRead(), and PhatFileWrite().
int Phat12SetClusterLink (NUTDEVICE * dev, uint32_t clust, uint32_t link)
Set link value of a specified cluster.
Parameters:
dev Specifies the file system device.
clust This cluster will be linked.
link Link to this cluster.
Returns:
0 on success or -1 on failure.
Definition at line 146 of file phat12.c.
References _NUTDEVICE::dev_dcb, PHAT12CMASK, PhatSectorLoad(), _PHATSECTBUF::sect_data, _PHATSECTBUF::sect_dirty, _PHATVOL::vol_buf, _PHATVOL::vol_sectsz, and _PHATVOL::vol_tab_sect.
Referenced by AllocFirstCluster(), and Phat12ReleaseChain().
int Phat12ReleaseChain (NUTDEVICE * dev, uint32_t first)
Release a cluster chain.
Parameters:
dev Specifies the file system device.
first First cluster of the chain to release.
Returns:
0 on success or -1 on failure.
Definition at line 209 of file phat12.c.
References _NUTDEVICE::dev_dcb, PHAT12CMASK, Phat12GetClusterLink(), Phat12SetClusterLink(), PHATEOC, and _PHATVOL::vol_numfree.
Referenced by PhatDirReleaseChain().