Nut/OS: XgNutArchAvr32OsTimer
XgNutArchAvr32OsTimer
Defines
#define NUT_TICK_FREQ 1000UL
Functions
void NutRegisterTimer (void(*handler)(void *))
Initialize system timer.
uint32_t NutArchClockGet (int idx)
Return the CPU clock in Hertz.
uint32_t NutGetTickClock (void)
Return the number of system ticks per second.
uint32_t NutTimerMillisToTicks (uint32_t ms)
Calculate system ticks for a given number of milliseconds.
Variables
IRQ_HANDLER sig_sysCompare
Detailed Description
Copyright (C) 2001-2010 by egnite Software GmbH
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 3. Neither the name of the copyright holders nor the names of contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
For additional information see http://www.ethernut.de/
Define Documentation
#define NUT_TICK_FREQ 1000UL
Definition at line 58 of file ostimer.c.
Referenced by NutGetTickClock(), NutRegisterTimer(), and NutTimerMillisToTicks().
Function Documentation
void NutRegisterTimer (void(*)(void *) handler)
Initialize system timer.
This function is automatically called by Nut/OS during system initialization.
Nut/OS uses on-chip tick counter for its timer services. Applications should not modify any registers of this timer, but make use of the Nut/OS timer API. Timer 1 and timer 2 are available to applications.
Definition at line 180 of file ostimer.c.
References Get_system_register, IRQ_HANDLER::ir_handler, NUT_TICK_FREQ, NutGetCpuClock(), register_interrupt(), and Set_system_register.
Referenced by NutTimerInit().
uint32_t NutArchClockGet (int idx)
Return the CPU clock in Hertz.
On AVR32 CPUs the processor clock may differ from the clock driving the peripherals. In this case NutArchClockGet() will provide the correct clock depending on it's argument.
Returns:
CPU clock frequency in Hertz.
Definition at line 199 of file ostimer.c.
References _BV, NUT_HWCLK_CPU, NUT_HWCLK_PERIPHERAL_A, NUT_HWCLK_PERIPHERAL_B, NUT_HWCLK_PERIPHERAL_HSB, and NUT_HWCLK_SLOW_CLOCK.
Referenced by Avr32WatchDogStart(), and NutGetCpuClock().
uint32_t NutGetTickClock (void)
Return the number of system ticks per second.
Returns:
System tick frequency in Hertz.
Definition at line 240 of file ostimer.c.
References NUT_TICK_FREQ.
Referenced by NutGetMillis(), NutGetSeconds(), and NutTimerMillisToTicks().
uint32_t NutTimerMillisToTicks (uint32_t ms)
Calculate system ticks for a given number of milliseconds.
Definition at line 248 of file ostimer.c.
References NUT_TICK_FREQ.
Referenced by NutTimerStart().
Variable Documentation
IRQ_HANDLER sig_sysCompare
Initial value:
 {
    NULL,
    NULL,
    NULL
}
Definition at line 61 of file ostimer.c.