Nut/OS: XgNutArchAvr32Rstc
XgNutArchAvr32Rstc
Functions
void Avr32Reset (void)
System reset.
int Avr32ResetCause (void)
Function Documentation
void Avr32Reset (void)
System reset.
Definition at line 59 of file reset.c.
References NutWatchDogStart().
Referenced by NutReset().
int Avr32ResetCause (void)
Definition at line 67 of file reset.c.
References NUT_RSTTYP_BROWNOUT, NUT_RSTTYP_EXTERNAL, NUT_RSTTYP_POWERUP, NUT_RSTTYP_UNKNOWN, and NUT_RSTTYP_WATCHDOG.
Referenced by NutResetCause().