Nut/OS: pro/httpd_p.c File Reference
httpd_p.c File Reference
#include <cfg/http.h>
#include <sys/heap.h>
#include <stdlib.h>
#include <string.h>
#include <memdebug.h>
#include "httpd_p.h"
Defines
#define HTTP_DEFAULT_ROOT "UROM:"
Default index files.
Functions
char * CreateFilePath (CONST char *url, CONST char *addon)
Create a file path from an URL.
void DestroyRequestInfo (REQUEST *req)
Release request info structure.
Variables
char * http_root
char * default_files []
Define Documentation
#define HTTP_DEFAULT_ROOT "UROM:"
Default index files.
The first entry must contain an empty string.
Default file system.
Definition at line 30 of file httpd_p.c.
Referenced by CreateFilePath().
Function Documentation
char* CreateFilePath (CONST char * url, CONST char * addon)
Create a file path from an URL.
Definition at line 55 of file httpd_p.c.
References HTTP_DEFAULT_ROOT, http_root, malloc(), strcat(), strcpy(), and strlen().
void DestroyRequestInfo (REQUEST * req)
Release request info structure.
Definition at line 77 of file httpd_p.c.
References free(), _REQUEST::req_agent, _REQUEST::req_auth, _REQUEST::req_cookie, _REQUEST::req_encoding, _REQUEST::req_host, _REQUEST::req_qptrs, _REQUEST::req_query, _REQUEST::req_referer, _REQUEST::req_type, and _REQUEST::req_url.
Referenced by NutHttpProcessRequest().
Variable Documentation
char* default_files[]
Initial value:
 {
    "",
    "/index.html",
    "/index.htm",
    "/default.html",
    "/default.htm",
    "/index.shtml",
    "/index.xhtml",
    "/index.asp",
    "/default.asp",
    NULL
}
Definition at line 35 of file httpd_p.c.