Nut/OS: app/httpd_simple/httpd_simple.c File Reference
httpd_simple.c File Reference
#include <dev/board.h>
#include <dev/urom.h>
#include <sys/version.h>
#include <sys/timer.h>
#include <sys/confnet.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <pro/dhcp.h>
#include <pro/httpd.h>
#include <io.h>
#include <errno.h>
Functions
int main (void)
Main application routine.
Function Documentation
int main (void)
Main application routine.
Nut/OS automatically calls this entry after initialization.
Definition at line 69 of file httpd_simple.c.
References _fdopen(), _fileno(), _ioctl(), _CONFNET::cdn_ip_addr, confnet, DEV_CONSOLE, DEV_CONSOLE_NAME, DEV_ETHER, DEV_ETHER_NAME, devUrom, errno, fclose(), freopen(), inet_ntoa(), NutDhcpIfConfig(), NutHttpProcessRequest(), NutRegisterDevice(), NutSleep(), NutTcpAccept(), NutTcpCloseSocket(), NutTcpCreateSocket(), NutVersionString(), printf, puts, stdout, and UART_SETSPEED.