Nut/OS: arch/arm/dev/atmel/ih_at91sys.c File Reference
ih_at91sys.c File Reference
#include <arch/arm.h>
#include <dev/irqreg.h>
Defines
#define NUT_IRQPRI_SYS 0
Functions
int NutSysIrqEnable (SYSIRQ_HANDLER *sysirq)
Enable a specified system interrupt.
int NutSysIrqDisable (SYSIRQ_HANDLER *sysirq)
Disable a specified system interrupt.
int NutRegisterSysIrqHandler (SYSIRQ_HANDLER *sysirq, void(*handler)(void *), void *arg)
Register a system interrupt handler.
Variables
SYSIRQ_HANDLER syssig_DBGU
SYSIRQ_HANDLER syssig_MC
SYSIRQ_HANDLER syssig_PIT
SYSIRQ_HANDLER syssig_PMC
SYSIRQ_HANDLER syssig_RSTC
SYSIRQ_HANDLER syssig_RTT
SYSIRQ_HANDLER syssig_WDT
IRQ_HANDLER sig_SYS
Define Documentation
#define NUT_IRQPRI_SYS 0
Definition at line 48 of file ih_at91sys.c.
Function Documentation
int NutSysIrqEnable (SYSIRQ_HANDLER * sysirq)
Enable a specified system interrupt.
Parameters:
sysirq Interrupt to enable.
Returns:
0 on success, -1 otherwise.
Definition at line 195 of file ih_at91sys.c.
References NUT_IRQCTL_ENABLE.
Referenced by NutRegisterTimer().
int NutSysIrqDisable (SYSIRQ_HANDLER * sysirq)
Disable a specified system interrupt.
Parameters:
sysirq Interrupt to disable.
Returns:
0 on success, -1 otherwise.
Definition at line 209 of file ih_at91sys.c.
Referenced by NutRegisterSysIrqHandler().
int NutRegisterSysIrqHandler (SYSIRQ_HANDLER * sysirq, void(*)(void *) handler, void * arg)
Register a system interrupt handler.
This call will also disable any previously registered handler.
If enabled with NutSysIrqEnable(), the registered handler will be called on every system interrupt. The handler must check, if the interrupt was triggered by the corresponding device.
This function is typically called by device drivers, but applications may also implement their local interrupt handlers.
Parameters:
irq Interrupt to be associated with this handler.
handler This routine will be called by Nut/OS, when the specified interrupt occurs.
arg Argument to be passed to the interrupt handler.
Returns:
0 on success, -1 otherwise.
Definition at line 235 of file ih_at91sys.c.
References NUT_IRQCTL_INIT, and NutSysIrqDisable().
Referenced by NutRegisterTimer().
Variable Documentation
SYSIRQ_HANDLER syssig_DBGU
Definition at line 51 of file ih_at91sys.c.
SYSIRQ_HANDLER syssig_MC
Definition at line 52 of file ih_at91sys.c.
SYSIRQ_HANDLER syssig_PIT
Definition at line 53 of file ih_at91sys.c.
Referenced by NutRegisterTimer().
SYSIRQ_HANDLER syssig_PMC
Definition at line 54 of file ih_at91sys.c.
SYSIRQ_HANDLER syssig_RSTC
Definition at line 55 of file ih_at91sys.c.
SYSIRQ_HANDLER syssig_RTT
Definition at line 56 of file ih_at91sys.c.
SYSIRQ_HANDLER syssig_WDT
Definition at line 57 of file ih_at91sys.c.
IRQ_HANDLER sig_SYS
Initial value:
 {
    NULL,
    NULL,
    SystemIrqCtl
}
Definition at line 62 of file ih_at91sys.c.