Nut/OS: app/inetq/inetq.c File Reference
inetq.c File Reference
#include <string.h>
#include <stdio.h>
#include <io.h>
#include <dev/board.h>
#include <sys/heap.h>
#include <sys/thread.h>
#include <sys/timer.h>
#include <sys/socket.h>
#include <sys/confnet.h>
#include <arpa/inet.h>
#include <net/route.h>
#include <netdb.h>
#include <pro/dhcp.h>
Defines
#define DNSSERVERIP "192.168.192.2"
#define INETSERVER "www.kornet.net"
#define INETSERVERPORT 80
#define INETURL "/"
#define MY_MAC {0x00,0x06,0x98,0x20,0x00,0x00}
#define MY_IP "192.168.192.100"
#define MY_MASK "255.255.255.0"
#define MY_GATE "192.168.192.3"
Functions
int main (void)
Define Documentation
#define DNSSERVERIP "192.168.192.2"
Examples:
inetq/inetq.c.
Definition at line 94 of file inetq.c.
Referenced by main().
#define INETSERVER "www.kornet.net"
Examples:
inetq/inetq.c.
Definition at line 95 of file inetq.c.
Referenced by main().
#define INETSERVERPORT 80
Examples:
inetq/inetq.c.
Definition at line 96 of file inetq.c.
Referenced by main().
#define INETURL "/"
Examples:
inetq/inetq.c.
Definition at line 97 of file inetq.c.
Referenced by main().
#define MY_MAC {0x00,0x06,0x98,0x20,0x00,0x00}
Definition at line 98 of file inetq.c.
#define MY_IP "192.168.192.100"
Definition at line 99 of file inetq.c.
Referenced by main().
#define MY_MASK "255.255.255.0"
Definition at line 100 of file inetq.c.
Referenced by main().
#define MY_GATE "192.168.192.3"
Definition at line 101 of file inetq.c.
Referenced by main().
Function Documentation
int main (void)
Definition at line 128 of file inetq.c.
References _fdopen(), _fileno(), _ioctl(), _CONFNET::cdn_ip_addr, confnet, DEV_CONSOLE, DEV_CONSOLE_NAME, DEV_ETHER, DNSSERVERIP, fclose(), fflush(), fgets(), fprintf(), fputs(), freopen(), inet_addr(), inet_ntoa(), INETSERVER, INETSERVERPORT, INETURL, MY_GATE, MY_IP, MY_MASK, NutDhcpIfConfig(), NutDnsConfig2(), NutDnsGetHostByName(), NutGetTickCount(), NutIpRouteAdd(), NutNetIfConfig(), NutRegisterDevice(), NutSleep(), NutTcpCloseSocket(), NutTcpConnect(), NutTcpCreateSocket(), NutTcpReceive(), NutTcpSend(), printf, puts, stdout, strcpy(), strlen(), and UART_SETSPEED.