Nut/OS: include/io.h File Reference
io.h File Reference
#include <sys/types.h>
Defines
#define IOCTL_GETSTATUS 0x0001
#define IOCTL_SETSTATUS 0x0002
#define IOCTL_SETBUFFERMODE 0x0003
#define IOCTL_GETBUFFERMODE 0x0004
#define IOCTL_GETOUTBUFSIZE 0x0005
#define IOCTL_SETOUTBUFSIZE 0x0006
#define IOCTL_GETINBUFSIZE 0x0007
#define IOCTL_SETINBUFSIZE 0x0008
#define IOCTL_FLUSHOUTBUF 0x0009
Flush the output buffer.
#define IOCTL_GETFILESIZE 0x000A
Return the number of bytes currently available in the input buffer.
#define IOCTL_GETOUTBUFCOUNT 0x000B
Return the number of bytes currently available in the input buffer.
#define IOCTL_GETINBUFCOUNT 0x000C
Return the number of bytes currently available in the output buffer.
Functions
int _close (int fd)
Close a file, device or socket.
int _open (CONST char *name, int mode)
Open a file.
int _read (int fd, void *buffer, size_t count)
int _write (int fd, CONST void *buffer, size_t count)
int _write_P (int fd, PGM_P buffer, size_t count)
int _seek (int fd, long offset, int origin)
Move read/write position of a file.
long _tell (int fd)
Return the read/write position of a stream.
int _ioctl (int fd, int cmd, void *buffer)
Perform device specific control functions.
long _filelength (int fd)
Return the length of a file.
Function Documentation
int _read (int fd, void * buffer, size_t count)
Examples:
uart/uart.c.
Referenced by fgetc(), fpurge(), fread(), main(), NutChatExpectString(), NutFtpTransferFile(), NutHttpProcessAsp(), PerCiDump(), PerCiOpen(), PerCiRead(), vfscanf(), and vfscanf_P().
int _write (int fd, CONST void * buffer, size_t count)
Examples:
uart/uart.c.
Referenced by fflush(), fputc(), fputs(), fwrite(), main(), NutFtpTransferFile(), PerCiFlush(), PerCiInit(), PerCiWrite(), syslog_flush(), vfprintf(), and vfprintf_P().
int _write_P (int fd, PGM_P buffer, size_t count)
Examples:
uart/uart.c.
Referenced by fputs_P(), fwrite_P(), and main().