Nut/OS: app/lua/lua.c File Reference
lua.c File Reference
#include <dev/board.h>
#include <sys/version.h>
#include <sys/heap.h>
#include <sys/timer.h>
#include <sys/confnet.h>
#include <sys/thread.h>
#include <gorp/edline.h>
#include <arpa/inet.h>
#include <pro/dhcp.h>
#include <stdio.h>
#include <io.h>
#include <string.h>
#include <lua/lua.h>
#include <lua/lauxlib.h>
#include <lua/lualib.h>
Defines
#define lua_c
#define THREAD_LUASTACK 8192
Functions
void LuaThread (void *arg)
int main (void)
Define Documentation
#define lua_c
Definition at line 58 of file lua.c.
#define THREAD_LUASTACK 8192
Definition at line 70 of file lua.c.
Referenced by main().
Function Documentation
void LuaThread (void * arg)
Definition at line 282 of file lua.c.
References EDIT_MODE_ECHO, EDIT_MODE_HISTORY, EdLineClose(), EdLineKeyMapVt100(), EdLineOpen(), EdLineRegisterKeymap(), lua_close(), lua_cpcall(), lua_open, NutHeapAvailable, NutVersionString(), and printf.
Referenced by main().
int main (void)
Definition at line 318 of file lua.c.
References _fileno(), _ioctl(), _CONFNET::cdn_ip_addr, confnet, DEV_CONSOLE, DEV_CONSOLE_NAME, DEV_ETHER, DEV_ETHER_NAME, freopen(), inet_addr(), inet_ntoa(), LUA_COPYRIGHT, LUA_RELEASE, LuaThread(), NUT_THREAD_STACK_ADD, NUT_THREAD_STACK_MULT, NutDhcpIfConfig(), NutNetIfConfig(), NutRegisterDevice(), NutSleep(), NutThreadCreate(), printf, puts, stderr, stdin, stdout, THREAD_LUASTACK, and UART_SETSPEED.