Nut/OS: app/editconf/meminfo.c File Reference
meminfo.c File Reference
#include <dev/board.h>
#include <sys/confnet.h>
#include <stdio.h>
#include "meminfo.h"
Functions
void ShowHardwareConfiguration (void)
Function Documentation
void ShowHardwareConfiguration (void)
$Id$
Examples:
editconf/editconf.c.
Definition at line 63 of file meminfo.c.
References AT45_CONF_DFPCS, AT45_CONF_DFSPI, At45dbPageSize(), FLASH_CHIP_BASE, FLASH_CONF_SECTOR, FLASH_CONF_SIZE, NUT_CONFIG_AT24_ADR, printf, puts, SPI0_BASE, and SpiAt45dConfigSize().
Referenced by main().