Nut/OS: app/snmpd/mib2sys.h File Reference
mib2sys.h File Reference
#include <pro/snmp_mib.h>
Defines
#define MAX_SYSSTR_LEN 64
Functions
int MibRegisterSysVars (void)
Register MIB II system variables.
Define Documentation
#define MAX_SYSSTR_LEN 64
Definition at line 39 of file mib2sys.h.
Function Documentation
int MibRegisterSysVars (void)
Register MIB II system variables.
Note:
Preliminary code with hard coded values.
Definition at line 134 of file mib2sys.c.
References BOARD_NAME, confos, getenv(), _CONFOS::hostname, NutVersionString(), SnmpMibRegister(), strcat(), strcpy(), and time().
Referenced by main().