Nut/OS: app/snmpd/mib2if.h File Reference
mib2if.h File Reference
#include <pro/snmp_mib.h>
Functions
int MibRegisterIfVars (void)
Register MIB II variables of the interfaces.
Function Documentation
int MibRegisterIfVars (void)
Register MIB II variables of the interfaces.
Note:
Preliminary code with hard coded values.
Definition at line 130 of file mib2if.c.
References malloc(), PHY_NAME, SnmpMibRegister(), strcpy(), and strlen().
Referenced by main().