Nut/OS: include/net/netdebug.h File Reference
netdebug.h File Reference
#include <stdio.h>
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <errno.h>
Defines
#define NET_DBG_SOCKSTATE 0x01
#define NET_DBG_ARP 0x10
#define NET_DBG_DHCP 0x20
Functions
void NutTraceTcp (FILE *stream, uint8_t flags)
Control TCP tracing.
void NutTracePPP (FILE *stream, uint8_t flags)
Control PPP tracing.
void NutDumpTcpHeader (FILE *stream, char *ds, TCPSOCKET *sock, NETBUF *nb)
void NutDumpSockState (FILE *stream, uint8_t state, char *lead, char *trail)
void NutDumpSocketList (FILE *stream)
void NutDumpLcpOption (FILE *stream, NETBUF *nb)
void NutDumpLcp (FILE *stream, NETBUF *nb)
void NutDumpPpp (FILE *stream, NETBUF *nb)
Variables
FILE * __tcp_trs
TCP trace output stream.
uint_fast8_t __tcp_trf
TCP trace flags.
FILE * __ppp_trs
PPP trace output stream.
uint_fast8_t __ppp_trf
PPP trace flags.
Define Documentation
#define NET_DBG_SOCKSTATE 0x01
Definition at line 80 of file netdebug.h.
#define NET_DBG_ARP 0x10
Definition at line 81 of file netdebug.h.
#define NET_DBG_DHCP 0x20
Definition at line 82 of file netdebug.h.
Function Documentation
void NutTraceTcp (FILE * stream, uint8_t flags)
Control TCP tracing.
Parameters:
stream Pointer to a previously opened stream or null to leave it unchanged.
flags Flags to enable specific traces.
Examples:
httpd/httpserv.c.
Definition at line 202 of file netdebug.c.
References __tcp_trf, and __tcp_trs.
Referenced by main().
void NutTracePPP (FILE * stream, uint8_t flags)
Control PPP tracing.
Parameters:
stream Pointer to a previously opened stream or null to disable trace output.
flags Flags to enable specific traces.
Examples:
httpd/httpserv.c.
Definition at line 429 of file pppdebug.c.
References __ppp_trf, and __ppp_trs.
Referenced by main().
void NutDumpTcpHeader (FILE * stream, char * ds, TCPSOCKET * sock, NETBUF * nb)
Definition at line 105 of file netdebug.c.
References fprintf(), fprintf_P, fputs(), _NETBUF::nb_ap, _NETBUF::nb_tp, ntohl, prog_char, _NBDATA::sz, TH_ACK, tcphdr::th_ack, TH_FIN, tcphdr::th_flags, TH_PUSH, TH_RST, tcphdr::th_seq, TH_SYN, TH_URG, and _NBDATA::vp.
Referenced by NutTcpOutput(), NutTcpReject(), NutTcpSm(), and NutTcpStateRetranTimeout().
void NutDumpSockState (FILE * stream, uint8_t state, char * lead, char * trail)
Definition at line 126 of file netdebug.c.
References fputs(), TCPS_CLOSE_WAIT, TCPS_CLOSED, TCPS_CLOSING, TCPS_ESTABLISHED, TCPS_FIN_WAIT_1, TCPS_FIN_WAIT_2, TCPS_LAST_ACK, TCPS_LISTEN, TCPS_SYN_RECEIVED, TCPS_SYN_SENT, and TCPS_TIME_WAIT.
Referenced by NutDumpSocketList().
void NutDumpSocketList (FILE * stream)
Definition at line 173 of file netdebug.c.
References fprintf(), fprintf_P, fputs(), inet_ntoa(), ntohs, NutDumpSockState(), prog_char, tcp_socket::so_local_addr, udp_socket::so_local_port, tcp_socket::so_local_port, udp_socket::so_next, tcp_socket::so_next, tcp_socket::so_remote_addr, tcp_socket::so_remote_port, and tcp_socket::so_state.
void NutDumpLcpOption (FILE * stream, NETBUF * nb)
Definition at line 89 of file pppdebug.c.
References fprintf(), fputs(), LCP_ACCOMPRESSION, LCP_ASYNCMAP, LCP_AUTHTYPE, LCP_MAGICNUMBER, LCP_MRU, LCP_PCOMPRESSION, _NETBUF::nb_ap, _NETBUF::nb_dl, ntohl, ntohs, _NBDATA::sz, XCPOPT::ul, XCPOPT::us, _NBDATA::vp, XCPOPT::xcpo_, XCPOPT::xcpo_len, and XCPOPT::xcpo_type.
Referenced by NutDumpLcp().
void NutDumpLcp (FILE * stream, NETBUF * nb)
Definition at line 134 of file pppdebug.c.
References fprintf(), fputs(), fputs_P, LCP_DRQ, LCP_ERP, LCP_ERQ, LCP_PROTREJ, _NETBUF::nb_ap, _NETBUF::nb_dl, _NETBUF::nb_nw, ntohs, NutDumpLcpOption(), _NBDATA::sz, _NBDATA::vp, xcphdr::xch_code, xcphdr::xch_id, xcphdr::xch_len, XCP_CODEREJ, XCP_CONFACK, XCP_CONFNAK, XCP_CONFREJ, XCP_CONFREQ, XCP_TERMACK, and XCP_TERMREQ.
Referenced by NutDumpPpp().
void NutDumpPpp (FILE * stream, NETBUF * nb)
Definition at line 365 of file pppdebug.c.
References ppp_header::address, AHDLC_ALLSTATIONS, fprintf(), fputs(), _NETBUF::nb_ap, _NETBUF::nb_dl, _NETBUF::nb_nw, _NETBUF::nb_tp, ntohs, NutDumpIpcp(), NutDumpLcp(), NutDumpPap(), PPP_IP, PPP_IPCP, PPP_LCP, PPP_PAP, ppp_header::prot_type, _NBDATA::sz, and _NBDATA::vp.
Referenced by NutPppInput(), and NutPppOutput().
Variable Documentation
FILE* __tcp_trs
TCP trace output stream.
Definition at line 102 of file netdebug.c.
Referenced by DhcpStateDebug(), NutArpCacheQuery(), NutArpCacheUpdate(), NutDhcpClient(), NutDhcpIfConfig(), NutTcpOutput(), NutTcpReject(), NutTcpSm(), NutTcpStateRetranTimeout(), and NutTraceTcp().
uint_fast8_t __tcp_trf
TCP trace flags.
Definition at line 103 of file netdebug.c.
Referenced by DhcpStateDebug(), NutArpCacheQuery(), NutArpCacheUpdate(), NutDhcpClient(), NutDhcpIfConfig(), NutTcpOutput(), NutTcpReject(), NutTcpSm(), NutTcpStateRetranTimeout(), and NutTraceTcp().
FILE* __ppp_trs
PPP trace output stream.
Definition at line 71 of file pppdebug.c.
Referenced by IpcpClose(), IpcpLowerDown(), IpcpLowerUp(), IpcpOpen(), LcpClose(), LcpLowerDown(), LcpLowerUp(), LcpOpen(), NutPppInput(), NutPppOutput(), and NutTracePPP().
uint_fast8_t __ppp_trf
PPP trace flags.
Definition at line 72 of file pppdebug.c.
Referenced by IpcpClose(), IpcpLowerDown(), IpcpLowerUp(), IpcpOpen(), LcpClose(), LcpLowerDown(), LcpLowerUp(), LcpOpen(), NutPppInput(), NutPppOutput(), and NutTracePPP().