Nut/OS: net/netdebug.c File Reference
netdebug.c File Reference
#include <arpa/inet.h>
#include <netinet/in.h>
#include <netinet/ip.h>
#include <netinet/icmp.h>
#include <netinet/ip_icmp.h>
#include <netinet/ipcsum.h>
#include <net/netdebug.h>
#include <sys/socket.h>
Functions
void NutDumpTcpHeader (FILE *stream, char *ds, TCPSOCKET *sock, NETBUF *nb)
void NutDumpSockState (FILE *stream, uint8_t state, char *lead, char *trail)
void NutDumpSocketList (FILE *stream)
void NutTraceTcp (FILE *stream, uint8_t flags)
Control TCP tracing.
Variables
TCPSOCKET * tcpSocketList
UDPSOCKET * udpSocketList
FILE * __tcp_trs
TCP trace output stream.
uint_fast8_t __tcp_trf
TCP trace flags.
Function Documentation
void NutDumpTcpHeader (FILE * stream, char * ds, TCPSOCKET * sock, NETBUF * nb)
Definition at line 105 of file netdebug.c.
References fprintf(), fprintf_P, fputs(), _NETBUF::nb_ap, _NETBUF::nb_tp, ntohl, prog_char, _NBDATA::sz, TH_ACK, tcphdr::th_ack, TH_FIN, tcphdr::th_flags, TH_PUSH, TH_RST, tcphdr::th_seq, TH_SYN, TH_URG, and _NBDATA::vp.
Referenced by NutTcpOutput(), NutTcpReject(), NutTcpSm(), and NutTcpStateRetranTimeout().
void NutDumpSockState (FILE * stream, uint8_t state, char * lead, char * trail)
Definition at line 126 of file netdebug.c.
References fputs(), TCPS_CLOSE_WAIT, TCPS_CLOSED, TCPS_CLOSING, TCPS_ESTABLISHED, TCPS_FIN_WAIT_1, TCPS_FIN_WAIT_2, TCPS_LAST_ACK, TCPS_LISTEN, TCPS_SYN_RECEIVED, TCPS_SYN_SENT, and TCPS_TIME_WAIT.
Referenced by NutDumpSocketList().
void NutDumpSocketList (FILE * stream)
Definition at line 173 of file netdebug.c.
References fprintf(), fprintf_P, fputs(), inet_ntoa(), ntohs, NutDumpSockState(), prog_char, tcp_socket::so_local_addr, udp_socket::so_local_port, tcp_socket::so_local_port, udp_socket::so_next, tcp_socket::so_next, tcp_socket::so_remote_addr, tcp_socket::so_remote_port, and tcp_socket::so_state.
void NutTraceTcp (FILE * stream, uint8_t flags)
Control TCP tracing.
Parameters:
stream Pointer to a previously opened stream or null to leave it unchanged.
flags Flags to enable specific traces.
Definition at line 202 of file netdebug.c.
References __tcp_trf, and __tcp_trs.
Referenced by main().
Variable Documentation
FILE* __tcp_trs
TCP trace output stream.
Definition at line 102 of file netdebug.c.
Referenced by DhcpStateDebug(), NutArpCacheQuery(), NutArpCacheUpdate(), NutDhcpClient(), NutDhcpIfConfig(), NutTcpOutput(), NutTcpReject(), NutTcpSm(), NutTcpStateRetranTimeout(), and NutTraceTcp().
uint_fast8_t __tcp_trf
TCP trace flags.
Definition at line 103 of file netdebug.c.
Referenced by DhcpStateDebug(), NutArpCacheQuery(), NutArpCacheUpdate(), NutDhcpClient(), NutDhcpIfConfig(), NutTcpOutput(), NutTcpReject(), NutTcpSm(), NutTcpStateRetranTimeout(), and NutTraceTcp().