Nut/OS: include/sys/osdebug.h File Reference
osdebug.h File Reference
#include <stdio.h>
#include <compiler.h>
#include <sys/thread.h>
Functions
void NutTraceOs (FILE *stream, uint8_t flags)
Control OS tracing.
void NutDumpThreadQueue (FILE *stream, NUTTHREADINFO *tdp)
Dump system queue contents.
void NutDumpThreadList (FILE *stream)
Dump system thread list.
void NutDumpTimerList (FILE *stream)
Dump system timer list.
void NutTraceHeap (FILE *stream, uint8_t flags)
Control dynamic memory tracing.
void NutDumpHeap (FILE *stream)
Dump free node list of heap memory.
Variables
FILE * __os_trs
uint_fast8_t __os_trf
FILE * __heap_trs
uint_fast8_t __heap_trf
Function Documentation
void NutTraceOs (FILE * stream, uint8_t flags)
Control OS tracing.
Parameters:
stream Pointer to a previously opened stream associated to a debug device or null to disable trace output.
flags Flags to enable specific traces.
Examples:
httpd/httpserv.c, and timers/timers.c.
Definition at line 249 of file osdebug.c.
References __os_trf, and __os_trs.
Referenced by main().
void NutDumpThreadQueue (FILE * stream, NUTTHREADINFO * tdp)
Dump system queue contents.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
tdp Pointer to the queue.
Warning:
Interrupts are disabled inside this funtion.
Definition at line 118 of file osdebug.c.
References DEADBEEF, fprintf_P, fputs(), prog_char, SIGNALED, and _NUTTHREADINFO::td_name.
void NutDumpThreadList (FILE * stream)
Dump system thread list.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
Warning:
Interrupts are disabled inside this funtion.
Definition at line 157 of file osdebug.c.
References DEADBEEF, fprintf_P, fputc(), fputs(), fputs_P, nutThreadList, NutThreadStackAvailable(), prog_char, SIGNALED, and _NUTTHREADINFO::td_name.
Referenced by NutThreadCreate().
void NutDumpTimerList (FILE * stream)
Dump system timer list.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
Warning:
Interrupts are disabled inside this funtion.
Definition at line 208 of file osdebug.c.
References fprintf_P, fputs_P, NutEventTimeout(), NutThreadWake(), nutTimerList, prog_char, and _NUTTIMERINFO::tn_ticks.
void NutTraceHeap (FILE * stream, uint8_t flags)
Control dynamic memory tracing.
Parameters:
stream Pointer to a previously opened stream or null to disable trace output.
flags Flags to enable specific traces.
Examples:
httpd/httpserv.c, and timers/timers.c.
Definition at line 302 of file osdebug.c.
References __heap_trf, and __heap_trs.
Referenced by main().
void NutDumpHeap (FILE * stream)
Dump free node list of heap memory.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
Definition at line 265 of file osdebug.c.
References fprintf_P, fputc(), heapFreeList, _HEAPNODE::hn_next, _HEAPNODE::hn_size, NutHeapAvailable, and prog_char.
Variable Documentation
FILE* __os_trs
Definition at line 93 of file osdebug.c.
uint_fast8_t __os_trf
Definition at line 94 of file osdebug.c.
FILE* __heap_trs
Definition at line 96 of file osdebug.c.
Referenced by NutTraceHeap().
uint_fast8_t __heap_trf
Definition at line 97 of file osdebug.c.
Referenced by NutTraceHeap().