Nut/OS: os/panic.c File Reference
panic.c File Reference
Panic handler.
#include <stdio.h>
#include <sys/atom.h>
#include <sys/nutdebug.h>
Functions
void NUTPANIC (CONST char *fmt,...)
This function is called on fatal errors.
Detailed Description
Panic handler.
 * $Id: panic.c 2458 2009-02-13 14:45:20Z haraldkipp $
 *
Definition in file panic.c.
Function Documentation
void NUTPANIC (CONST char * fmt, ...)
This function is called on fatal errors.
The function will enter a critical section and print a description of the problem to stdout. It is assumed, that stdout is available and has been assigned to a debug output device, such as devDebug or similar. Then the function will enter an endless loop, which freezes the system.
If this is not, what the application is expected to do on fatal errors or if no debug device has been assigned to stdout, the application must define its own version of this routine.
Parameters:
fmt Format string containing conversion specifications.
Definition at line 63 of file panic.c.
References NutEnterCritical, stdout, and vfprintf().
Referenced by NUTFATAL(), and NutHeapRootFree().