Nut/OS: arch/avr/dev/pcmcia.c File Reference
pcmcia.c File Reference
#include <compiler.h>
#include <dev/wlantypes.h>
#include <dev/pcmcia.h>
Defines
#define __PCMCIA_C__
#define BASE_ADDRESS 0x8800
#define DATA_LOW 0
#define DATA_HIGH 1
#define ADDRESS_LOW 2
#define ADDRESS_HIGH 3
#define CTRL 4
#define CTRL_CE1 0x01
#define CTRL_CE2 0x02
#define CTRL_OE 0x04
#define CTRL_WE 0x08
#define CTRL_IORD 0x10
#define CTRL_IOWR 0x20
#define CTRL_REGS 0x40
#define CTRL_DATA_OUT 0x80
#define DATA_LOW_REG *((volatile BYTE *)BASE_ADDRESS+DATA_LOW)
#define DATA_HIGH_REG *((volatile BYTE *)BASE_ADDRESS+DATA_HIGH)
#define ADDRESS_LOW_REG *((volatile BYTE *)BASE_ADDRESS+ADDRESS_LOW)
#define ADDRESS_HIGH_REG *((volatile BYTE *)BASE_ADDRESS+ADDRESS_HIGH)
#define CTRL_REG *((volatile BYTE *)BASE_ADDRESS+CTRL)
#define DELAY_CE_WRITE()
#define DELAY_WRITE()
#define DELAY_WRITE_CE()
#define DELAY_CE_READ()
#define DELAY_READ() _NOP();_NOP(); _NOP();_NOP()
#define DELAY_READ_CE()
Enumerations
enum MEMORY_TYPE { TYPE_IO = 0, TYPE_MEM }
Functions
void pcmcia_WriteMem (WORD wAddress, WORD wData)
void pcmcia_WriteReg (WORD wAddress, WORD wData)
WORD pcmcia_ReadMem (WORD wAddress)
WORD pcmcia_ReadReg (WORD wAddress)
Define Documentation
#define __PCMCIA_C__
Definition at line 38 of file pcmcia.c.
#define BASE_ADDRESS 0x8800
Definition at line 58 of file pcmcia.c.
#define DATA_LOW 0
Definition at line 59 of file pcmcia.c.
#define DATA_HIGH 1
Definition at line 60 of file pcmcia.c.
#define ADDRESS_LOW 2
Definition at line 61 of file pcmcia.c.
#define ADDRESS_HIGH 3
Definition at line 62 of file pcmcia.c.
#define CTRL 4
Definition at line 63 of file pcmcia.c.
#define CTRL_CE1 0x01
Definition at line 68 of file pcmcia.c.
#define CTRL_CE2 0x02
Definition at line 69 of file pcmcia.c.
#define CTRL_OE 0x04
Definition at line 70 of file pcmcia.c.
#define CTRL_WE 0x08
Definition at line 71 of file pcmcia.c.
#define CTRL_IORD 0x10
Definition at line 72 of file pcmcia.c.
#define CTRL_IOWR 0x20
Definition at line 73 of file pcmcia.c.
#define CTRL_REGS 0x40
Definition at line 74 of file pcmcia.c.
#define CTRL_DATA_OUT 0x80
Definition at line 75 of file pcmcia.c.
#define DATA_LOW_REG *((volatile BYTE *)BASE_ADDRESS+DATA_LOW)
Definition at line 77 of file pcmcia.c.
#define DATA_HIGH_REG *((volatile BYTE *)BASE_ADDRESS+DATA_HIGH)
Definition at line 78 of file pcmcia.c.
#define ADDRESS_LOW_REG *((volatile BYTE *)BASE_ADDRESS+ADDRESS_LOW)
Definition at line 79 of file pcmcia.c.
#define ADDRESS_HIGH_REG *((volatile BYTE *)BASE_ADDRESS+ADDRESS_HIGH)
Definition at line 80 of file pcmcia.c.
#define CTRL_REG *((volatile BYTE *)BASE_ADDRESS+CTRL)
Definition at line 81 of file pcmcia.c.
#define DELAY_CE_WRITE ()
Definition at line 86 of file pcmcia.c.
#define DELAY_WRITE ()
Definition at line 87 of file pcmcia.c.
#define DELAY_WRITE_CE ()
Definition at line 88 of file pcmcia.c.
#define DELAY_CE_READ ()
Definition at line 90 of file pcmcia.c.
#define DELAY_READ () _NOP();_NOP(); _NOP();_NOP()
Definition at line 91 of file pcmcia.c.
#define DELAY_READ_CE ()
Definition at line 92 of file pcmcia.c.
Enumeration Type Documentation
enum MEMORY_TYPE
Enumerator:
TYPE_IO
TYPE_MEM
Definition at line 94 of file pcmcia.c.
Function Documentation
void pcmcia_WriteMem (WORD wAddress, WORD wData)
Definition at line 235 of file pcmcia.c.
References TYPE_MEM.
Referenced by wlandrv_ProbeDevice().
void pcmcia_WriteReg (WORD wAddress, WORD wData)
Definition at line 243 of file pcmcia.c.
References TYPE_IO.
Referenced by wlandrv_ProbeDevice().
WORD pcmcia_ReadMem (WORD wAddress)
Definition at line 251 of file pcmcia.c.
References TYPE_MEM.
WORD pcmcia_ReadReg (WORD wAddress)
Definition at line 259 of file pcmcia.c.
References TYPE_IO.
Referenced by wlandrv_ProbeDevice().