Nut/OS: include/dev/pcmcia.h File Reference
pcmcia.h File Reference
#include <compiler.h>
#include <dev/wlantypes.h>
Functions
void pcmcia_WriteReg (WORD wAddress, WORD wData)
void pcmcia_WriteMem (WORD wAddress, WORD wData)
WORD pcmcia_ReadReg (WORD wAddress)
WORD pcmcia_ReadMem (WORD wAddress)
Function Documentation
void pcmcia_WriteReg (WORD wAddress, WORD wData)
Definition at line 243 of file pcmcia.c.
References TYPE_IO.
Referenced by wlandrv_ProbeDevice().
void pcmcia_WriteMem (WORD wAddress, WORD wData)
Definition at line 235 of file pcmcia.c.
References TYPE_MEM.
Referenced by wlandrv_ProbeDevice().
WORD pcmcia_ReadReg (WORD wAddress)
Definition at line 259 of file pcmcia.c.
References TYPE_IO.
Referenced by wlandrv_ProbeDevice().
WORD pcmcia_ReadMem (WORD wAddress)
Definition at line 251 of file pcmcia.c.
References TYPE_MEM.