Nut/OS: crt/putenv.c File Reference
putenv.c File Reference
#include <sys/environ.h>
#include <sys/nutdebug.h>
#include <stdlib.h>
#include <string.h>
Functions
int putenv (CONST char *string)
Add a new or update an existing environment variable.
Function Documentation
int putenv (CONST char * string)
Add a new or update an existing environment variable.
Parameters:
Points to a string of the form 'name=value'.
Returns:
0 upon successful completion. Otherwise, -1 is returned and errno is set to indicate the error.
Definition at line 50 of file putenv.c.
References free(), NUTASSERT, setenv(), strchr(), and strdup().