Nut/OS: app/rs232d/rs232d.c File Reference
rs232d.c File Reference
#include <dev/board.h>
#include <sys/heap.h>
#include <sys/thread.h>
#include <sys/timer.h>
#include <sys/socket.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <io.h>
#include <fcntl.h>
#include <arpa/inet.h>
#include <net/if_var.h>
#include <pro/dhcp.h>
Data Structures
struct CHANNEL
Defines
#define BUFFERSIZE 128
#define TCPPORT 23
Functions
void StreamCopy (FILE *istream, FILE *ostream, char *cop)
void Receiver (void *arg)
int main (void)
Define Documentation
#define BUFFERSIZE 128
Examples:
rs232d/rs232d.c.
Definition at line 69 of file rs232d.c.
Referenced by StreamCopy().
#define TCPPORT 23
Examples:
rs232d/rs232d.c.
Definition at line 70 of file rs232d.c.
Referenced by main().
Function Documentation
void StreamCopy (FILE * istream, FILE * ostream, char * cop)
Examples:
rs232d/rs232d.c.
Definition at line 81 of file rs232d.c.
References BUFFERSIZE, fflush(), fread(), free(), fwrite(), and malloc().
Referenced by main(), and Receiver().
void Receiver (void * arg)
Examples:
rs232d/rs232d.c.
Definition at line 102 of file rs232d.c.
References CHANNEL::cd_connected, CHANNEL::cd_rs232, CHANNEL::cd_tcpip, NutThreadSetPriority(), NutThreadYield(), and StreamCopy().
Referenced by main().
int main (void)
Definition at line 125 of file rs232d.c.
References _fdopen(), _fileno(), _ioctl(), CHANNEL::cd_connected, CHANNEL::cd_rs232, CHANNEL::cd_tcpip, DEV_ETHER, DEV_ETHER_NAME, DEV_UART, DEV_UART_NAME, fclose(), fopen(), inet_addr(), NutDhcpIfConfig(), NutNetIfConfig(), NutRegisterDevice(), NutTcpAccept(), NutTcpCloseSocket(), NutTcpCreateSocket(), NutThreadCreate(), Receiver(), StreamCopy(), TCPPORT, and UART_SETSPEED.