Nut/OS: dev/rtc.c File Reference
rtc.c File Reference
RTC for Philips PCF8563 clock chip.
#include <dev/rtc.h>
Functions
int NutRegisterRtc (NUTRTC *rtc)
Register a specified RTC.
int NutRtcGetTime (struct _tm *tm)
Get date and time from the registered RTC.
int NutRtcSetTime (CONST struct _tm *tm)
Set date and time of the registered RTC.
int NutRtcGetAlarm (int idx, struct _tm *tm, int *aflags)
Get alarm date and time from the registered RTC.
int NutRtcSetAlarm (int idx, CONST struct _tm *tm, int aflags)
Set alarm date and time of the registered RTC.
int NutRtcGetStatus (uint32_t *sflags)
Query status flags from the registered RTC.
int NutRtcClearStatus (uint32_t sflags)
Clear status flags of the registered RTC.
Detailed Description
RTC for Philips PCF8563 clock chip.
 *
 * $Log$
 * Revision 1.3  2008/08/11 06:59:42  haraldkipp
 * BSD types replaced by stdint types (feature request #1282721).
 *
 * Revision 1.2  2006/10/08 16:48:09  haraldkipp
 * Documentation fixed
 *
 * Revision 1.1  2006/10/05 17:18:49  haraldkipp
 * Hardware independant RTC layer added.
 *
 *
 *
Definition in file rtc.c.
Function Documentation
int NutRegisterRtc (NUTRTC * rtc)
Register a specified RTC.
This will also initialize any hardware, if required.
Parameters:
rtc Pointer to the NUTRTC structure.
Returns:
0 on success or -1 in case of an error.
Definition at line 69 of file rtc.c.
References _NUTRTC::rtc_init.
Referenced by main().
int NutRtcGetTime (struct _tm * tm)
Get date and time from the registered RTC.
Portable applications should use standard C functions.
Parameters:
tm Points to a structure that receives the date and time information.
Returns:
0 on success or -1 in case of an error.
Definition at line 91 of file rtc.c.
References _NUTRTC::rtc_gettime.
Referenced by time().
int NutRtcSetTime (CONST struct _tm * tm)
Set date and time of the registered RTC.
Portable applications should stime().
Parameters:
tm Points to a structure which contains the date and time information.
Returns:
0 on success or -1 in case of an error.
Definition at line 109 of file rtc.c.
References _NUTRTC::rtc_settime.
Referenced by stime().
int NutRtcGetAlarm (int idx, struct _tm * tm, int * aflags)
Get alarm date and time from the registered RTC.
Parameters:
idx Zero based index. Two alarms are supported.
tm Points to a structure that receives the date and time information.
aflags Points to an unsigned long that receives the enable flags.
Returns:
0 on success or -1 in case of an error.
Definition at line 128 of file rtc.c.
References _NUTRTC::rtc_getalarm.
int NutRtcSetAlarm (int idx, CONST struct _tm * tm, int aflags)
Set alarm date and time of the registered RTC.
Parameters:
idx Zero based index. Two alarms are supported.
tm Points to a structure which contains the date and time information. May be NULL to clear the alarm.
aflags Each bit enables a specific comparision.
Bit 0: Seconds
Bit 1: Minutes
Bit 2: Hours
Bit 3: Day of month
Bit 4: Month
Bit 7: Day of week (Sunday is zero)
Returns:
0 on success or -1 in case of an error.
Definition at line 152 of file rtc.c.
References _NUTRTC::rtc_setalarm.
int NutRtcGetStatus (uint32_t * sflags)
Query status flags from the registered RTC.
Parameters:
sflags Points to an unsigned long that receives the status flags.
Bit 0: Power fail.
Bit 5: Alarm 0 occured.
Bit 6: Alarm 1 occured.
Returns:
0 on success or -1 in case of an error.
Definition at line 170 of file rtc.c.
References _NUTRTC::rtc_getstatus.
Referenced by main().
int NutRtcClearStatus (uint32_t sflags)
Clear status flags of the registered RTC.
Parameters:
sflags Status flags to clear.
Returns:
Always 0.
Definition at line 185 of file rtc.c.
References _NUTRTC::rtc_clrstatus.