Nut/OS: crt/setenv.c File Reference
setenv.c File Reference
#include <dev/nvmem.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <memdebug.h>
#include <sys/environ.h>
#include <cfg/crt.h>
Functions
int setenv (CONST char *name, CONST char *value, int force)
Remove an environment variable.
void unsetenv (CONST char *name)
Remove an environment variable.
Function Documentation
int setenv (CONST char * name, CONST char * value, int force)
Remove an environment variable.
Parameters:
name Points to a string, which is the name of the variable.
value Points to a string, which is the value of the variable.
force If not zero, existing values will be updated.
Returns:
0 upon successful completion. Otherwise, -1 is returned and errno is set to indicate the error.
Definition at line 96 of file setenv.c.
References _NUTENVIRONMENT::env_name, _NUTENVIRONMENT::env_next, _NUTENVIRONMENT::env_prev, _NUTENVIRONMENT::env_value, findenv(), free(), malloc(), memset(), nut_environ, strcmp(), and strdup().
Referenced by putenv().
void unsetenv (CONST char * name)
Remove an environment variable.
Parameters:
name Points to a string, which is the name of the variable to be removed.
Returns:
0 upon successful completion. Otherwise, -1 is returned and errno is set to indicate the error.
Definition at line 195 of file setenv.c.
References ENOENT, _NUTENVIRONMENT::env_name, _NUTENVIRONMENT::env_next, _NUTENVIRONMENT::env_prev, _NUTENVIRONMENT::env_value, errno, findenv(), free(), and nut_environ.