Nut/OS: app/snmpd/snmpd.c File Reference
snmpd.c File Reference
#include <dev/board.h>
#include <sys/types.h>
#include <ctype.h>
#include <errno.h>
#include <arpa/inet.h>
#include <net/route.h>
#include <pro/dhcp.h>
#include <sys/version.h>
#include <sys/timer.h>
#include <pro/snmp_config.h>
#include <pro/snmp_mib.h>
#include <pro/snmp_api.h>
#include <pro/snmp_agent.h>
#include <stdio.h>
#include <io.h>
#include "mib2sys.h"
#include "mib2if.h"
Defines
#define MYMAC 0x00, 0x06, 0x98, 0x33, 0x44, 0x00
Default MAC. Used if EEPROM is empty.
#define MYIP "192.168.192.100"
Default local IP address. Used if EEPROM configuration and DHCP is unavailable.
#define MYMASK "255.255.255.0"
Default IP mask. Used if EEPROM configuration and DHCP is unavailable.
#define MYGATE "192.168.192.1"
Default gateway address. Used if EEPROM configuration and DHCP is unavailable. Only required if syslog or time server are located in a different network.
#define MYUART DEV_CONSOLE_NAME
Device name used for UART output.
#define MYDEV DEV_CONSOLE
Output device.
#define MYBAUD 115200
UART baudrate.
#define COMPILERNAME "GCC"
#define UART_OK 0x0001
#define STDOUT_OK 0x0002
#define STDERR_OK 0x0004
#define BAUDRATE_OK 0x0008
#define LANDEV_OK 0x0010
#define NETIF_OK 0x0020
#define NETROUTE_OK 0x0040
#define TIMED_OK 0x0080
Functions
int main (void)
Define Documentation
#define MYMAC 0x00, 0x06, 0x98, 0x33, 0x44, 0x00
Default MAC. Used if EEPROM is empty.
Definition at line 66 of file snmpd.c.
Referenced by main().
#define MYIP "192.168.192.100"
Default local IP address. Used if EEPROM configuration and DHCP is unavailable.
Definition at line 70 of file snmpd.c.
Referenced by main().
#define MYMASK "255.255.255.0"
Default IP mask. Used if EEPROM configuration and DHCP is unavailable.
Definition at line 74 of file snmpd.c.
Referenced by main().
#define MYGATE "192.168.192.1"
Default gateway address. Used if EEPROM configuration and DHCP is unavailable. Only required if syslog or time server are located in a different network.
Definition at line 80 of file snmpd.c.
Referenced by main().
#define MYUART DEV_CONSOLE_NAME
Device name used for UART output.
Definition at line 83 of file snmpd.c.
Referenced by main().
#define MYDEV DEV_CONSOLE
Output device.
Definition at line 86 of file snmpd.c.
Referenced by main().
#define MYBAUD 115200
UART baudrate.
Definition at line 89 of file snmpd.c.
Referenced by main().
#define COMPILERNAME "GCC"
Definition at line 104 of file snmpd.c.
Referenced by main().
#define UART_OK 0x0001
Definition at line 111 of file snmpd.c.
Referenced by main().
#define STDOUT_OK 0x0002
Definition at line 112 of file snmpd.c.
Referenced by main().
#define STDERR_OK 0x0004
Definition at line 113 of file snmpd.c.
Referenced by main().
#define BAUDRATE_OK 0x0008
Definition at line 114 of file snmpd.c.
Referenced by main().
#define LANDEV_OK 0x0010
Definition at line 115 of file snmpd.c.
Referenced by main().
#define NETIF_OK 0x0020
Definition at line 116 of file snmpd.c.
Referenced by main().
#define NETROUTE_OK 0x0040
Definition at line 117 of file snmpd.c.
Referenced by main().
#define TIMED_OK 0x0080
Definition at line 118 of file snmpd.c.
Function Documentation
int main (void)
Definition at line 120 of file snmpd.c.
References _fileno(), _ioctl(), BAUDRATE_OK, COMPILERNAME, DEV_ETHER, freopen(), inet_addr(), LANDEV_OK, MibRegisterIfVars(), MibRegisterSysVars(), MYBAUD, MYDEV, MYGATE, MYIP, MYMAC, MYMASK, MYUART, NETIF_OK, NETROUTE_OK, NutDhcpIfConfig(), NutIpRouteAdd(), NutNetIfConfig(), NutRegisterDevice(), NutSleep(), NutUdpCreateSocket(), NutUdpDestroySocket(), NutUdpSetSockOpt(), NutVersionString(), printf, puts, SNMP_MAX_MSG_SIZE, SNMP_OID_INTERNET, SNMP_PORT, SNMP_VIEW_INCLUDED, SnmpAgent(), SnmpCommunityCreate(), SnmpViewCreate(), SO_RCVBUF, stderr, STDERR_OK, stdout, STDOUT_OK, UART_OK, and UART_SETSPEED.