Nut/OS: arch/arm/debug/stackdump.c File Reference
stackdump.c File Reference
#include <stdio.h>
#include <sys/ptrace.h>
#include <arch/arm/ptrace.h>
Functions
void ptrace_stackdump_from (const int *fp)
void ptrace_stackdump_regs (struct pt_regs *p)
void ptrace_stackdump_here (void)
Detailed Description
 * $Id: stackdump.c 2399 2009-01-16 19:39:07Z haraldkipp $
 *
Definition in file stackdump.c.
Function Documentation
void ptrace_stackdump_from (const int * fp)
Definition at line 64 of file stackdump.c.
References printf, and puts.
Referenced by ptrace_stackdump_here(), and ptrace_stackdump_regs().
void ptrace_stackdump_regs (struct pt_regs * p)
Definition at line 89 of file stackdump.c.
References ptrace_dump_regs(), PTRACE_R13_idx, ptrace_stackdump_from(), and pt_regs::uregs.
Referenced by ARM_COMMON_Handler_crash().
void ptrace_stackdump_here (void)
Definition at line 96 of file stackdump.c.
References ptrace_stackdump_from().