Nut/OS: include/stdio.h File Reference
stdio.h File Reference
C Standard I/O.
#include <sys/types.h>
#include <stdarg.h>
Defines
#define _STDIO_H_
#define EOF (-1)
End of file.
#define _IOFBF 0x00
Fully buffered.
#define _IOLBF 0x01
Line buffered.
#define _IONBF 0x02
Unbuffered.
#define stdin (__iob[0])
Standard input stream.
#define stdout (__iob[1])
Standard output stream.
#define stderr (__iob[2])
Standard error output stream.
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
Typedefs
typedef struct __iobuf FILE
Stream structure type.
Functions
void clearerr (FILE *stream)
Reset error status of a stream.
int fclose (FILE *stream)
Close a stream.
void fcloseall (void)
Close all open streams.
FILE * _fdopen (int fd, CONST char *mode)
Open a stream associated with a file, device or socket descriptor.
int feof (FILE *stream)
Test if a stream reached the end of file.
int ferror (FILE *stream)
Test for an error on a stream.
int fflush (FILE *stream)
Flush a stream.
int fgetc (FILE *stream)
Read a character from a stream.
char * fgets (char *buffer, int count, FILE *stream)
Read a line from a stream.
int _fileno (FILE *stream)
Get the file descriptor associated with a stream.
void _flushall (void)
Flushes all streams.
FILE * fopen (CONST char *name, CONST char *mode)
Open a stream.
int fprintf (FILE *stream, CONST char *fmt,...)
Print formatted data to a stream.
int fpurge (FILE *stream)
Purge a stream, i.e. discards the input buffer.
int fputc (int c, FILE *stream)
Write a character to a stream.
int fputs (CONST char *string, FILE *stream)
Write a string to a stream.
size_t fread (void *buffer, size_t size, size_t count, FILE *stream)
Read data from a stream.
FILE * freopen (CONST char *name, CONST char *mode, FILE *stream)
Reassign a stream.
int fscanf (FILE *stream, CONST char *fmt,...)
Read formatted data from a stream.
int fseek (FILE *stream, long offset, int origin)
Move read/write position of a stream.
long ftell (FILE *stream)
Return the read/write position of a stream.
size_t fwrite (CONST void *data, size_t size, size_t count, FILE *stream)
Write data to a stream.
int getc (FILE *stream)
Read a character from a stream.
int getchar (void)
Read a character from a standard input.
int kbhit (void)
char * gets (char *buffer)
Get a line from the standard input stream.
int printf (CONST char *fmt,...)
Print formatted data to the standard output stream.
int putc (int c, FILE *stream)
Write a character to a stream.
int putchar (int c)
Write a character to standard output.
int puts (CONST char *string)
Write a string to stdout.
int scanf (CONST char *fmt,...)
Read formatted data from the standard input stream.
int sprintf (char *buffer, CONST char *fmt,...)
Write formatted data to a string.
int sscanf (CONST char *string, CONST char *fmt,...)
Read formatted data from a string.
int ungetc (int c, FILE *stream)
Push a character back onto a stream.
int vfprintf (FILE *stream, CONST char *fmt, va_list ap)
Write argument list to a stream using a given format.
int vfscanf (FILE *stream, CONST char *fmt, va_list ap)
Read formatted data from a stream.
int vsprintf (char *buffer, CONST char *fmt, va_list ap)
Write argument list to a string using a given format.
int vsscanf (CONST char *string, CONST char *fmt, va_list ap)
Read formatted data from a string.
int rename (CONST char *old_name, CONST char *new_name)
Rename a file.
int fprintf_P (FILE *stream, PGM_P fmt,...)
Print formatted data to a stream.
int fputs_P (PGM_P string, FILE *stream)
Write a string from progam memory to a stream.
int fscanf_P (FILE *stream, PGM_P fmt,...)
Read formatted data from a stream.
size_t fwrite_P (PGM_P data, size_t size, size_t count, FILE *stream)
Write data from program space to a stream.
int printf_P (PGM_P fmt,...)
Print formatted output to the standard output stream.
int puts_P (PGM_P string)
Write a string from program memory to stdout.
int scanf_P (PGM_P fmt,...)
Read formatted data from the standard input stream.
int sprintf_P (char *buffer, PGM_P fmt,...)
Write formatted data to a string.
int sscanf_P (CONST char *string, CONST char *fmt,...)
Read formatted data from a string.
int vfprintf_P (FILE *stream, PGM_P fmt, va_list ap)
Write argument list to a stream using a given format.
int vfscanf_P (FILE *stream, PGM_P fmt, va_list ap)
Read formatted data from a stream.
int vsprintf_P (char *buffer, PGM_P fmt, va_list ap)
Write argument list to a string using a given format.
int vsscanf_P (CONST char *string, PGM_P fmt, va_list ap)
Read formatted data from a string.
Variables
FILE * __iob []
Detailed Description
C Standard I/O.
Definition in file stdio.h.
Define Documentation
#define _STDIO_H_
Definition at line 73 of file stdio.h.
#define SEEK_SET 0
Definition at line 130 of file stdio.h.
Referenced by PerCiFlush(), PerCiOpen(), and PerCiWrite().
#define SEEK_CUR 1
Definition at line 134 of file stdio.h.
Referenced by _tell(), and PerCiOpen().
#define SEEK_END 2
Definition at line 138 of file stdio.h.
Function Documentation
int kbhit (void)
Examples:
caltime/caltime.c, and editconf/editconf.c.
Definition at line 46 of file kbhit.c.
References _filelength(), _fileno(), and stdin.
Referenced by main().