Nut/OS: _MMCIFC Struct Reference
_MMCIFC Struct Reference
Multimedia Card Driver
Low level access information structure.
#include <mmcard.h>
Data Fields
int(* mmcifc_in)(void)
uint8_t(* mmcifc_io)(uint8_t)
int(* mmcifc_cs)(int)
int(* mmcifc_cd)(void)
int(* mmcifc_wp)(void)
Detailed Description
Low level access information structure.
Definition at line 97 of file mmcard.h.
Field Documentation
int(* _MMCIFC::mmcifc_in)(void)
Initialize the card.
Definition at line 99 of file mmcard.h.
uint8_t(* _MMCIFC::mmcifc_io)(uint8_t)
Read received byte and transmit a new one.
Definition at line 101 of file mmcard.h.
int(* _MMCIFC::mmcifc_cs)(int)
Select or deselect the card.
Definition at line 103 of file mmcard.h.
int(* _MMCIFC::mmcifc_cd)(void)
Query card detect.
Definition at line 105 of file mmcard.h.
Referenced by MmCardBlockRead(), MmCardBlockWrite(), MmCardIOCtl(), MmCardMount(), and MmCardUnmount().
int(* _MMCIFC::mmcifc_wp)(void)
Query write protect.
Definition at line 107 of file mmcard.h.
The documentation for this struct was generated from the following file:
include/dev/mmcard.h