Nut/OS: _NUTVIRTUALDEVICE Struct Reference
_NUTVIRTUALDEVICE Struct Reference
Device Management
Virtual device structure.
#include <device.h>
Data Fields
NUTVIRTUALDEVICE * vdv_next
NUTVIRTUALDEVICE * vdv_zero
uint8_t vdv_type
int(* vdv_read)(void *, void *, int)
int(* vdv_write)(void *, CONST void *, int)
int(* vdv_write_P)(void *, PGM_P, int)
int(* vdv_ioctl)(void *, int, void *)
Detailed Description
Virtual device structure.
Definition at line 274 of file device.h.
Field Documentation
NUTVIRTUALDEVICE* _NUTVIRTUALDEVICE::vdv_next
Definition at line 275 of file device.h.
NUTVIRTUALDEVICE* _NUTVIRTUALDEVICE::vdv_zero
Definition at line 276 of file device.h.
uint8_t _NUTVIRTUALDEVICE::vdv_type
Definition at line 277 of file device.h.
int(* _NUTVIRTUALDEVICE::vdv_read)(void *, void *, int)
Definition at line 278 of file device.h.
Referenced by _read().
int(* _NUTVIRTUALDEVICE::vdv_write)(void *, CONST void *, int)
Definition at line 279 of file device.h.
Referenced by _close(), and _write().
int(* _NUTVIRTUALDEVICE::vdv_write_P)(void *, PGM_P, int)
Definition at line 281 of file device.h.
Referenced by _write_P().
int(* _NUTVIRTUALDEVICE::vdv_ioctl)(void *, int, void *)
Definition at line 283 of file device.h.
Referenced by _filelength(), and _ioctl().
The documentation for this struct was generated from the following file:
include/sys/device.h