Nut/OS: _NUTRTC Struct Reference
_NUTRTC Struct Reference
RTC device structure.
#include <rtc.h>
Data Fields
int(* rtc_init)(void)
int(* rtc_gettime)(struct _tm *)
int(* rtc_settime)(CONST struct _tm *)
int(* rtc_getalarm)(int idx, struct _tm *, int *)
int(* rtc_setalarm)(int idx, CONST struct _tm *, int)
int(* rtc_getstatus)(uint32_t *)
int(* rtc_clrstatus)(uint32_t)
Detailed Description
RTC device structure.
Definition at line 80 of file rtc.h.
Field Documentation
int(* _NUTRTC::rtc_init)(void)
Definition at line 81 of file rtc.h.
Referenced by NutRegisterRtc().
int(* _NUTRTC::rtc_gettime)(struct _tm *)
Definition at line 82 of file rtc.h.
Referenced by NutRtcGetTime().
int(* _NUTRTC::rtc_settime)(CONST struct _tm *)
Definition at line 83 of file rtc.h.
Referenced by NutRtcSetTime().
int(* _NUTRTC::rtc_getalarm)(int idx, struct _tm *, int *)
Definition at line 84 of file rtc.h.
Referenced by NutRtcGetAlarm().
int(* _NUTRTC::rtc_setalarm)(int idx, CONST struct _tm *, int)
Definition at line 85 of file rtc.h.
Referenced by NutRtcSetAlarm().
int(* _NUTRTC::rtc_getstatus)(uint32_t *)
Definition at line 86 of file rtc.h.
Referenced by NutRtcGetStatus().
int(* _NUTRTC::rtc_clrstatus)(uint32_t)
Definition at line 87 of file rtc.h.
Referenced by NutRtcClearStatus().
The documentation for this struct was generated from the following file:
include/dev/rtc.h