Nut/OS: _NUTSERIALFLASH Struct Reference
_NUTSERIALFLASH Struct Reference
XgSerialflash
Serial flash support information structure.
#include <serialflash.h>
Data Fields
NUTSPINODE * sf_node
Pointer to the SPI node structure.
void * sf_info
Pointer to a local information structure.
size_t sf_unit_size
Size of the erase/write unit.
sf_unit_t sf_units
Total number of units available, including reserved ones.
sf_unit_t sf_rsvbot
Configurable number of reserved units at the bottom.
sf_unit_t sf_rsvtop
Configurable number of reserved units at the top.
int(* sf_init)(NUTSERIALFLASH *)
Flash device initialization.
void(* sf_exit)(NUTSERIALFLASH *)
Release the flash device.
int(* sf_check)(NUTSERIALFLASH *, sf_unit_t, int)
Check a number of units.
int(* sf_read)(NUTSERIALFLASH *, sf_unit_t, int, void *, int)
Read bytes from a unit.
int(* sf_compare)(NUTSERIALFLASH *, sf_unit_t, int, CONST void *, int)
Compare bytes of a unit.
int(* sf_used)(NUTSERIALFLASH *, sf_unit_t, int)
Find first used byte.
int(* sf_write)(NUTSERIALFLASH *, sf_unit_t, int, CONST void *, int)
Write bytes from a unit.
int(* sf_copy)(NUTSERIALFLASH *, sf_unit_t, sf_unit_t)
Copy a unit.
int(* sf_commit)(NUTSERIALFLASH *, sf_unit_t)
Commit changes.
int(* sf_erase)(NUTSERIALFLASH *, sf_unit_t, int)
Erase a number of units.
Detailed Description
Serial flash support information structure.
Definition at line 70 of file serialflash.h.
Field Documentation
NUTSPINODE* _NUTSERIALFLASH::sf_node
Pointer to the SPI node structure.
Definition at line 72 of file serialflash.h.
Referenced by UFlashAttach(), and UFlashFormat().
void* _NUTSERIALFLASH::sf_info
Pointer to a local information structure.
Definition at line 74 of file serialflash.h.
size_t _NUTSERIALFLASH::sf_unit_size
Size of the erase/write unit.
Definition at line 76 of file serialflash.h.
sf_unit_t _NUTSERIALFLASH::sf_units
Total number of units available, including reserved ones.
Definition at line 78 of file serialflash.h.
Referenced by UFlashFormat().
sf_unit_t _NUTSERIALFLASH::sf_rsvbot
Configurable number of reserved units at the bottom.
Definition at line 80 of file serialflash.h.
Referenced by UFlashFormat().
sf_unit_t _NUTSERIALFLASH::sf_rsvtop
Configurable number of reserved units at the top.
Definition at line 82 of file serialflash.h.
Referenced by UFlashFormat().
int(* _NUTSERIALFLASH::sf_init)(NUTSERIALFLASH *)
Flash device initialization.
Definition at line 84 of file serialflash.h.
Referenced by UFlashAttach(), and UFlashFormat().
void(* _NUTSERIALFLASH::sf_exit)(NUTSERIALFLASH *)
Release the flash device.
Definition at line 86 of file serialflash.h.
Referenced by UFlashDetach(), and UFlashFormat().
int(* _NUTSERIALFLASH::sf_check)(NUTSERIALFLASH *, sf_unit_t, int)
Check a number of units.
Definition at line 88 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_read)(NUTSERIALFLASH *, sf_unit_t, int, void *, int)
Read bytes from a unit.
Definition at line 90 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_compare)(NUTSERIALFLASH *, sf_unit_t, int, CONST void *, int)
Compare bytes of a unit.
Definition at line 92 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_used)(NUTSERIALFLASH *, sf_unit_t, int)
Find first used byte.
Definition at line 94 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_write)(NUTSERIALFLASH *, sf_unit_t, int, CONST void *, int)
Write bytes from a unit.
Definition at line 96 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_copy)(NUTSERIALFLASH *, sf_unit_t, sf_unit_t)
Copy a unit.
Definition at line 98 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_commit)(NUTSERIALFLASH *, sf_unit_t)
Commit changes.
Definition at line 100 of file serialflash.h.
int(* _NUTSERIALFLASH::sf_erase)(NUTSERIALFLASH *, sf_unit_t, int)
Erase a number of units.
Definition at line 102 of file serialflash.h.
The documentation for this struct was generated from the following file:
include/dev/serialflash.h