Nut/OS: _USARTDCB Struct Reference
_USARTDCB Struct Reference
USART Driver Frame
USART device low level information structure.
#include <dev/usart.h>
Data Fields
uint32_t dcb_modeflags
Mode flags.
uint32_t dcb_statusflags
Status flags.
uint32_t dcb_rtimeout
Read timeout.
uint32_t dcb_wtimeout
Write timeout.
RINGBUF dcb_tx_rbf
Output ring buffer.
RINGBUF dcb_rx_rbf
Input ring buffer.
uint8_t dcb_last_eol
Last EOL character.
int(* dcb_init)(void)
Driver control initialization.
int(* dcb_deinit)(void)
Driver control de-initialization.
void(* dcb_tx_start)(void)
Driver control write notification.
void(* dcb_rx_start)(void)
Driver control read notification.
int(* dcb_set_flow_control)(uint32_t flags)
Set handshake mode.
uint32_t(* dcb_get_flow_control)(void)
Get handshake mode.
int(* dcb_set_speed)(uint32_t rate)
Set hardware speed.
uint32_t(* dcb_get_speed)(void)
Get hardware speed.
int(* dcb_set_data_bits)(uint8_t bits)
Set hardware data bits.
uint8_t(* dcb_get_data_bits)(void)
Get hardware data bits.
int(* dcb_set_parity)(uint8_t bits)
Set hardware parity mode.
uint8_t(* dcb_get_parity)(void)
Get hardware parity mode.
int(* dcb_set_stop_bits)(uint8_t bits)
Set hardware stop bits.
uint8_t(* dcb_get_stop_bits)(void)
Get hardware stop bits.
int(* dcb_set_status)(uint32_t flags)
Set hardware status.
uint32_t(* dcb_get_status)(void)
Get hardware status.
int(* dcb_set_clock_mode)(uint8_t mode)
Set clock mode.
uint8_t(* dcb_get_clock_mode)(void)
Get clock mode.
Detailed Description
USART device low level information structure.
Definition at line 274 of file usart.h.
Field Documentation
uint32_t _USARTDCB::dcb_modeflags
Mode flags.
Definition at line 278 of file usart.h.
Referenced by UsartIOCtl(), UsartOpen(), and UsartRead().
uint32_t _USARTDCB::dcb_statusflags
Status flags.
Definition at line 282 of file usart.h.
uint32_t _USARTDCB::dcb_rtimeout
Read timeout.
Definition at line 286 of file usart.h.
Referenced by UsartIOCtl(), and UsartRead().
uint32_t _USARTDCB::dcb_wtimeout
Write timeout.
Definition at line 290 of file usart.h.
Referenced by UsartIOCtl().
RINGBUF _USARTDCB::dcb_tx_rbf
Output ring buffer.
Definition at line 294 of file usart.h.
Referenced by Sc16is752UsartProcessChannelInterrupt(), UsartClose(), UsartIOCtl(), and UsartOpen().
RINGBUF _USARTDCB::dcb_rx_rbf
Input ring buffer.
Definition at line 298 of file usart.h.
Referenced by Sc16is752UsartProcessChannelInterrupt(), UsartClose(), UsartIOCtl(), UsartOpen(), UsartRead(), and UsartSize().
uint8_t _USARTDCB::dcb_last_eol
Last EOL character.
Definition at line 302 of file usart.h.
Referenced by UsartRead().
_USARTDCB::dcb_init
Driver control initialization.
Definition at line 308 of file usart.h.
Referenced by UsartInit().
int(* _USARTDCB::dcb_deinit)(void)
Driver control de-initialization.
Definition at line 313 of file usart.h.
void(* _USARTDCB::dcb_tx_start)(void)
Driver control write notification.
Definition at line 318 of file usart.h.
void(* _USARTDCB::dcb_rx_start)(void)
Driver control read notification.
Definition at line 323 of file usart.h.
Referenced by UsartIOCtl(), UsartOpen(), and UsartRead().
int(* _USARTDCB::dcb_set_flow_control)(uint32_t flags)
Set handshake mode.
Definition at line 328 of file usart.h.
Referenced by UsartIOCtl().
uint32_t(* _USARTDCB::dcb_get_flow_control)(void)
Get handshake mode.
Definition at line 333 of file usart.h.
Referenced by UsartIOCtl().
int(* _USARTDCB::dcb_set_speed)(uint32_t rate)
Set hardware speed.
Definition at line 338 of file usart.h.
Referenced by UsartInit(), and UsartIOCtl().
uint32_t(* _USARTDCB::dcb_get_speed)(void)
Get hardware speed.
Definition at line 343 of file usart.h.
Referenced by UsartIOCtl().
int(* _USARTDCB::dcb_set_data_bits)(uint8_t bits)
Set hardware data bits.
Definition at line 348 of file usart.h.
Referenced by UsartIOCtl().
uint8_t(* _USARTDCB::dcb_get_data_bits)(void)
Get hardware data bits.
Definition at line 353 of file usart.h.
Referenced by UsartIOCtl().
int(* _USARTDCB::dcb_set_parity)(uint8_t bits)
Set hardware parity mode.
Definition at line 358 of file usart.h.
Referenced by UsartIOCtl().
uint8_t(* _USARTDCB::dcb_get_parity)(void)
Get hardware parity mode.
Definition at line 363 of file usart.h.
Referenced by UsartIOCtl().
int(* _USARTDCB::dcb_set_stop_bits)(uint8_t bits)
Set hardware stop bits.
Definition at line 368 of file usart.h.
Referenced by UsartIOCtl().
uint8_t(* _USARTDCB::dcb_get_stop_bits)(void)
Get hardware stop bits.
Definition at line 373 of file usart.h.
Referenced by UsartIOCtl().
int(* _USARTDCB::dcb_set_status)(uint32_t flags)
Set hardware status.
Definition at line 378 of file usart.h.
Referenced by UsartClose(), and UsartIOCtl().
uint32_t(* _USARTDCB::dcb_get_status)(void)
Get hardware status.
Definition at line 383 of file usart.h.
Referenced by UsartIOCtl().
int(* _USARTDCB::dcb_set_clock_mode)(uint8_t mode)
Set clock mode.
Definition at line 388 of file usart.h.
Referenced by UsartIOCtl().
uint8_t(* _USARTDCB::dcb_get_clock_mode)(void)
Get clock mode.
Definition at line 393 of file usart.h.
Referenced by UsartIOCtl().
The documentation for this struct was generated from the following file:
include/dev/usart.h