Nut/OS: IRQ_HANDLER Struct Reference
IRQ_HANDLER Struct Reference
Interrupt Management
#include <irqreg.h>
Data Fields
void * ir_arg
void(* ir_handler)(void *)
int(* ir_ctl)(int cmd, void *param)
Detailed Description
Definition at line 146 of file irqreg.h.
Field Documentation
void* IRQ_HANDLER::ir_arg
Definition at line 150 of file irqreg.h.
Referenced by CallHandler(), InterruptNMIEntry(), NplRegisterIrqHandler(), NutRegisterIrqHandler(), Uart0IrqEntry(), and Uart1IrqEntry().
void(* IRQ_HANDLER::ir_handler)(void *)
Definition at line 151 of file irqreg.h.
Referenced by CallHandler(), InterruptNMIEntry(), NplRegisterIrqHandler(), NutRegisterIrqHandler(), NutRegisterTimer(), Uart0IrqEntry(), and Uart1IrqEntry().
int(* IRQ_HANDLER::ir_ctl)(int cmd, void *param)
Definition at line 152 of file irqreg.h.
Referenced by NplIrqDisable(), NplIrqEnable(), NplRegisterIrqHandler(), NutIrqDisable(), NutIrqEnable(), NutIrqSetMode(), NutIrqSetPriority(), and NutRegisterIrqHandler().
The documentation for this struct was generated from the following file:
include/dev/irqreg.h