Nut/OS: GPIO_SIGNAL Struct Reference
GPIO_SIGNAL Struct Reference
#include <gpio.h>
Data Fields
IRQ_HANDLER * ios_sig
void(* ios_handler)(void *)
int(* ios_ctl)(int cmd, void *param, int bit)
GPIO_VECTOR * ios_vector
Detailed Description
Definition at line 134 of file gpio.h.
Field Documentation
IRQ_HANDLER* GPIO_SIGNAL::ios_sig
Definition at line 135 of file gpio.h.
Referenced by GpioRegisterIrqHandler().
void(* GPIO_SIGNAL::ios_handler)(void *)
Definition at line 136 of file gpio.h.
Referenced by GpioRegisterIrqHandler().
int(* GPIO_SIGNAL::ios_ctl)(int cmd, void *param, int bit)
Definition at line 137 of file gpio.h.
Referenced by GpioIrqDisable(), and GpioIrqEnable().
GPIO_VECTOR* GPIO_SIGNAL::ios_vector
Definition at line 138 of file gpio.h.
Referenced by GpioRegisterIrqHandler().
The documentation for this struct was generated from the following file:
include/dev/gpio.h