Nut/OS: app/threads/threads.c File Reference
threads.c File Reference
#include <stdio.h>
#include <io.h>
#include <cfg/arch.h>
#include <dev/board.h>
#include <sys/thread.h>
#include <sys/timer.h>
Functions
void Thread1 (void *arg)
void Thread2 (void *arg)
int main (void)
Function Documentation
void Thread1 (void * arg)
Examples:
threads/threads.c.
Definition at line 60 of file threads.c.
References NutSleep(), NutThreadSetPriority(), and putchar().
Referenced by main().
void Thread2 (void * arg)
Examples:
threads/threads.c.
Definition at line 75 of file threads.c.
References NutSleep(), NutThreadSetPriority(), and putchar().
Referenced by main().
int main (void)
Definition at line 90 of file threads.c.
References _fileno(), _ioctl(), DEV_CONSOLE, DEV_CONSOLE_NAME, freopen(), NutRegisterDevice(), NutSleep(), NutThreadCreate(), putchar(), puts, stdout, Thread1(), Thread2(), and UART_SETSPEED.