Nut/OS: app/timers/timers.c File Reference
timers.c File Reference
#include <cfg/os.h>
#include <sys/osdebug.h>
#include <stdio.h>
#include <io.h>
#include <cfg/arch.h>
#include <dev/board.h>
#include <sys/thread.h>
#include <sys/timer.h>
#include <sys/event.h>
#include <sys/heap.h>
Functions
void TimerCallback (HANDLE timer, void *arg)
void TimerEvent1 (void *arg)
void TimerEvent2 (void *arg)
void TimerEvent3 (void *arg)
void TimerEvent4 (void *arg)
void Sleeper1 (void *arg)
void Sleeper2 (void *arg)
void Sleeper3 (void *arg)
void Sleeper4 (void *arg)
int main (void)
Function Documentation
void TimerCallback (HANDLE timer, void * arg)
Examples:
timers/timers.c.
Definition at line 83 of file timers.c.
References NutEventPostAsync().
Referenced by main().
void TimerEvent1 (void * arg)
Examples:
timers/timers.c.
Definition at line 88 of file timers.c.
References NutEventWait(), NutThreadSetPriority(), and printf.
Referenced by main().
void TimerEvent2 (void * arg)
Examples:
timers/timers.c.
Definition at line 100 of file timers.c.
References NutEventWait(), NutThreadSetPriority(), and printf.
Referenced by main().
void TimerEvent3 (void * arg)
Examples:
timers/timers.c.
Definition at line 112 of file timers.c.
References NutEventWait(), NutThreadSetPriority(), and printf.
Referenced by main().
void TimerEvent4 (void * arg)
Examples:
timers/timers.c.
Definition at line 124 of file timers.c.
References NutEventWait(), NutThreadSetPriority(), and printf.
Referenced by main().
void Sleeper1 (void * arg)
Examples:
timers/timers.c.
Definition at line 136 of file timers.c.
References NutHeapAvailable, NutSleep(), NutThreadSetPriority(), printf, and puts.
Referenced by main().
void Sleeper2 (void * arg)
Examples:
timers/timers.c.
Definition at line 148 of file timers.c.
References NutSleep(), NutThreadSetPriority(), and printf.
Referenced by main().
void Sleeper3 (void * arg)
Examples:
timers/timers.c.
Definition at line 157 of file timers.c.
References NutSleep(), NutThreadSetPriority(), and printf.
Referenced by main().
void Sleeper4 (void * arg)
Examples:
timers/timers.c.
Definition at line 166 of file timers.c.
References NutSleep(), NutThreadSetPriority(), and printf.
Referenced by main().
int main (void)
Definition at line 179 of file timers.c.
References _fileno(), _ioctl(), DEV_CONSOLE, DEV_CONSOLE_NAME, freopen(), NutGetCpuClock(), NutHeapAvailable, NutRegisterDevice(), NutSleep(), NutThreadCreate(), NutThreadSetPriority(), NutTimerStart(), NutTimerStop(), NutTraceHeap(), NutTraceOs(), printf, puts, Sleeper1(), Sleeper2(), Sleeper3(), Sleeper4(), stdout, TimerCallback(), TimerEvent1(), TimerEvent2(), TimerEvent3(), TimerEvent4(), TM_ONESHOT, and UART_SETSPEED.