Nut/OS: app/uart/uart.c File Reference
uart.c File Reference
#include <cfg/crt.h>
#include <string.h>
#include <stdio.h>
#include <io.h>
#include <dev/board.h>
#include <sys/timer.h>
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 69 of file uart.c.
References _fileno(), _ioctl(), _read(), _write(), _write_P(), DEV_CONSOLE, DEV_CONSOLE_NAME, fflush(), fgets(), fopen(), fprintf(), fputs(), fputs_P, NutRegisterDevice(), strchr(), strlen(), and UART_SETSPEED.