Nut/OS: app/httpd_upnp/httpserv.c File Reference
httpserv.c File Reference
#include <cfg/os.h>
#include <string.h>
#include <io.h>
#include <fcntl.h>
#include <time.h>
#include <dev/board.h>
#include <dev/urom.h>
#include <dev/nplmmc.h>
#include <dev/sbimmc.h>
#include <fs/phatfs.h>
#include <sys/version.h>
#include <sys/thread.h>
#include <sys/timer.h>
#include <sys/heap.h>
#include <sys/confnet.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <net/route.h>
#include <netinet/in.h>
#include <pro/httpd.h>
#include <pro/dhcp.h>
#include <pro/ssi.h>
#include <pro/asp.h>
#include <pro/discover.h>
#include "upnp.h"
Defines
#define HTTPD_SERVICE_STACK ((1024 * NUT_THREAD_STACK_MULT) + NUT_THREAD_STACK_ADD)
Functions
void Service (void *arg)
int main (void)
Main application routine.
Define Documentation
#define HTTPD_SERVICE_STACK ((1024 * NUT_THREAD_STACK_MULT) + NUT_THREAD_STACK_ADD)
Definition at line 82 of file httpserv.c.
Referenced by main().
Function Documentation
void Service (void * arg)
Definition at line 97 of file httpserv.c.
References _fdopen(), fclose(), NutHeapAvailable, NutHttpProcessRequest(), NutSleep(), NutTcpAccept(), NutTcpCloseSocket(), NutTcpCreateSocket(), and printf.
int main (void)
Main application routine.
Nut/OS automatically calls this entry after initialization.
Definition at line 166 of file httpserv.c.
References _fileno(), _ioctl(), _CONFNET::cdn_ip_addr, confnet, DEV_CONSOLE, DEV_CONSOLE_NAME, DEV_ETHER, DEV_ETHER_NAME, devUrom, freopen(), HTTPD_SERVICE_STACK, INADDR_ALLHOSTS_GROUP, inet_ntoa(), NutDhcpIfConfig(), NutNetIfAddMcastAddr(), NutNetLoadConfig(), NutRegisterCgiBinPath(), NutRegisterDevice(), NutSleep(), NutThreadCreate(), NutThreadSetPriority(), NutVersionString(), printf, puts, Service(), stdout, UART_SETSPEED, and upnp_Init().