Nut/OS: app/httpd_upnp/upnp.h File Reference
upnp.h File Reference
Functions
void upnp_Init (void)
Function Documentation
void upnp_Init (void)
Definition at line 445 of file upnp.c.
References _NUTDEVICE::dev_icb, NotifyTask(), NutDeviceLookup(), NutNetIfAddMcastAddr(), NutRegisterCgi(), NutThreadCreate(), printf, puts, SSDP_IP, SSDPTask(), UPNP_CGI_NAME, and UPNP_SERVICE_STACK.
Referenced by main().