Nut/OS: arch/avr/dev/wlan.c File Reference
wlan.c File Reference
#include <compiler.h>
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <sys/heap.h>
#include <sys/timer.h>
#include <netinet/if_ether.h>
#include <net/ether.h>
#include <net/if_var.h>
#include <dev/wlantypes.h>
#include <dev/wlan.h>
#include <dev/wlandrv.h>
Defines
#define __WLAN_C__
#define ERROR -1
#define OK 0
Functions
int WlanInit (NUTDEVICE *dev)
int WlanIOCtl (NUTDEVICE *dev, int req, void *conf)
int WlanOutput (NUTDEVICE *dev, NETBUF *nb)
Variables
NUTDEVICE devWlan
Define Documentation
#define __WLAN_C__
Definition at line 37 of file wlan.c.
#define ERROR -1
Definition at line 58 of file wlan.c.
Referenced by WlanInit(), and WlanOutput().
#define OK 0
Definition at line 59 of file wlan.c.
Referenced by WlanInit().
Function Documentation
int WlanInit (NUTDEVICE * dev)
Definition at line 145 of file wlan.c.
References _NUTDEVICE::dev_dcb, ERROR, memset(), NutHeapAlloc, OK, wlandrv_Attach(), wlandrv_Init(), and wlandrv_ProbeDevice().
int WlanIOCtl (NUTDEVICE * dev, int req, void * conf)
Definition at line 202 of file wlan.c.
References wlandrv_IOCTL().
int WlanOutput (NUTDEVICE * dev, NETBUF * nb)
Definition at line 224 of file wlan.c.
References ERROR, and wlandrv_PutPacket().
Variable Documentation
NUTDEVICE devWlan
Initial value:
 {
    0,
    {'w', 'l', 'a', 'n', '0', 0, 0, 0, 0},
    IFTYP_NET,
    0,
    0,
    &ifn_eth0,
    0,
    WlanInit,
    WlanIOCtl,
    0,
    0,
    0,
    0,
    0,
    0
}
Definition at line 103 of file wlan.c.