Nut/OS: include/dev/wlan.h File Reference
wlan.h File Reference
#include <dev/netbuf.h>
#include <net/if_var.h>
Data Structures
struct _wlan_wep_key
struct _wlan_config
struct _wlan_status
Defines
#define DEV_ETHER devWlan
#define WLAN_NETWORK_NAME_MAX_LEN 32
#define WLAN_WEP_MAX_KEY_COUNT 4
#define WLAN_WEP_MAX_KEY_SIZE 16
Typedefs
typedef struct _wlan_wep_key WLAN_WEP_KEY
typedef struct _wlan_config WLAN_CONFIG
typedef struct _wlan_status WLAN_STATUS
Enumerations
enum WLAN_IOCTL { WLAN_IOCTL_GET_MAC_ADDRESS = 1, WLAN_IOCTL_SET_CONFIG, WLAN_IOCTL_GET_STATUS }
enum WLAN_MODE { WLAN_MODE_STOP = 0, WLAN_MODE_STATION, WLAN_MODE_ADHOC }
enum WLAN_STATUS_PORT {
WLAN_STATUS_PORT_DISABLE = 1, WLAN_STATUS_PORT_SEARCHING = 2, WLAN_STATUS_PORT_CONN_IBSS = 3, WLAN_STATUS_PORT_CONN_ESS = 4,
WLAN_STATUS_PORT_OOR_ESS = 5
}
enum WLAN_WEP { WLAN_USE_NO_WEP = 0, WLAN_USE_64BIT_WEP = 5, WLAN_USE_128BIT_WEP = 13 }
Functions
int WlanInit (NUTDEVICE *dev)
int WlanIOCtl (NUTDEVICE *dev, int req, void *conf)
int WlanOutput (NUTDEVICE *dev, NETBUF *nb)
Variables
NUTDEVICE devWlan
Define Documentation
#define DEV_ETHER devWlan
Definition at line 53 of file wlan.h.
#define WLAN_NETWORK_NAME_MAX_LEN 32
Definition at line 59 of file wlan.h.
#define WLAN_WEP_MAX_KEY_COUNT 4
Definition at line 64 of file wlan.h.
Referenced by wlandrv_IOCTL().
#define WLAN_WEP_MAX_KEY_SIZE 16
Definition at line 65 of file wlan.h.
Referenced by wlandrv_IOCTL().
Typedef Documentation
typedef struct _wlan_wep_key WLAN_WEP_KEY
typedef struct _wlan_config WLAN_CONFIG
typedef struct _wlan_status WLAN_STATUS
Enumeration Type Documentation
enum WLAN_IOCTL
Enumerator:
WLAN_IOCTL_GET_MAC_ADDRESS
WLAN_IOCTL_SET_CONFIG
WLAN_IOCTL_GET_STATUS
Definition at line 74 of file wlan.h.
enum WLAN_MODE
Enumerator:
WLAN_MODE_STOP
WLAN_MODE_STATION
WLAN_MODE_ADHOC
Definition at line 85 of file wlan.h.
enum WLAN_STATUS_PORT
Enumerator:
WLAN_STATUS_PORT_DISABLE
WLAN_STATUS_PORT_SEARCHING
WLAN_STATUS_PORT_CONN_IBSS
WLAN_STATUS_PORT_CONN_ESS
WLAN_STATUS_PORT_OOR_ESS
Definition at line 94 of file wlan.h.
enum WLAN_WEP
Enumerator:
WLAN_USE_NO_WEP
WLAN_USE_64BIT_WEP
WLAN_USE_128BIT_WEP
Definition at line 105 of file wlan.h.
Function Documentation
int WlanInit (NUTDEVICE * dev)
Definition at line 145 of file wlan.c.
References _NUTDEVICE::dev_dcb, ERROR, memset(), NutHeapAlloc, OK, wlandrv_Attach(), wlandrv_Init(), and wlandrv_ProbeDevice().
int WlanIOCtl (NUTDEVICE * dev, int req, void * conf)
Definition at line 202 of file wlan.c.
References wlandrv_IOCTL().
int WlanOutput (NUTDEVICE * dev, NETBUF * nb)
Definition at line 224 of file wlan.c.
References ERROR, and wlandrv_PutPacket().
Variable Documentation
NUTDEVICE devWlan
Definition at line 103 of file wlan.c.