type lost\lost.js > all.js
type lost\lost_html.js >> all.js
type lost\lost_alarm.js >> all.js
type lost\lost_alarm_html.js >> all.js
type lost\lost_atm.js >> all.js
type lost\lost_atm_html.js >> all.js
type lost\lost_safety.js >> all.js
type lost\lost_safety_html.js >> all.js
type lost\lost_rooms.js >> all.js
type lost\lost_rooms_html.js >> all.js
type lost\lost_ev.js >> all.js
type lost\lost_ev_html.js >> all.js
