type com\lost.js > mms.js
type com\lost_mon.js >> mms.js
type com\lost_alarm.js >> mms.js
type com\lost_atm.js >> mms.js
type com\lost_safety.js >> mms.js
type com\lost_rooms.js >> mms.js
type com\lost_ev.js >> mms.js
type mms\lost_html.js >> mms.js
type com\lost_mon_html.js >> mms.js
type com\lost_alarm_html.js >> mms.js
type mms\lost_scenes_html.js >> mms.js
type com\lost_safety_html.js >> mms.js
type mms\lost_rooms_html.js >> mms.js
type mms\lost_ev_html.js >> mms.js

type com\lost.js > bt.js
type com\lost_mon.js >> bt.js
type com\lost_alarm.js >> bt.js
type com\lost_atm.js >> bt.js
type com\lost_safety.js >> bt.js
type com\lost_lbcom.js >> bt.js
type com\lost_rooms.js >> bt.js
type com\lost_ev.js >> bt.js
type bt\lost_html.js >> bt.js
type com\lost_mon_html.js >> bt.js
type com\lost_alarm_html.js >> bt.js
type bt\lost_atm_html.js >> bt.js
type bt\lost_safety_html.js >> bt.js
type bt\lost_lbcom_html.js >> bt.js
type bt\lost_rooms_html.js >> bt.js
type bt\lost_ev_html.js >> bt.js

type com\lost.js > lb.js
type com\lost_mon.js >> lb.js
type com\lost_alarm.js >> lb.js
type com\lost_atm.js >> lb.js
type com\lost_safety.js >> lb.js
type com\lost_rooms.js >> lb.js
type com\lost_ev.js >> lb.js
type lb\lost_html.js >> lb.js
type com\lost_mon_html.js >> lb.js
type com\lost_alarm_html.js >> lb.js
type lb\lost_scenes_html.js >> lb.js
type com\lost_safety_html.js >> lb.js
type lb\lost_rooms_html.js >> lb.js
type lb\lost_ev_html.js >> lb.js

type com\lost.js > fr.js
type com\lost_mon.js >> fr.js
type com\lost_alarm.js >> fr.js
type com\lost_atm.js >> fr.js
type com\lost_safety.js >> fr.js
type com\lost_rooms.js >> fr.js
type com\lost_ev.js >> fr.js
type fr\lost_html.js >> fr.js
type com\lost_mon_html.js >> fr.js
type com\lost_alarm_html.js >> fr.js
type fr\lost_atm_html.js >> fr.js
type com\lost_safety_html.js >> fr.js
type fr\lost_rooms_html.js >> fr.js
type fr\lost_ev_html.js >> fr.js
