cat com/lost.js > mms.js
cat com/lost_mon.js >> mms.js
cat com/lost_alarm.js >> mms.js
cat com/lost_atm.js >> mms.js
cat com/lost_safety.js >> mms.js
cat com/lost_rooms.js >> mms.js
cat com/lost_ev.js >> mms.js
cat mms/lost_html.js >> mms.js
cat com/lost_mon_html.js >> mms.js
cat com/lost_alarm_html.js >> mms.js
cat mms/lost_scenes_html.js >> mms.js
cat com/lost_safety_html.js >> mms.js
cat mms/lost_rooms_html.js >> mms.js
cat mms/lost_ev_html.js >> mms.js

cat com/lost.js > bt.js
cat com/lost_mon.js >> bt.js
cat com/lost_alarm.js >> bt.js
cat com/lost_atm.js >> bt.js
cat com/lost_safety.js >> bt.js
cat com/lost_lbcom.js >> bt.js
cat com/lost_rooms.js >> bt.js
cat com/lost_ev.js >> bt.js
cat bt/lost_html.js >> bt.js
cat com/lost_mon_html.js >> bt.js
cat com/lost_alarm_html.js >> bt.js
cat bt/lost_atm_html.js >> bt.js
cat bt/lost_safety_html.js >> bt.js
cat bt/lost_lbcom_html.js >> bt.js
cat bt/lost_rooms_html.js >> bt.js
cat bt/lost_ev_html.js >> bt.js

cat com/lost.js > lb.js
cat com/lost_mon.js >> lb.js
cat com/lost_alarm.js >> lb.js
cat com/lost_atm.js >> lb.js
cat com/lost_safety.js >> lb.js
cat com/lost_rooms.js >> lb.js
cat com/lost_ev.js >> lb.js
cat lb/lost_html.js >> lb.js
cat com/lost_mon_html.js >> lb.js
cat com/lost_alarm_html.js >> lb.js
cat lb/lost_scenes_html.js >> lb.js
cat com/lost_safety_html.js >> lb.js
cat lb/lost_rooms_html.js >> lb.js
cat lb/lost_ev_html.js >> lb.js

cat com/lost.js > fr.js
cat com/lost_mon.js >> fr.js
cat com/lost_alarm.js >> fr.js
cat com/lost_atm.js >> fr.js
cat com/lost_safety.js >> fr.js
cat com/lost_rooms.js >> fr.js
cat com/lost_ev.js >> fr.js
cat fr/lost_html.js >> fr.js
cat com/lost_mon_html.js >> fr.js
cat com/lost_alarm_html.js >> fr.js
cat fr/lost_atm_html.js >> fr.js
cat com/lost_safety_html.js >> fr.js
cat fr/lost_rooms_html.js >> fr.js
cat fr/lost_ev_html.js >> fr.js
