#ifndef _NODE_
#define _NODE_

#define NODE_LIGHT_MAX 10
#define NODE_SHUTTER_MAX 10
#define NODE_HEATER_MAX 10
#define NODE_ELEC_MAX 10
#define NODE_IR_DATA_NB 10
#define NODE_RF_DATA_NB 10

enum NODE_REG_T
{
  NODE_REG_TYPE = 0,
  NODE_REG_VERSION,
  NODE_REG_ADRESS,

  NODE_REG_TEMP_VALUE,
  NODE_REG_TEMP_MAX_TH,
  NODE_REG_TEMP_MAX_CONTROL,
  NODE_REG_TEMP_MAX_TRIG,
  NODE_REG_TEMP_MIN_TH,
  NODE_REG_TEMP_MIN_CONTROL,
  NODE_REG_TEMP_MIN_TRIG,

  NODE_REG_HUM_STATUS,
  NODE_REG_HUM_CONTROL,
  NODE_REG_HUM_TRIG,

  NODE_REG_SMOKE_STATUS,
  NODE_REG_SMOKE_CONTROL,
  NODE_REG_SMOKE_TRIG,

  NODE_REG_PERI_STATUS,
  NODE_REG_PERI_CONTROL,
  NODE_REG_PERI_TRIG,

  NODE_REG_VOL_STATUS,
  NODE_REG_VOL_CONTROL,
  NODE_REG_VOL_TRIG,

  NODE_REG_SIM_STATUS,
  NODE_REG_SIM_CONTROL,
  NODE_REG_SIM_TRIG,

  NODE_REG_LIGHT,
  NODE_REG_SHUTTER = NODE_REG_LIGHT   + NODE_LIGHT_MAX,
  NODE_REG_HEATER  = NODE_REG_SHUTTER + NODE_SHUTTER_MAX,
  NODE_REG_ELEC    = NODE_REG_HEATER  + NODE_HEATER_MAX,

  NODE_REG_IR_TX_TYPE = NODE_REG_ELEC + NODE_ELEC_MAX,
  NODE_REG_IR_TX_SRC_ADDR,
  NODE_REG_IR_TX_DEST_ADDR,
  NODE_REG_IR_TX_CTRL,
  NODE_REG_IR_TX_DATA,
  NODE_REG_IR_TX_ACK = NODE_REG_IR_TX_DATA + NODE_IR_DATA_NB,

  NODE_REG_IR_RX_TYPE,
  NODE_REG_IR_RX_SRC_ADDR,
  NODE_REG_IR_RX_DEST_ADDR,
  NODE_REG_IR_RX_CTRL,
  NODE_REG_IR_RX_DATA,
  NODE_REG_IR_RX_ACK = NODE_REG_IR_RX_DATA + NODE_IR_DATA_NB,

  NODE_REG_RF_TX_TYPE,
  NODE_REG_RF_TX_SRC_ADDR,
  NODE_REG_RF_TX_DEST_ADDR,
  NODE_REG_RF_TX_CTRL,
  NODE_REG_RF_TX_DATA,
  NODE_REG_RF_TX_ACK = NODE_REG_RF_TX_DATA + NODE_RF_DATA_NB,

  NODE_REG_RF_RX_TYPE,
  NODE_REG_RF_RX_SRC_ADDR,
  NODE_REG_RF_RX_DEST_ADDR,
  NODE_REG_RF_RX_CTRL,
  NODE_REG_RF_RX_DATA,
  NODE_REG_RF_RX_ACK = NODE_REG_RF_RX_DATA + NODE_RF_DATA_NB,

  NODE_REG_CLIM,

  NODE_REG_MAX
};

extern u08 node[NODE_REG_MAX];

extern void node_init(void);

#endif
