Nut/OS API
candemo.c File Reference
Defines
#define DEV_CAN devSJA1000
Functions
int main (void)
Variables
CANFRAME canFrame
CANINFO * canInfoPtr
Define Documentation
#define DEV_CAN devSJA1000
Examples:
canbus/candemo.c.
Definition at line 69 of file candemo.c.
Referenced by main().
Function Documentation
int main (void)
Main entry point of application
Definition at line 84 of file candemo.c.
References _fileno(), _ioctl(), AtCanEnableRx(), CAN_SetSpeed(), CAN_SPEED_125K, CAN_TryRxFrame(), CAN_TxFrame(), canFrame, canInfoPtr, DEV_CAN, DEV_DEBUG, DEV_DEBUG_NAME, freopen(), memset(), NutRegisterDevice(), NutSleep(), printf, puts, stdout, and UART_SETSPEED.
Variable Documentation
CANFRAME canFrame
Examples:
canbus/candemo.c.
Definition at line 77 of file candemo.c.
Referenced by main().
CANINFO* canInfoPtr
Examples:
canbus/candemo.c.
Definition at line 78 of file candemo.c.
Referenced by main().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/