Nut/OS API
common_xxx_handler.c File Reference
Functions
void ARM_COMMON_Handler_crash (struct pt_regs *p, const char *name)
Detailed Description
 * $Id: common_xxx_handler.c 2399 2009-01-16 19:39:07Z haraldkipp $
 *
Definition in file common_xxx_handler.c.
Function Documentation
void ARM_COMMON_Handler_crash (struct pt_regs * p, const char * name)
Definition at line 65 of file common_xxx_handler.c.
References printf, ptrace_stackdump_regs(), and putchar().
Referenced by ARM_DA_Handler(), ARM_PFA_Handler(), ARM_SWI_Handler(), and ARM_UDF_Handler().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/