Nut/OS API
config.c File Reference
Functions
size_t ConfigSize (void)
Calculate total size of configuration data.
int ConfigStation (u_char idx, CONST char *url)
Configure a station list entry.
void ConfigResetFactory (void)
Reset configuration.
int ConfigLoad (void)
Load configuration from EEPROM.
void ConfigSaveControl (void)
Save radio control settings.
void ConfigSave (void)
Save configuration in EEPROM.
Variables
RADIOSTATION * station
List of radio stations.
RADIOCONTROL radio
Radio status and control.
Function Documentation
size_t ConfigSize (void)
Calculate total size of configuration data.
Returns:
Number of bytes used by configuration data.
Definition at line 156 of file config.c.
References MAXNUM_STATIONS, RADIOSTATION::rs_ip, RADIOSTATION::rs_port, RADIOSTATION::rs_url, and strlen().
int ConfigStation (u_char idx, CONST char * url)
Configure a station list entry.
Parameters:
idx Index of the entry.
url URL of the station.
Returns:
0 on success, -1 otherwise.
Definition at line 185 of file config.c.
References atoi(), free, inet_addr(), malloc, MAXNUM_STATIONS, RADIOSTATION::rs_ip, RADIOSTATION::rs_port, RADIOSTATION::rs_url, strcpy(), and strlen().
Referenced by ConfigResetFactory().
void ConfigResetFactory (void)
Reset configuration.
Examples:
nutpiper/nutpiper.c.
Definition at line 262 of file config.c.
References ConfigStation(), RADIOCONTROL::rc_rstation, and RADIOCONTROL::rc_rvolume.
Referenced by main().
int ConfigLoad (void)
Load configuration from EEPROM.
If no configuration is available, some preconfigured stations are loaded.
Returns:
0 on success, -1 if no configuration data had been found.
Examples:
nutpiper/nutpiper.c.
Definition at line 350 of file config.c.
References CONFAPP_EE_NAME, CONFAPP_EE_OFFSET, free, malloc, MAXLEN_URL, RADIOCONTROL::rc_rstation, RADIOCONTROL::rc_rvolume, RADIOSTATION::rs_ip, RADIOSTATION::rs_port, RADIOSTATION::rs_url, strcmp(), strcpy(), and strlen().
Referenced by main().
void ConfigSaveControl (void)
Save radio control settings.
Saves currently selected station and volume.
Definition at line 395 of file config.c.
References CONFAPP_EE_NAME, CONFAPP_EE_OFFSET, RADIOCONTROL::rc_cstation, and RADIOCONTROL::rc_cvolume.
void ConfigSave (void)
Save configuration in EEPROM.
Examples:
nutpiper/nutpiper.c.
Definition at line 407 of file config.c.
References CONFAPP_EE_NAME, CONFAPP_EE_OFFSET, NutNetSaveConfig(), RADIOCONTROL::rc_cstation, RADIOCONTROL::rc_cvolume, RADIOSTATION::rs_ip, RADIOSTATION::rs_port, and RADIOSTATION::rs_url.
Variable Documentation
RADIOSTATION* station
List of radio stations.
$Log$ Revision 1.5 2009/02/18 12:18:58 olereinhardt 2009-02-18 Ole Reinhardt <ole.reinhardt@thermotemp.de>
Fixed compilier warnings. Especialy signedness of char buffers as well as unused code on arm platform and main functions without return value
Revision 1.4 2006/07/21 09:06:36 haraldkipp Exclude AVR specific parts from building for other platforms. This does not imply, that all samples are working on all platforms.
Revision 1.3 2004/05/11 17:23:05 drsung Advanced radio stations are now used depending of macro ETHERNUT2.
Revision 1.2 2003/11/04 17:46:52 haraldkipp Adapted to Ethernut 2
Revision 1.1 2003/07/21 17:50:48 haraldkipp First check in
Examples:
nutpiper/nutpiper.c.
Definition at line 74 of file config.c.
Referenced by DisplayEntry(), DisplayStatus(), and Scanner().
RADIOCONTROL radio
Radio status and control.
Examples:
nutpiper/nutpiper.c.
Definition at line 79 of file config.c.
Referenced by DisplayStatus(), main(), and Scanner().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/