Nut/OS API
display.h File Reference
Functions
int DisplayInit (char *name)
Start background thread for display updates.
void DisplayStatus (u_char status)
Display a specified status.
void DisplayMessage (u_char row, u_char secs, CONST char *fmt,...)
Display a specified text.
void DisplayEntry (u_char rs)
Display specified entry of the list of stations.
Function Documentation
int DisplayInit (char * name)
Start background thread for display updates.
$Log$ Revision 1.1 2003/07/21 17:50:48 haraldkipp First check in
Parameters:
name Display device name.
Returns:
0 on success or -1 in case of a failure.
Definition at line 236 of file display.c.
References DISPLAY_VCOLUMNS, Displayer(), DisplayStatus(), DIST_NONE, fopen(), lcd, malloc, mline, NutThreadCreate(), and sline.
Referenced by main().
void DisplayStatus (u_char status)
Display a specified status.
Parameters:
status Status to be displayed.
Definition at line 145 of file display.c.
References DISPLAY_VCOLUMNS, DisplayStation(), DIST_CONNECTED, DIST_CONNECTING, DIST_DEAD, DIST_FORCE, DIST_NONE, NutEventPost(), player, PLAYERINFO::psi_metatitle, radio, RADIOCONTROL::rc_cstation, RADIOCONTROL::rc_cstatus, RADIOSTATION::rs_genre, sline, sprintf, station, strcpy(), strncpy(), and updevt.
Referenced by DisplayInit().
void DisplayMessage (u_char row, u_char secs, CONST char * fmt, ...)
Display a specified text.
Parameters:
row Row position of the message.
secs Number of seconds to display the message. Set to 0 for permanent display.
fmt Format string containing conversion specifications.
Definition at line 186 of file display.c.
References mline, mticks, NutEventPost(), sline, updevt, and vsprintf().
void DisplayEntry (u_char rs)
Display specified entry of the list of stations.
Parameters:
rs Index of the list entry.
Definition at line 206 of file display.c.
References DISPLAY_VCOLUMNS, inet_ntoa(), NutEventPost(), RADIOSTATION::rs_genre, RADIOSTATION::rs_ip, RADIOSTATION::rs_name, RADIOSTATION::rs_port, RADIOSTATION::rs_scandead, RADIOSTATION::rs_scantitle, sline, sprintf, station, strcpy(), strncpy(), and updevt.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/