Nut/OS API
display.c File Reference
Defines
#define DISPLAY_LINES 2
#define DISPLAY_VCOLUMNS 80
Functions
void Displayer (void *arg)
void DisplayStation (RADIOSTATION *rsp)
void DisplayStatus (u_char status)
Display a specified status.
void DisplayMessage (u_char row, u_char secs, CONST char *fmt,...)
Display a specified text.
void DisplayEntry (u_char rs)
Display specified entry of the list of stations.
int DisplayInit (char *name)
Start background thread for display updates.
Variables
u_short lcd_offset
char * sline [2]
char * mline [2]
u_short mticks [2]
FILE * lcd
HANDLE updevt
Define Documentation
#define DISPLAY_LINES 2
Definition at line 59 of file display.c.
Referenced by Displayer().
#define DISPLAY_VCOLUMNS 80
Definition at line 60 of file display.c.
Referenced by DisplayEntry(), DisplayInit(), DisplayStation(), and DisplayStatus().
Function Documentation
void Displayer (void * arg)
Definition at line 73 of file display.c.
References DISPLAY_LINES, ESC_CLREOL, ESC_CURSOROFF, ESC_POS, fprintf(), fputs(), lcd, mline, mticks, NutEventWait(), NutThreadSetPriority(), sline, strlen(), and updevt.
Referenced by DisplayInit().
void DisplayStation (RADIOSTATION * rsp)
Definition at line 129 of file display.c.
References DISPLAY_VCOLUMNS, inet_ntoa(), RADIOSTATION::rs_ip, RADIOSTATION::rs_name, RADIOSTATION::rs_port, sline, and strncpy().
Referenced by DisplayStatus().
void DisplayStatus (u_char status)
Display a specified status.
Parameters:
status Status to be displayed.
Examples:
nutpiper/nutpiper.c.
Definition at line 145 of file display.c.
References DISPLAY_VCOLUMNS, DisplayStation(), DIST_CONNECTED, DIST_CONNECTING, DIST_DEAD, DIST_FORCE, DIST_NONE, NutEventPost(), player, PLAYERINFO::psi_metatitle, radio, RADIOCONTROL::rc_cstation, RADIOCONTROL::rc_cstatus, RADIOSTATION::rs_genre, sline, sprintf, station, strcpy(), strncpy(), and updevt.
Referenced by DisplayInit().
void DisplayMessage (u_char row, u_char secs, CONST char * fmt, ...)
Display a specified text.
Parameters:
row Row position of the message.
secs Number of seconds to display the message. Set to 0 for permanent display.
fmt Format string containing conversion specifications.
Examples:
nutpiper/nutpiper.c.
Definition at line 186 of file display.c.
References mline, mticks, NutEventPost(), sline, updevt, and vsprintf().
void DisplayEntry (u_char rs)
Display specified entry of the list of stations.
Parameters:
rs Index of the list entry.
Examples:
nutpiper/nutpiper.c.
Definition at line 206 of file display.c.
References DISPLAY_VCOLUMNS, inet_ntoa(), NutEventPost(), RADIOSTATION::rs_genre, RADIOSTATION::rs_ip, RADIOSTATION::rs_name, RADIOSTATION::rs_port, RADIOSTATION::rs_scandead, RADIOSTATION::rs_scantitle, sline, sprintf, station, strcpy(), strncpy(), and updevt.
int DisplayInit (char * name)
Start background thread for display updates.
Parameters:
name Display device name.
Returns:
0 on success or -1 in case of a failure.
Examples:
nutpiper/nutpiper.c.
Definition at line 236 of file display.c.
References DISPLAY_VCOLUMNS, Displayer(), DisplayStatus(), DIST_NONE, fopen(), lcd, malloc, mline, NutThreadCreate(), and sline.
Referenced by main().
Variable Documentation
u_short lcd_offset
$Log$ Revision 1.1 2003/07/21 17:50:48 haraldkipp First check in
Definition at line 57 of file display.c.
char* sline[2]
Definition at line 62 of file display.c.
Referenced by DisplayEntry(), Displayer(), DisplayInit(), DisplayMessage(), DisplayStation(), and DisplayStatus().
char* mline[2]
Definition at line 63 of file display.c.
Referenced by Displayer(), DisplayInit(), and DisplayMessage().
u_short mticks[2]
Definition at line 64 of file display.c.
Referenced by Displayer(), and DisplayMessage().
FILE* lcd
Definition at line 66 of file display.c.
Referenced by Displayer(), and DisplayInit().
HANDLE updevt
Definition at line 68 of file display.c.
Referenced by DisplayEntry(), Displayer(), DisplayMessage(), and DisplayStatus().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/