Nut/OS API
environ.c File Reference
Functions
NUTENVIRONMENT * findenv (CONST char *name)
Find an NUTENVIRONMENT entry by name.
Variables
NUTENVIRONMENT * nut_environ
Function Documentation
NUTENVIRONMENT* findenv (CONST char * name)
Find an NUTENVIRONMENT entry by name.
Parameters:
name Points to a string, which is the name of the entry.
Returns:
A pointer to the entry with the specified name. If the name cannot be found, then a null pointer is returned.
Definition at line 81 of file environ.c.
References NUTENVIRONMENT::env_name, NUTENVIRONMENT::env_next, NUTENVIRONMENT::env_prev, NUTENVIRONMENT::env_value, ENVIRON_EE_OFFSET, ENVIRON_MAGIC, free, malloc, MAX_ENVIRON_ITEM_SIZE, memset(), NUTASSERT, NutNvMemLoad(), strcmp(), and strcpy().
Referenced by getenv(), nextenv(), setenv(), and unsetenv().
Variable Documentation
NUTENVIRONMENT* nut_environ
Definition at line 43 of file environ.c.
Referenced by nextenv(), setenv(), and unsetenv().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/