Nut/OS API
exception_c.h File Reference
Functions
void ARM_COMMON_Handler_crash (struct pt_regs *p, const char *name)
void ARM_DA_Handler (struct pt_regs *p)
void ARM_PFA_Handler (struct pt_regs *p)
void ARM_SWI_Handler (struct pt_regs *p)
void ARM_UDF_Handler (struct pt_regs *p)
Detailed Description
 * $Id: exception_c.h 2400 2009-01-16 19:44:05Z haraldkipp $
 *
Definition in file exception_c.h.
Function Documentation
void ARM_COMMON_Handler_crash (struct pt_regs * p, const char * name)
Definition at line 65 of file common_xxx_handler.c.
Referenced by ARM_DA_Handler(), ARM_PFA_Handler(), ARM_SWI_Handler(), and ARM_UDF_Handler().
void ARM_DA_Handler (struct pt_regs * p)
Definition at line 52 of file default_da_handler.c.
void ARM_PFA_Handler (struct pt_regs * p)
Definition at line 52 of file default_pfa_handler.c.
void ARM_SWI_Handler (struct pt_regs * p)
Definition at line 52 of file default_swi_handler.c.
void ARM_UDF_Handler (struct pt_regs * p)
Definition at line 52 of file default_udf_handler.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/