Nut/OS API
getenv.c File Reference
Functions
char * getenv (CONST char *name)
Get the value of an environment variable.
char * nextenv (CONST char *name)
Get the name of the next environment variable.
Function Documentation
char* getenv (CONST char * name)
Get the value of an environment variable.
Parameters:
name Points to a string, which is the name of the variable.
Returns:
A pointer to a string containing the value. If the specified name cannot be found a null pointer will be returned.
Definition at line 45 of file getenv.c.
References NUTENVIRONMENT::env_value, and findenv().
Referenced by MibRegisterSysVars().
char* nextenv (CONST char * name)
Get the name of the next environment variable.
Parameters:
name Points to a string, which is the name of the previous variable. If this pointer is NULL or points to an empty string, then the name of the first variable is returned.
Returns:
A pointer to a string containing the name of the next variable, or NULL if no more variables are available.
Definition at line 68 of file getenv.c.
References NUTENVIRONMENT::env_name, NUTENVIRONMENT::env_next, findenv(), and nut_environ.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/