Nut/OS API
gpio_avr.c File Reference
Functions
int GpioPinGet (int bank, int bit)
void GpioPinSetLow (int bank, int bit)
void GpioPinSetHigh (int bank, int bit)
void GpioPinSet (int bank, int bit, int value)
unsigned int GpioPortGet (int bank)
void GpioPortSet (int bank, unsigned int value)
void GpioPortSetLow (int bank, unsigned int mask)
void GpioPortSetHigh (int bank, unsigned int mask)
uint32_t GpioPinConfigGet (int bank, int bit)
int GpioPortConfigSet (int bank, unsigned int mask, uint32_t flags)
int GpioPinConfigSet (int bank, int bit, uint32_t flags)
int GpioRegisterIrqHandler (GPIO_SIGNAL *sig, int bit, void(*handler)(void *), void *arg)
int GpioIrqEnable (GPIO_SIGNAL *sig, int bit)
int GpioIrqDisable (GPIO_SIGNAL *sig, int bit)
Function Documentation
int GpioPinGet (int bank, int bit)
Copyright (C) 2007 by egnite Software GmbH. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 3. Neither the name of the copyright holders nor the names of contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY EGNITE SOFTWARE GMBH AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL EGNITE SOFTWARE GMBH OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
For additional information see http://www.ethernut.de/
Id
gpio_avr.c 2402 2009-01-17 11:26:52Z haraldkipp
Definition at line 44 of file gpio_avr.c.
References AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, and bit_is_set.
void GpioPinSetLow (int bank, int bit)
Definition at line 99 of file gpio_avr.c.
References AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, and cbi.
void GpioPinSetHigh (int bank, int bit)
Definition at line 165 of file gpio_avr.c.
References AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, and sbi.
void GpioPinSet (int bank, int bit, int value)
Definition at line 231 of file gpio_avr.c.
References GpioPinSetHigh(), and GpioPinSetLow().
unsigned int GpioPortGet (int bank)
Definition at line 241 of file gpio_avr.c.
References AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, and inb.
void GpioPortSet (int bank, unsigned int value)
Definition at line 296 of file gpio_avr.c.
References AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, and outb.
void GpioPortSetLow (int bank, unsigned int mask)
Definition at line 362 of file gpio_avr.c.
References GpioPortGet(), and GpioPortSet().
void GpioPortSetHigh (int bank, unsigned int mask)
Definition at line 367 of file gpio_avr.c.
References GpioPortGet(), and GpioPortSet().
uint32_t GpioPinConfigGet (int bank, int bit)
Definition at line 372 of file gpio_avr.c.
References _BV, AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, GPIO_CFG_OUTPUT, GPIO_CFG_PULLUP, and inb.
int GpioPortConfigSet (int bank, unsigned int mask, uint32_t flags)
Definition at line 501 of file gpio_avr.c.
References AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, AVRPORTG, AVRPORTH, AVRPORTI, AVRPORTJ, AVRPORTK, AVRPORTL, GPIO_CFG_OUTPUT, GPIO_CFG_PULLUP, inb, and outb.
int GpioPinConfigSet (int bank, int bit, uint32_t flags)
Definition at line 700 of file gpio_avr.c.
References _BV, AVRPORTA, AVRPORTB, AVRPORTC, AVRPORTD, AVRPORTE, AVRPORTF, cbi, GPIO_CFG_OUTPUT, GPIO_CFG_PULLUP, GpioPinConfigGet(), GpioPortConfigSet(), and sbi.
int GpioRegisterIrqHandler (GPIO_SIGNAL * sig, int bit, void(*)(void *) handler, void * arg)
Definition at line 812 of file gpio_avr.c.
int GpioIrqEnable (GPIO_SIGNAL * sig, int bit)
Definition at line 817 of file gpio_avr.c.
int GpioIrqDisable (GPIO_SIGNAL * sig, int bit)
Definition at line 822 of file gpio_avr.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/