Nut/OS API
Version Information
[Nut/OS API]
Nut/OS version number.
Functions
uint32_t NutVersion (void)
Return Nut/OS version.
CONST char * NutVersionString (void)
Return Nut/OS version string.
Detailed Description
Nut/OS version number.
The version number is divided into four parts:
Major version number
Minor version number
Release number
Build number
The following code test for version 4.0.1.
 if (NutVersion() < 0x04000100UL) {
     printf("Error: Nut/OS is too old\n");
 }
Function Documentation
uint32_t NutVersion (void)
Return Nut/OS version.
Returns:
Version coded into an unsigned long. Most significant byte is the major version number, followed by the minor version number, again followed by the release number and finally the build number in the least significant byte.
Definition at line 271 of file version.c.
References OS_VERSION_NUMBER.
CONST char* NutVersionString (void)
Return Nut/OS version string.
Returns:
Pointer to a printable string containing the version number. The string contains 4 numbers separated by dots. The first is the major version number, followed by the minor version number, again followed by the release number and finally followed by the build number. In non-official releases this may be optionally followed by a space and an additional release state.
Definition at line 287 of file version.c.
Referenced by main(), MibRegisterSysVars(), NutFtpServerSession(), and NutHttpSendHeaderTop().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/