Nut/OS API
PHAT Debugging Support
[PHAT File System]
Listing various PHAT structures.
Functions
void PhatDbgAttrList (FILE *fp, uint8_t attr)
void PhatDbgDirEntry (FILE *fp, CONST char *title, PHATDIRENT *dent)
void PhatDbgFileInfo (FILE *fp, CONST char *title, PHATFILE *nfp)
void PhatDbgVbr (FILE *fp, CONST char *title, PHATVBR *vbr)
Detailed Description
Listing various PHAT structures.
Function Documentation
void PhatDbgAttrList (FILE * fp, uint8_t attr)
Definition at line 68 of file phatdbg.c.
References fputc(), PHAT_FATTR_ARCHIV, PHAT_FATTR_DIR, PHAT_FATTR_HIDDEN, PHAT_FATTR_RDONLY, PHAT_FATTR_SYSTEM, and PHAT_FATTR_VOLID.
Referenced by PhatDbgDirEntry().
void PhatDbgDirEntry (FILE * fp, CONST char * title, PHATDIRENT * dent)
Definition at line 85 of file phatdbg.c.
References PHATDIRENT::dent_adate, PHATDIRENT::dent_attr, PHATDIRENT::dent_cdate, PHATDIRENT::dent_clust, PHATDIRENT::dent_clusthi, PHATDIRENT::dent_ctime, PHATDIRENT::dent_ctsecs, PHATDIRENT::dent_fsize, PHATDIRENT::dent_mdate, PHATDIRENT::dent_mtime, PHATDIRENT::dent_name, PHATDIRENT::dent_rsvdnt, fprintf(), fputc(), fputs(), and PhatDbgAttrList().
Referenced by PhatDbgFileInfo(), PhatDirEntryUpdate(), and PhatDirRead().
void PhatDbgFileInfo (FILE * fp, CONST char * title, PHATFILE * nfp)
Definition at line 102 of file phatdbg.c.
References PHATFILE::f_clust, PHATFILE::f_clust_pos, PHATFILE::f_clust_prv, PHATFILE::f_de_dirty, PHATFILE::f_de_offs, PHATFILE::f_de_sect, PHATFILE::f_dirent, PHATFILE::f_pde_clust, PHATFILE::f_pde_clusthi, PHATFILE::f_pos, PHATFILE::f_sect_pos, fprintf(), and PhatDbgDirEntry().
Referenced by PhatDirEntryCreate(), PhatDirOpen(), PhatFileClose(), and PhatFileOpen().
void PhatDbgVbr (FILE * fp, CONST char * title, PHATVBR * vbr)
Definition at line 118 of file phatdbg.c.
References PHATVBR::bios_boot_bak, PHATVBR::bios_clustsz, PHATVBR::bios_fsinfo, PHATVBR::bios_fsver, PHATVBR::bios_heads, PHATVBR::bios_media, PHATVBR::bios_ntabs, PHATVBR::bios_root_clust, PHATVBR::bios_rootsz, PHATVBR::bios_rsvd_sects, PHATVBR::bios_sects_hidd, PHATVBR::bios_sects_p_trk, PHATVBR::bios_sectsz, PHATVBR::bios_tabsz, PHATVBR::bios_tabsz_big, PHATVBR::bios_volsz, PHATVBR::bios_volsz_big, PHATVBR::bios_xflags, PHATVBR::boot_drive, PHATVBR::boot_jump, PHATVBR::boot_oem, PHATVBR::boot_rsvd_nt, PHATVBR::boot_vol_fs, PHATVBR::boot_vol_id, PHATVBR::boot_vol_lbl, PHATVBR::boot_xsig, and fprintf().
Referenced by PhatVolMount().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/