Nut/OS API
ICC Context Switch
[System Support]
Thread context switching for ImageCraft ICCAVR.
Functions
void NutThreadSwitch (void)
Switch to another thread.
HANDLE NutThreadCreate (uint8_t *name, void(*fn)(void *), void *arg, size_t stackSize)
Create a new thread.
Detailed Description
Thread context switching for ImageCraft ICCAVR.
Function Documentation
void NutThreadSwitch (void)
Switch to another thread.
Stop the current thread, saving its context. Then start the one with the highest priority, which is ready to run.
Application programs typically do not call this function.
Note:
CPU interrupts must be disabled before calling this function.
Definition at line 196 of file context_icc.c.
References runningThread, runQueue, and TDS_RUNNING.
Referenced by NutThreadCreate(), NutThreadResume(), and NutThreadSetPriority().
HANDLE NutThreadCreate (uint8_t * name, void(*)(void *) fn, void * arg, size_t stackSize)
Create a new thread.
If the current thread's priority is lower or equal than the default priority (64), then the current thread is stopped and the new one is started.
Parameters:
name String containing the symbolic name of the new thread, up to 8 characters long.
fn The thread's entry point, typically created by the THREAD macro.
arg Argument pointer passed to the new thread.
stackSize Number of bytes of the stack space allocated for the new thread.
Returns:
Pointer to the NUTTHREADINFO structure or 0 to indicate an error.
Definition at line 272 of file context_icc.c.
References __os_trf, __os_trs, DEADBEEF, fprintf(), memcpy(), NutDumpThreadList(), NutEnterCritical, NutExitCritical, NutStackAlloc, NutThreadAddPriQueue(), nutThreadList, NutThreadSwitch(), runningThread, runQueue, and TDS_READY.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/