Nut/OS API
Initialization
[Emulator (UNIX)]
Starting Nut/OS.
Defines
#define PSEUDO_RAM_SIZE 999999
Nut/OS Initialization.
Functions
void NutIdle (void *arg)
Emulated idle thread.
void NutThreadInit (void)
NUTFILE * NUT_freopen (CONST char *name, CONST char *mode, NUTFILE *stream)
int main (int argc, char *argv[])
Variables
uint8_t PSEUDO_RAM [PSEUDO_RAM_SIZE]
NUTFILE * __iob []
Detailed Description
Starting Nut/OS.
Define Documentation
#define PSEUDO_RAM_SIZE 999999
Nut/OS Initialization.
Initializes the memory management and the thread system and starts an idle thread, which in turn initializes the timer management. Finally the application's main() function is called.
Definition at line 408 of file nutinit.c.
Referenced by main().
Function Documentation
void NutIdle (void * arg)
Emulated idle thread.
After initializing the timers, the idle thread switches to priority 254 and enters an endless loop.
Definition at line 376 of file nutinit.c.
References NUT_THREAD_MAINSTACK, NutAppMain(), NutThreadCreate(), NutThreadDestroy(), NutThreadSetPriority(), NutThreadYield(), and NutTimerInit().
void NutThreadInit (void)
Definition at line 78 of file thread.c.
References attr, main_cv, and thread_mutex.
NUTFILE* NUT_freopen (CONST char * name, CONST char * mode, NUTFILE * stream)
int main (int argc, char * argv[])
Definition at line 416 of file nutinit.c.
References emulation_options, emulation_options_parse(), NUT_THREAD_IDLESTACK, NutHeapAdd, NutIdle(), NutLoadConfig(), NutThreadCreate(), NutThreadInit(), PSEUDO_RAM_SIZE, emulation_options_t::saved_termios, and stdout.
Variable Documentation
uint8_t PSEUDO_RAM[PSEUDO_RAM_SIZE]
Definition at line 409 of file nutinit.c.
NUTFILE* __iob[]
Definition at line 63 of file fopen.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/