Nut/OS API
GBA Interrupts
[Interrupts]
Interrupt handler for the GameBoy Advance.
Functions
void IrqHandler (void)
void InitIrqHandler (void)
Variables
IRQ_HANDLER sig_VBLANK
IRQ_HANDLER sig_HBLANK
IRQ_HANDLER sig_VCOUNT
IRQ_HANDLER sig_TMR0
IRQ_HANDLER sig_TMR1
IRQ_HANDLER sig_TMR2
IRQ_HANDLER sig_TMR3
IRQ_HANDLER sig_SIO
IRQ_HANDLER sig_DMA0
IRQ_HANDLER sig_DMA1
IRQ_HANDLER sig_DMA2
IRQ_HANDLER sig_DMA3
IRQ_HANDLER sig_KEYPAD
IRQ_HANDLER sig_GAMEPAK
Detailed Description
Interrupt handler for the GameBoy Advance.
Function Documentation
void IrqHandler (void)
Definition at line 77 of file ihndlr_gba.c.
References CallHandler(), INT_DMA0, INT_DMA1, INT_DMA2, INT_DMA3, INT_GAMEPAK, INT_HBLANK, INT_KEYPAD, INT_SIO, INT_TMR0, INT_TMR1, INT_TMR2, INT_TMR3, INT_VBLANK, INT_VCOUNT, inw, and REG_IF.
Referenced by InitIrqHandler().
void InitIrqHandler (void)
Definition at line 129 of file ihndlr_gba.c.
References INT_VECTOR, IrqHandler(), and outdw.
Referenced by NutIdle().
Variable Documentation
IRQ_HANDLER sig_VBLANK
Definition at line 62 of file ihndlr_gba.c.
IRQ_HANDLER sig_HBLANK
Definition at line 63 of file ihndlr_gba.c.
IRQ_HANDLER sig_VCOUNT
Definition at line 64 of file ihndlr_gba.c.
IRQ_HANDLER sig_TMR0
Definition at line 65 of file ihndlr_gba.c.
IRQ_HANDLER sig_TMR1
Definition at line 66 of file ihndlr_gba.c.
IRQ_HANDLER sig_TMR2
Definition at line 67 of file ihndlr_gba.c.
IRQ_HANDLER sig_TMR3
Definition at line 68 of file ihndlr_gba.c.
Referenced by NutRegisterTimer().
IRQ_HANDLER sig_SIO
Definition at line 69 of file ihndlr_gba.c.
IRQ_HANDLER sig_DMA0
Definition at line 70 of file ihndlr_gba.c.
IRQ_HANDLER sig_DMA1
Definition at line 71 of file ihndlr_gba.c.
IRQ_HANDLER sig_DMA2
Definition at line 72 of file ihndlr_gba.c.
IRQ_HANDLER sig_DMA3
Definition at line 73 of file ihndlr_gba.c.
IRQ_HANDLER sig_KEYPAD
Definition at line 74 of file ihndlr_gba.c.
IRQ_HANDLER sig_GAMEPAK
Definition at line 75 of file ihndlr_gba.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/