Nut/OS API
Watchdog
[Special Hardware]
ATmega128 on-chip watchdog.
Defines
#define NUT_WDT_FREQ 1165000
Watchdog oscillator frequency.
Functions
uint32_t AvrWatchDogStart (uint32_t ms)
Start the AVR hardware watch dog timer.
void AvrWatchDogRestart (void)
Re-start the AVR hardware watch dog timer.
void AvrWatchDogDisable (void)
Disable the AVR hardware watch dog timer.
void AvrWatchDogEnable (void)
Enable the AVR hardware watch dog timer.
Detailed Description
ATmega128 on-chip watchdog.
Define Documentation
#define NUT_WDT_FREQ 1165000
Watchdog oscillator frequency.
Definition at line 59 of file wdt_avr.c.
Referenced by AvrWatchDogStart().
Function Documentation
uint32_t AvrWatchDogStart (uint32_t ms)
Start the AVR hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Parameters:
ms Desired watchdog timeout in milliseconds.
Returns:
The actual watchdog timeout.
Definition at line 76 of file wdt_avr.c.
References NUT_WDT_FREQ, wdt_enable, and wdt_reset.
Referenced by NutReset(), and NutWatchDogStart().
void AvrWatchDogRestart (void)
Re-start the AVR hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 99 of file wdt_avr.c.
References wdt_reset.
Referenced by NutWatchDogRestart().
void AvrWatchDogDisable (void)
Disable the AVR hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 110 of file wdt_avr.c.
References wdt_disable.
Referenced by NutWatchDogDisable().
void AvrWatchDogEnable (void)
Enable the AVR hardware watch dog timer.
For portability, applications should use the platform independent Watchdog Driver API.
Definition at line 124 of file wdt_avr.c.
References wdt_enable.
Referenced by NutWatchDogEnable().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/