Nut/OS API
PHAT32 Support
[PHAT File System]
PHAT32 specific routines.
Defines
#define PHAT32CMASK 0x0FFFFFFF
Functions
int Phat32GetClusterLink (NUTDEVICE *dev, uint32_t clust, uint32_t *link)
Get link value of a specified cluster.
int Phat32SetClusterLink (NUTDEVICE *dev, uint32_t clust, uint32_t link)
Set link value of a specified cluster.
int Phat32ReleaseChain (NUTDEVICE *dev, uint32_t first)
Release a cluster chain.
Detailed Description
PHAT32 specific routines.
Define Documentation
#define PHAT32CMASK 0x0FFFFFFF
Definition at line 58 of file phat32.h.
Referenced by AllocFirstCluster(), Phat32GetClusterLink(), Phat32ReleaseChain(), Phat32SetClusterLink(), PhatFilePosSet(), PhatFileRead(), and PhatFileWrite().
Function Documentation
int Phat32GetClusterLink (NUTDEVICE * dev, uint32_t clust, uint32_t * link)
Get link value of a specified cluster.
Parameters:
dev Specifies the file system device.
clust Get the link of this cluster.
link Pointer to a variable which will receive the link.
Returns:
0 on success or -1 on failure.
Definition at line 103 of file phat32.c.
References PHAT32CMASK, PHATEOC, PhatSectorLoad(), PHATSECTBUF::sect_data, and PHATVOL::vol_buf.
Referenced by Phat32ReleaseChain(), PhatFilePosSet(), PhatFileRead(), and PhatFileWrite().
int Phat32SetClusterLink (NUTDEVICE * dev, uint32_t clust, uint32_t link)
Set link value of a specified cluster.
Parameters:
dev Specifies the file system device.
clust This cluster will be linked.
link Link to this cluster.
Returns:
0 on success or -1 on failure.
Definition at line 138 of file phat32.c.
References PHAT32CMASK, PhatSectorLoad(), PHATSECTBUF::sect_data, PHATSECTBUF::sect_dirty, PHATVOL::vol_buf, and PHATVOL::vol_tab_sect.
Referenced by AllocFirstCluster(), and Phat32ReleaseChain().
int Phat32ReleaseChain (NUTDEVICE * dev, uint32_t first)
Release a cluster chain.
Parameters:
dev Specifies the file system device.
first First cluster of the chain to release.
Returns:
0 on success or -1 on failure.
Definition at line 170 of file phat32.c.
References PHAT32CMASK, Phat32GetClusterLink(), Phat32SetClusterLink(), PHATEOC, and PHATVOL::vol_numfree.
Referenced by PhatDirReleaseChain().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/