Nut/OS API
PHAT16 Support
[PHAT File System]
PHAT16 specific routines.
Defines
#define PHAT16CMASK 0xFFFF
Functions
int Phat16GetClusterLink (NUTDEVICE *dev, uint32_t clust, uint32_t *link)
Get link value of a specified cluster.
int Phat16SetClusterLink (NUTDEVICE *dev, uint32_t clust, uint32_t link)
Set link value of a specified cluster.
int Phat16ReleaseChain (NUTDEVICE *dev, uint32_t first)
Release a cluster chain.
Detailed Description
PHAT16 specific routines.
Define Documentation
#define PHAT16CMASK 0xFFFF
Definition at line 58 of file phat16.h.
Referenced by AllocFirstCluster(), Phat16GetClusterLink(), Phat16ReleaseChain(), PhatFilePosSet(), PhatFileRead(), and PhatFileWrite().
Function Documentation
int Phat16GetClusterLink (NUTDEVICE * dev, uint32_t clust, uint32_t * link)
Get link value of a specified cluster.
Parameters:
dev Specifies the file system device.
clust Get the link of this cluster.
link Pointer to a variable which will receive the link.
Returns:
0 on success or -1 on failure.
Definition at line 103 of file phat16.c.
References PHAT16CMASK, PHATEOC, PhatSectorLoad(), PHATSECTBUF::sect_data, and PHATVOL::vol_buf.
Referenced by Phat16ReleaseChain(), PhatFilePosSet(), PhatFileRead(), and PhatFileWrite().
int Phat16SetClusterLink (NUTDEVICE * dev, uint32_t clust, uint32_t link)
Set link value of a specified cluster.
Parameters:
dev Specifies the file system device.
clust This cluster will be linked.
link Link to this cluster.
Returns:
0 on success or -1 on failure.
Definition at line 137 of file phat16.c.
References PhatSectorLoad(), PHATSECTBUF::sect_data, PHATSECTBUF::sect_dirty, PHATVOL::vol_buf, and PHATVOL::vol_tab_sect.
Referenced by AllocFirstCluster(), and Phat16ReleaseChain().
int Phat16ReleaseChain (NUTDEVICE * dev, uint32_t first)
Release a cluster chain.
Parameters:
dev Specifies the file system device.
first First cluster of the chain to release.
Returns:
0 on success or -1 on failure.
Definition at line 165 of file phat16.c.
References PHAT16CMASK, Phat16GetClusterLink(), Phat16SetClusterLink(), PHATEOC, and PHATVOL::vol_numfree.
Referenced by PhatDirReleaseChain().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/