Nut/OS API
httpd_p.h File Reference
Functions
char * CreateFilePath (CONST char *url, CONST char *addon)
Create a file path from an URL.
void DestroyRequestInfo (REQUEST *req)
Release request info structure.
Variables
char * http_root
char * default_files []
Function Documentation
char* CreateFilePath (CONST char * url, CONST char * addon)
Create a file path from an URL.
Definition at line 55 of file httpd_p.c.
References HTTP_DEFAULT_ROOT, http_root, malloc, strcat(), strcpy(), and strlen().
void DestroyRequestInfo (REQUEST * req)
Release request info structure.
Definition at line 77 of file httpd_p.c.
References free.
Referenced by NutHttpProcessRequest().
Variable Documentation
char* http_root
Definition at line 33 of file httpd_p.c.
char* default_files[]
Definition at line 35 of file httpd_p.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/