Nut/OS API
kbhit.c File Reference
Functions
int kbhit (void)
Function Documentation
int kbhit (void)
Definition at line 46 of file kbhit.c.
References _filelength(), _fileno(), and stdin.
Referenced by main().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/