Nut/OS API
mib2sys.c File Reference
Defines
#define BOARD_NAME "Custom"
#define MAG_SYS_DESCR 1
#define MAG_SYS_OID 2
#define MAG_SYS_UPTIME 3
#define MAG_SYS_CONTACT 4
#define MAG_SYS_NAME 5
#define MAG_SYS_LOCATION 6
#define MAG_SYS_SERVICES 7
Functions
int MibRegisterSysVars (void)
Register MIB II system variables.
Define Documentation
#define BOARD_NAME "Custom"
Definition at line 76 of file mib2sys.c.
Referenced by MibRegisterSysVars().
#define MAG_SYS_DESCR 1
Definition at line 79 of file mib2sys.c.
#define MAG_SYS_OID 2
Definition at line 80 of file mib2sys.c.
#define MAG_SYS_UPTIME 3
Definition at line 81 of file mib2sys.c.
#define MAG_SYS_CONTACT 4
Definition at line 82 of file mib2sys.c.
#define MAG_SYS_NAME 5
Definition at line 83 of file mib2sys.c.
#define MAG_SYS_LOCATION 6
Definition at line 84 of file mib2sys.c.
#define MAG_SYS_SERVICES 7
Definition at line 85 of file mib2sys.c.
Function Documentation
int MibRegisterSysVars (void)
Register MIB II system variables.
Note:
Preliminary code with hard coded values.
Examples:
snmpd/snmpd.c.
Definition at line 135 of file mib2sys.c.
References BOARD_NAME, confos, getenv(), NutVersionString(), SnmpMibRegister(), strcat(), strcpy(), and time().
Referenced by main().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/