Nut/OS API
mweeprom.h File Reference
Functions
unsigned char eeprom_read_byte (const unsigned char *addr)
unsigned short eeprom_read_word (const unsigned short *addr)
void eeprom_read_block (void *buf, const void *addr, size_t n)
void eeprom_write_byte (unsigned char *addr, unsigned char val)
void eeprom_write_word (unsigned short *addr, unsigned short val)
void eeprom_write_block (const void *buf, void *addr, size_t n)
void eeprom_fill_all (const unsigned char c)
void eeprom_erase (unsigned char *addr)
void eeprom_erase_all (void)
Function Documentation
unsigned char eeprom_read_byte (const unsigned char * addr)
read one byte from EEPROM address addr
Definition at line 100 of file eeprom.c.
References fread(), and unix_eeprom_acces().
unsigned short eeprom_read_word (const unsigned short * addr)
read one 16-bit word (little endian) from EEPROM address addr
Definition at line 113 of file eeprom.c.
References fread(), and unix_eeprom_acces().
void eeprom_read_block (void * buf, const void * addr, size_t n)
read a block of n bytes from EEPROM address addr to buf
Definition at line 86 of file eeprom.c.
References fread(), and unix_eeprom_acces().
void eeprom_write_byte (unsigned char * addr, unsigned char val)
write a byte val to EEPROM address addr
Definition at line 76 of file eeprom.c.
References fflush(), fwrite(), and unix_eeprom_acces().
void eeprom_write_word (unsigned short * addr, unsigned short val)
void eeprom_write_block (const void * buf, void * addr, size_t n)
void eeprom_fill_all (const unsigned char c)
void eeprom_erase (unsigned char * addr)
void eeprom_erase_all (void)
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/