Nut/OS API
options.c File Reference
Parsing of command line options. NOTE: Unix emulation only!
Functions
void emulation_options_parse (int argc, char *argv[])
Variables
emulation_options_t emulation_options
Detailed Description
Parsing of command line options. NOTE: Unix emulation only!
Definition in file options.c.
Function Documentation
void emulation_options_parse (int argc, char * argv[])
Definition at line 79 of file options.c.
References atoi(), uart_options_t::bautrate, uart_options_t::device, uart_options_t::flowcontrol, printf, strcmp(), strdup(), strncmp(), emulation_options_t::uart_options, uart_options_t::usbnum, and emulation_options_t::verbose.
Referenced by main().
Variable Documentation
emulation_options_t emulation_options
Definition at line 60 of file options.c.
Referenced by main().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/