Nut/OS API
osdebug.c File Reference
Functions
void NutDumpThreadQueue (FILE *stream, NUTTHREADINFO *tdp)
Dump system queue contents.
void NutDumpThreadList (FILE *stream)
Dump system thread list.
void NutDumpTimerList (FILE *stream)
Dump system timer list.
void NutTraceOs (FILE *stream, uint8_t flags)
Control OS tracing.
void NutDumpHeap (FILE *stream)
Dump free node list of heap memory.
void NutTraceHeap (FILE *stream, uint8_t flags)
Control dynamic memory tracing.
Variables
FILE * __os_trs
uint_fast8_t __os_trf
FILE * __heap_trs
uint_fast8_t __heap_trf
Function Documentation
void NutDumpThreadQueue (FILE * stream, NUTTHREADINFO * tdp)
Dump system queue contents.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
tdp Pointer to the queue.
Warning:
Interrupts are disabled inside this funtion.
Definition at line 116 of file osdebug.c.
References DEADBEEF, fprintf_P, fputs(), prog_char, and SIGNALED.
void NutDumpThreadList (FILE * stream)
Dump system thread list.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
Warning:
Interrupts are disabled inside this funtion.
Definition at line 155 of file osdebug.c.
References DEADBEEF, fprintf_P, fputc(), fputs(), fputs_P, nutThreadList, prog_char, and SIGNALED.
Referenced by NutThreadCreate().
void NutDumpTimerList (FILE * stream)
Dump system timer list.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
Warning:
Interrupts are disabled inside this funtion.
Definition at line 205 of file osdebug.c.
References fprintf_P, fputs_P, NutEventTimeout(), NutThreadWake(), nutTimerList, and prog_char.
void NutTraceOs (FILE * stream, uint8_t flags)
Control OS tracing.
Parameters:
stream Pointer to a previously opened stream associated to a debug device or null to disable trace output.
flags Flags to enable specific traces.
Definition at line 246 of file osdebug.c.
References __os_trf, and __os_trs.
Referenced by main().
void NutDumpHeap (FILE * stream)
Dump free node list of heap memory.
Parameters:
stream Pointer to a previously opened stream associated to a debug device.
Definition at line 262 of file osdebug.c.
References fprintf_P, fputc(), heapFreeList, NutHeapAvailable, and prog_char.
void NutTraceHeap (FILE * stream, uint8_t flags)
Control dynamic memory tracing.
Parameters:
stream Pointer to a previously opened stream or null to disable trace output.
flags Flags to enable specific traces.
Definition at line 299 of file osdebug.c.
References __heap_trf, and __heap_trs.
Referenced by main().
Variable Documentation
FILE* __os_trs
Definition at line 91 of file osdebug.c.
Referenced by NutThreadCreate(), and NutTraceOs().
uint_fast8_t __os_trf
Definition at line 92 of file osdebug.c.
Referenced by NutThreadCreate(), and NutTraceOs().
FILE* __heap_trs
Definition at line 94 of file osdebug.c.
Referenced by NutTraceHeap().
uint_fast8_t __heap_trf
Definition at line 95 of file osdebug.c.
Referenced by NutTraceHeap().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/