Nut/OS API
playmp3.c File Reference
Functions
int main (void)
Function Documentation
int main (void)
Definition at line 105 of file playmp3.c.
References _fileno(), _ioctl(), DEV_DEBUG, DEV_DEBUG_NAME, devUrom, freopen(), NutRegisterDevice(), NutSegBufInit(), NutSleep(), NutVersionString(), printf, puts, stdout, UART_SETSPEED, VsPlayerInit(), VsPlayerReset(), and VsSetVolume().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/