Nut/OS API
pppc.c File Reference
Defines
#define PPPUSER "me"
#define PPPPASS "secret"
#define PPPCHAT "TIMEOUT 2 '' CLIENT\\c CLIENTSERVER"
#define PPPCOM "uart0"
#define PPPSPEED 115200
#define PPPRXTO 1000
#define RXBUFFSIZE 256
#define CC_STRING "AVRGCC"
#define DBGDEV devDebug1
#define DBGCOM "uart1"
#define DBGSPEED 115200
Functions
void ProcessRequests (FILE *stream)
int main (void)
Variables
prog_char vbanner_P [] = "\n\nPPP Client Sample - Nut/OS %s - " CC_STRING "\n"
prog_char banner_P [] = "200 Welcome to tcps. Type help to get help.\r\n"
prog_char help_P []
prog_char thread_intro_P [] = "220 List of threads with name,state,prio,stack,mem,timeout follows\r\n"
prog_char timer_intro_P [] = "221 List of timers with ticks left and interval follows\r\n"
prog_char mem_fmt_P [] = "210 %lu bytes RAM free\r\n"
Define Documentation
#define PPPUSER "me"
Examples:
pppc/pppc.c.
Definition at line 94 of file pppc.c.
Referenced by main().
#define PPPPASS "secret"
Examples:
pppc/pppc.c.
Definition at line 95 of file pppc.c.
Referenced by main().
#define PPPCHAT "TIMEOUT 2 '' CLIENT\\c CLIENTSERVER"
Examples:
pppc/pppc.c.
Definition at line 102 of file pppc.c.
Referenced by main().
#define PPPCOM "uart0"
Examples:
pppc/pppc.c.
Definition at line 119 of file pppc.c.
Referenced by main().
#define PPPSPEED 115200
Examples:
pppc/pppc.c.
Definition at line 120 of file pppc.c.
Referenced by main().
#define PPPRXTO 1000
Examples:
pppc/pppc.c.
Definition at line 121 of file pppc.c.
Referenced by main().
#define RXBUFFSIZE 256
Examples:
pppc/pppc.c.
Definition at line 127 of file pppc.c.
Referenced by ProcessRequests().
#define CC_STRING "AVRGCC"
Definition at line 162 of file pppc.c.
#define DBGDEV devDebug1
Examples:
pppc/pppc.c.
Definition at line 171 of file pppc.c.
Referenced by main().
#define DBGCOM "uart1"
Definition at line 173 of file pppc.c.
#define DBGSPEED 115200
Examples:
pppc/pppc.c.
Definition at line 174 of file pppc.c.
Referenced by main().
Function Documentation
void ProcessRequests (FILE * stream)
Definition at line 191 of file pppc.c.
References banner_P, DEADBEEF, fflush(), fgets(), fprintf(), fprintf_P, fputs(), fputs_P, help_P, malloc, mem_fmt_P, NutHeapAvailable, nutThreadList, nutTimerList, RXBUFFSIZE, strchr(), strlen(), strncmp(), TDS_READY, TDS_RUNNING, TDS_SLEEP, TDS_TERM, thread_intro_P, and timer_intro_P.
int main (void)
Definition at line 312 of file pppc.c.
References _fdopen(), _fileno(), _ioctl(), _O_BINARY, _O_RDWR, _open(), DBGDEV, DBGSPEED, devPpp, fclose(), freopen(), inet_ntoa(), NutChat(), NutDnsConfig2(), NutHeapAvailable, NutIpRouteAdd(), NutNetIfConfig(), NutRegisterDevice(), NutSleep(), NutTcpAccept(), NutTcpCloseSocket(), NutTcpCreateSocket(), NutTracePPP(), NutVersionString(), PPPCHAT, PPPCOM, PPPPASS, PPPRXTO, PPPSPEED, PPPUSER, printf, printf_P(), ProcessRequests(), puts, stdout, UART_SETREADTIMEOUT, UART_SETSPEED, and vbanner_P.
Variable Documentation
prog_char vbanner_P[] = "\n\nPPP Client Sample - Nut/OS %s - " CC_STRING "\n"
Examples:
pppc/pppc.c, and tcps/tcps.c.
Definition at line 177 of file pppc.c.
Referenced by main().
prog_char banner_P[] = "200 Welcome to tcps. Type help to get help.\r\n"
Examples:
pppc/pppc.c, and tcps/tcps.c.
Definition at line 178 of file pppc.c.
Referenced by ProcessRequests().
prog_char help_P[]
Initial value:
 "400 List of commands follows\r\n"
    "m[emory]\tQueries number of RAM bytes free.\r\n"
    "t[hreads]\tLists all created threads.\r\n"
    "ti[mers]\tLists all running timers.\r\n" "q[uit]\t\tTerminates connection.\r\n" ".\r\n"
Examples:
pppc/pppc.c, and tcps/tcps.c.
Definition at line 179 of file pppc.c.
Referenced by ProcessRequests().
prog_char thread_intro_P[] = "220 List of threads with name,state,prio,stack,mem,timeout follows\r\n"
Examples:
pppc/pppc.c, and tcps/tcps.c.
Definition at line 183 of file pppc.c.
Referenced by ProcessRequests().
prog_char timer_intro_P[] = "221 List of timers with ticks left and interval follows\r\n"
Examples:
pppc/pppc.c, and tcps/tcps.c.
Definition at line 184 of file pppc.c.
Referenced by ProcessRequests().
prog_char mem_fmt_P[] = "210 %lu bytes RAM free\r\n"
Examples:
pppc/pppc.c, and tcps/tcps.c.
Definition at line 185 of file pppc.c.
Referenced by ProcessRequests().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/