Nut/OS API
scanner.c File Reference
Functions
int ScanStreamHeader (TCPSOCKET *sock, RADIOSTATION *rsp)
Process header from server.
void Scanner (void *arg)
int ScannerInit (void)
Initialize the MP3 player.
Function Documentation
int ScanStreamHeader (TCPSOCKET * sock, RADIOSTATION * rsp)
Process header from server.
Examples:
nutpiper/nutpiper.c.
Definition at line 115 of file scanner.c.
References atoi(), atol(), free, inet_ntoa(), malloc, printf, puts, RADIOSTATION::rs_bitrate, RADIOSTATION::rs_genre, RADIOSTATION::rs_ip, RADIOSTATION::rs_metaint, RADIOSTATION::rs_name, RADIOSTATION::rs_url, sprintf, strcat(), strcpy(), strlen(), and strncmp().
Referenced by Scanner().
void Scanner (void * arg)
Definition at line 263 of file scanner.c.
References free, inet_ntoa(), MAXNUM_STATIONS, NutHeapAvailable, NutSleep(), NutTcpCloseSocket(), NutTcpConnect(), NutTcpCreateSocket(), NutTcpError(), NutTcpSetSockOpt(), NutThreadSetPriority(), printf, radio, RADIOCONTROL::rc_cstation, RADIOCONTROL::rc_off, RADIOCONTROL::rc_rstation, RADIOSTATION::rs_ip, RADIOSTATION::rs_metaint, RADIOSTATION::rs_name, RADIOSTATION::rs_port, RADIOSTATION::rs_scandead, RADIOSTATION::rs_scantitle, ScanStreamHeader(), SO_RCVTIMEO, and station.
Referenced by ScannerInit().
int ScannerInit (void)
Initialize the MP3 player.
Initializes the decoder and the decoder buffer and starts the player background thread.
Definition at line 329 of file scanner.c.
References NutThreadCreate(), and Scanner().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/