Nut/OS API
scanner.h File Reference
Functions
int ScannerInit (void)
Initialize the MP3 player.
int ScanStreamHeader (TCPSOCKET *sock, RADIOSTATION *rsp)
Process header from server.
Function Documentation
int ScannerInit (void)
Initialize the MP3 player.
$Log$ Revision 1.1 2003/07/21 17:50:48 haraldkipp First check in
Initializes the decoder and the decoder buffer and starts the player background thread.
Definition at line 329 of file scanner.c.
References NutThreadCreate(), and Scanner().
int ScanStreamHeader (TCPSOCKET * sock, RADIOSTATION * rsp)
Process header from server.
Definition at line 115 of file scanner.c.
References atoi(), atol(), free, inet_ntoa(), malloc, printf, puts, RADIOSTATION::rs_bitrate, RADIOSTATION::rs_genre, RADIOSTATION::rs_ip, RADIOSTATION::rs_metaint, RADIOSTATION::rs_name, RADIOSTATION::rs_url, sprintf, strcat(), strcpy(), strlen(), and strncmp().
Referenced by Scanner().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/