Nut/OS API
snmp_mib.h File Reference
SNMP MIB support functions.
Data Structures
struct SNMPVAR
Typedefs
typedef int(WMETHOD)(int, uint8_t *, uint8_t, size_t, OID *, size_t)
Functions
int SnmpMibRegister (OID[], size_t, SNMPVAR *, int)
Register MIB variables.
uint8_t * SnmpMibFind (OID *, size_t *, uint8_t *, size_t *, uint16_t *, int, WMETHOD **, int *)
Find MIB variable.
Detailed Description
SNMP MIB support functions.
 * $Id: snmp_mib.h 2235 2008-08-11 07:00:36Z haraldkipp $
 *
Definition in file snmp_mib.h.
Typedef Documentation
typedef int(WMETHOD)(int, uint8_t *, uint8_t, size_t, OID *, size_t)
Definition at line 48 of file snmp_mib.h.
Function Documentation
int SnmpMibRegister (OID [], size_t , SNMPVAR * , int)
Register MIB variables.
Definition at line 70 of file snmp_mib.c.
References malloc, memcpy(), and SnmpOidCmp().
Referenced by MibRegisterIfVars(), and MibRegisterSysVars().
uint8_t* SnmpMibFind (OID * name, size_t * namelen, uint8_t * type, size_t * len, uint16_t * acl, int exact, WMETHOD ** wmethod, int * no_obj)
Find MIB variable.
Parameters:
name
namelen
type
len
acl
exact
wmethod
no_obj
Definition at line 109 of file snmp_mib.c.
References access(), free, malloc, memcpy(), SnmpOidTreeCmp(), SNMPVAR::var_acl, SNMPVAR::var_get, SNMPVAR::var_name, SNMPVAR::var_namelen, and SNMPVAR::var_type.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/