Nut/OS API
snmp_config.h File Reference
SNMP configuration.
Data Structures
struct VIEW_LIST
struct COMMUNITY_LIST
Defines
#define SNMP_VIEW_INCLUDED 1
#define SNMP_VIEW_EXCLUDED 2
Functions
int SnmpViewCreate (CONST char *, CONST OID *, size_t, int)
int SnmpViewFind (char *)
int SnmpCommunityCreate (CONST char *, int, int)
Create a community entry.
int SnmpCommunityFind (CONST char *, int *, int *)
Find community entry by name.
Detailed Description
SNMP configuration.
 * $Id: snmp_config.h 2034 2008-02-15 17:13:17Z haraldkipp $
 *
Definition in file snmp_config.h.
Define Documentation
#define SNMP_VIEW_INCLUDED 1
Examples:
snmpd/snmpd.c.
Definition at line 51 of file snmp_config.h.
Referenced by main().
#define SNMP_VIEW_EXCLUDED 2
Definition at line 52 of file snmp_config.h.
Function Documentation
int SnmpViewCreate (CONST char * name, CONST OID * subtree, size_t subtreelen, int type)
Parameters:
name Symbolic name of this view.
type Either SNMP_VIEW_INCLUDED or SNMP_VIEW_EXCLUDED.
Returns:
View index on success. Otherwise -1 is returned.
Examples:
snmpd/snmpd.c.
Definition at line 51 of file snmp_config.c.
References malloc, memset(), VIEW_LIST::next, strcmp(), strcpy(), strlen(), VIEW_LIST::view_index, VIEW_LIST::view_name, VIEW_LIST::view_subtree, VIEW_LIST::view_subtree_len, and VIEW_LIST::view_type.
Referenced by main().
int SnmpViewFind (char *)
Definition at line 93 of file snmp_config.c.
References VIEW_LIST::next, strcmp(), VIEW_LIST::view_index, and VIEW_LIST::view_name.
int SnmpCommunityCreate (CONST char * name, int readView, int writeView)
Create a community entry.
Parameters:
name Community name.
readView View index for read access, obtained from a previous call to SnmpViewCreate().
writeView View index for write access, obtained from a previous call to SnmpViewCreate().
Returns:
0 on success, -1 otherwise.
Examples:
snmpd/snmpd.c.
Definition at line 148 of file snmp_config.c.
References COMMUNITY_LIST::comm_name, COMMUNITY_LIST::comm_read_view, COMMUNITY_LIST::comm_write_view, malloc, memset(), COMMUNITY_LIST::next, strcmp(), strcpy(), and strlen().
Referenced by main().
int SnmpCommunityFind (CONST char * name, int * readView, int * writeView)
Find community entry by name.
Parameters:
name Community name.
readView Pointer to a variable that receives the view index for read access.
writeView Pointer to a variable that receives the view index for write access.
Returns:
0 on success, -1 otherwise.
Definition at line 119 of file snmp_config.c.
References COMMUNITY_LIST::comm_name, COMMUNITY_LIST::comm_read_view, COMMUNITY_LIST::comm_write_view, COMMUNITY_LIST::next, and strcmp().
Referenced by SnmpAgentProcessRequest().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/