Nut/OS API
snmp_mib.c File Reference
Functions
int SnmpMibRegister (OID basename[], size_t baselen, SNMPVAR *vars, int num)
Register MIB variables.
uint8_t * SnmpMibFind (OID *name, size_t *namelen, uint8_t *type, size_t *len, uint16_t *acl, int exact, WMETHOD **wmethod, int *no_obj)
Find MIB variable.
Function Documentation
int SnmpMibRegister (OID basename[], size_t baselen, SNMPVAR * vars, int num)
Register MIB variables.
Definition at line 70 of file snmp_mib.c.
References malloc, memcpy(), and SnmpOidCmp().
Referenced by MibRegisterIfVars(), and MibRegisterSysVars().
uint8_t* SnmpMibFind (OID * name, size_t * namelen, uint8_t * type, size_t * len, uint16_t * acl, int exact, WMETHOD ** wmethod, int * no_obj)
Find MIB variable.
Parameters:
name
namelen
type
len
acl
exact
wmethod
no_obj
Definition at line 109 of file snmp_mib.c.
References access(), free, malloc, memcpy(), SnmpOidTreeCmp(), SNMPVAR::var_acl, SNMPVAR::var_get, SNMPVAR::var_name, SNMPVAR::var_namelen, and SNMPVAR::var_type.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/