Nut/OS API
snmp_auth.c File Reference
Functions
CONST uint8_t * SnmpAuthParse (CONST uint8_t *data, size_t *length, uint8_t *sidp, size_t *slen, long *version)
Parse header of community string based message.
uint8_t * SnmpAuthBuild (SNMP_SESSION *session, uint8_t *data, size_t *length, size_t messagelen)
Build header of community string based message.
Function Documentation
CONST uint8_t* SnmpAuthParse (CONST uint8_t * data, size_t * length, uint8_t * sidp, size_t * slen, long * version)
Parse header of community string based message.
Retrieves version and community.
Parameters:
data Points to the message.
length Bytes left in message.
sidp Pointer to a buffer that receives the community string.
slen Length of the community string.
version Message version
Definition at line 49 of file snmp_auth.c.
References ASN_CONSTRUCTOR, ASN_SEQUENCE, AsnIntegerParse(), AsnOctetStringParse(), AsnSequenceParse(), and SNMP_VERSION_1.
Referenced by SnmpAgentProcessRequest().
uint8_t* SnmpAuthBuild (SNMP_SESSION * session, uint8_t * data, size_t * length, size_t messagelen)
Build header of community string based message.
Definition at line 76 of file snmp_auth.c.
References ASN_CONSTRUCTOR, ASN_INTEGER, ASN_OCTET_STR, ASN_PRIMITIVE, ASN_SEQUENCE, ASN_UNIVERSAL, AsnIntegerBuild(), AsnOctetStringBuild(), AsnSequenceBuild(), SNMP_SESSION::sess_id, SNMP_SESSION::sess_id_len, and SNMP_SESSION::sess_version.
Referenced by SnmpAgentProcessRequest().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/