Nut/OS API
snmp_agent.h File Reference
SNMP agent functions.
Data Structures
struct SNMP_SESSION
Functions
int SnmpAgent (UDPSOCKET *)
Run SNMP agent.
Detailed Description
SNMP agent functions.
 * $Id: snmp_agent.h 2235 2008-08-11 07:00:36Z haraldkipp $
 *
Definition in file snmp_agent.h.
Function Documentation
int SnmpAgent (UDPSOCKET * sock)
Run SNMP agent.
Normally runs in an endless loop, which is only left in case of an error.
Parameters:
sock UDP socket to use.
Returns:
Always -1.
Examples:
snmpd/snmpd.c.
Definition at line 463 of file snmp_agent.c.
References free, malloc, memset(), NutUdpReceiveFrom(), NutUdpSendTo(), SNMP_MAX_LEN, SNMP_STAT_OUTPKTS, SnmpAgentProcessRequest(), and SnmpStatsInc().
Referenced by main().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/