Nut/OS API
snmp_api.c File Reference
Functions
int SnmpOidLenCmp (CONST OID *name1, CONST OID *name2, size_t len)
Compare object identifiers up to a specified length.
int SnmpOidCmp (CONST OID *name1, size_t len1, CONST OID *name2, size_t len2)
Compare object identifiers.
int SnmpOidTreeCmp (CONST OID *objid, size_t objlen, CONST OID *treeid, size_t treelen)
Compare object identifier with tree element.
int SnmpOidCmpIdx (CONST OID *name1, size_t len1, CONST OID *name2, size_t len2, OID index)
Compare object identifiers with index added.
int SnmpOidEquals (CONST OID *name1, size_t len1, CONST OID *name2, size_t len2)
void SnmpStatsInc (int which)
uint32_t SnmpStatsGet (int which)
Function Documentation
int SnmpOidLenCmp (CONST OID * name1, CONST OID * name2, size_t len)
Compare object identifiers up to a specified length.
Parameters:
name1 First object identifier.
name2 Second object identifier.
len Number of sub identifiers to compare.
Definition at line 51 of file snmp_api.c.
Referenced by SnmpOidCmp(), SnmpOidCmpIdx(), and SnmpOidTreeCmp().
int SnmpOidCmp (CONST OID * name1, size_t len1, CONST OID * name2, size_t len2)
Compare object identifiers.
Parameters:
name1 First object identifier.
len1 Length of first object identifier.
name2 Second object identifier.
len2 Length of second object identifier.
Returns:
0 if both are equal, 1 if first element is larger or -1 if first element is lower than the second one.
Definition at line 79 of file snmp_api.c.
References SnmpOidLenCmp().
Referenced by SnmpMibRegister().
int SnmpOidTreeCmp (CONST OID * objid, size_t objlen, CONST OID * treeid, size_t treelen)
Compare object identifier with tree element.
Parameters:
name1 Object identifier.
len1 Length of object identifier.
name2 Tree identifier.
len2 Length of tree identifier.
Returns:
0 if the object identifier is part of the subtree, -1 if it is located before the tree element or 1 if it is located after the tree element.
Definition at line 106 of file snmp_api.c.
References SnmpOidLenCmp().
Referenced by SnmpMibFind().
int SnmpOidCmpIdx (CONST OID * name1, size_t len1, CONST OID * name2, size_t len2, OID index)
Compare object identifiers with index added.
Parameters:
name1 First object identifier.
len1 Length of first object identifier.
name2 Second object identifier.
len2 Length of second object identifier.
index Index sub identifier.
Returns:
0 if both are equal, 1 if first element is larger or -1 if first element is lower than the second one.
Definition at line 129 of file snmp_api.c.
References SnmpOidLenCmp().
int SnmpOidEquals (CONST OID * name1, size_t len1, CONST OID * name2, size_t len2)
Definition at line 167 of file snmp_api.c.
References memcmp().
void SnmpStatsInc (int which)
Definition at line 176 of file snmp_api.c.
References SNMP_STAT_MAX.
Referenced by SnmpAgent(), SnmpAgentProcessRequest(), and SnmpVarBuild().
uint32_t SnmpStatsGet (int which)
Definition at line 183 of file snmp_api.c.
References SNMP_STAT_MAX.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/