Nut/OS API
ptrace.h File Reference
Functions
void ptrace_dump_regs (struct pt_regs *p)
void ptrace_stackdump_from (const int *frame_ptr)
void ptrace_stackdump_regs (struct pt_regs *p)
void ptrace_stackdump_here (void)
Function Documentation
void ptrace_dump_regs (struct pt_regs * p)
Definition at line 56 of file reg-dump.c.
References ARM_ABT_MODE, ARM_CPSR_C_BIT, ARM_CPSR_F_BIT, ARM_CPSR_I_BIT, ARM_CPSR_N_BIT, ARM_CPSR_T_BIT, ARM_CPSR_V_BIT, ARM_CPSR_Z_BIT, ARM_FIQ_MODE, ARM_IRQ_MODE, ARM_MODE_MASK, ARM_SVC_MODE, ARM_SYS_MODE, ARM_UND_MODE, ARM_USR_MODE, printf, PTRACE_CPSR_idx, PTRACE_FRAMETYPE_da, PTRACE_FRAMETYPE_idx, PTRACE_FRAMETYPE_pfa, PTRACE_R0_idx, PTRACE_R7_idx, PTRACE_R8_idx, putchar(), and pt_regs::uregs.
Referenced by ptrace_stackdump_regs().
void ptrace_stackdump_from (const int * frame_ptr)
Definition at line 64 of file stackdump.c.
References printf, and puts.
Referenced by ptrace_stackdump_here(), and ptrace_stackdump_regs().
void ptrace_stackdump_regs (struct pt_regs * p)
Definition at line 89 of file stackdump.c.
References ptrace_dump_regs(), PTRACE_R13_idx, ptrace_stackdump_from(), and pt_regs::uregs.
Referenced by ARM_COMMON_Handler_crash().
void ptrace_stackdump_here (void)
Definition at line 96 of file stackdump.c.
References ptrace_stackdump_from().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/