Nut/OS API
tcps.c File Reference
Defines
#define CC_STRING "AVRGCC"
Functions
void ProcessRequests (FILE *stream)
int main (void)
Variables
prog_char vbanner_P [] = "\n\nTCP Server Sample - Nut/OS %s - " CC_STRING "\n"
prog_char banner_P [] = "200 Welcome to tcps. Type help to get help.\r\n"
prog_char help_P []
prog_char thread_intro_P [] = "220 List of threads with name,state,prio,stack,mem,timeout follows\r\n"
prog_char timer_intro_P [] = "221 List of timers with ticks left and interval follows\r\n"
prog_char mem_fmt_P [] = "210 %u bytes RAM free\r\n"
Define Documentation
#define CC_STRING "AVRGCC"
Definition at line 120 of file tcps.c.
Function Documentation
void ProcessRequests (FILE * stream)
Definition at line 138 of file tcps.c.
References banner_P, DEADBEEF, fflush(), fgets(), fprintf(), fprintf_P, fputs(), fputs_P, help_P, mem_fmt_P, NutHeapAvailable, nutThreadList, nutTimerList, strchr(), strlen(), strncmp(), TDS_READY, TDS_RUNNING, TDS_SLEEP, TDS_TERM, thread_intro_P, and timer_intro_P.
int main (void)
Definition at line 255 of file tcps.c.
References _fdopen(), _fileno(), _ioctl(), confnet, DEV_DEBUG, DEV_DEBUG_NAME, DEV_ETHER, DEV_ETHER_NAME, fclose(), freopen(), inet_addr(), inet_ntoa(), memcpy(), NutDhcpIfConfig(), NutNetIfConfig(), NutNetLoadConfig(), NutNetSaveConfig(), NutRegisterDevice(), NutTcpAccept(), NutTcpCloseSocket(), NutTcpCreateSocket(), NutTraceHeap(), NutTraceOs(), NutTracePPP(), NutTraceTcp(), NutVersionString(), printf, printf_P(), ProcessRequests(), puts, stdout, UART_SETSPEED, and vbanner_P.
Variable Documentation
prog_char vbanner_P[] = "\n\nTCP Server Sample - Nut/OS %s - " CC_STRING "\n"
Definition at line 125 of file tcps.c.
prog_char banner_P[] = "200 Welcome to tcps. Type help to get help.\r\n"
Definition at line 126 of file tcps.c.
prog_char help_P[]
Initial value:
 "400 List of commands follows\r\n"
    "m[emory]\tQueries number of RAM bytes free.\r\n"
    "t[hreads]\tLists all created threads.\r\n"
    "ti[mers]\tLists all running timers.\r\n" "q[uit]\t\tTerminates connection.\r\n" ".\r\n"
Definition at line 127 of file tcps.c.
prog_char thread_intro_P[] = "220 List of threads with name,state,prio,stack,mem,timeout follows\r\n"
Definition at line 131 of file tcps.c.
prog_char timer_intro_P[] = "221 List of timers with ticks left and interval follows\r\n"
Definition at line 132 of file tcps.c.
prog_char mem_fmt_P[] = "210 %u bytes RAM free\r\n"
Definition at line 133 of file tcps.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/