Nut/OS API
unix.h File Reference
Data Structures
struct uart_options_t
struct emulation_options_t
Defines
#define CONST const
#define INLINE inline
#define PSTR(p) (p)
#define PRG_RDB(p) (*((const char *)(p)))
#define prog_char const char
#define PGM_P prog_char *
#define main(...) NutAppMain(__VA_ARGS__)
#define strlen_P(x) strlen(x)
#define strcpy_P(x, y) strcpy(x,y)
#define strcmp_P(x, y) strcmp(x, y)
#define memcpy_P(x, y, z) memcpy(x, y, z)
#define RAMSTART ((void *)0x00100)
#define malloc(...) NUT_malloc(__VA_ARGS__)
#define realloc(...) NUT_realloc(__VA_ARGS__)
#define free(...) NUT_free(__VA_ARGS__)
Enumerations
enum {
IRQ_TIMER0, IRQ_UART0_RX, IRQ_UART1_RX, IRQ_UART2_RX,
IRQ_MAX
}
Functions
void emulation_options_parse (int argc, char *argv[])
Variables
emulation_options_t emulation_options
Backwards compatibility defines
#define eeprom_rb(addr) eeprom_read_byte ((uint8_t *)(uint32_t) (addr))
#define eeprom_rw(addr) eeprom_read_word ((uint16_t *)(uint32_t) (addr))
#define eeprom_wb(addr, val) eeprom_write_byte ((uint8_t *)(uint32_t) (addr), (val))
#define E2END 0x0FFF
#define eeprom_is_ready() TRUE
Define Documentation
#define CONST const
Definition at line 53 of file unix.h.
#define INLINE inline
Definition at line 54 of file unix.h.
#define PSTR (p) (p)
Definition at line 56 of file unix.h.
#define PRG_RDB (p) (*((const char *)(p)))
Definition at line 57 of file unix.h.
#define prog_char const char
Definition at line 59 of file unix.h.
#define PGM_P prog_char *
Definition at line 60 of file unix.h.
#define main (...) NutAppMain(__VA_ARGS__)
Definition at line 77 of file unix.h.
#define strlen_P (x) strlen(x)
Definition at line 84 of file unix.h.
#define strcpy_P (x, y) strcpy(x,y)
Definition at line 85 of file unix.h.
#define strcmp_P (x, y) strcmp(x, y)
Definition at line 86 of file unix.h.
#define memcpy_P (x, y, z) memcpy(x, y, z)
Definition at line 87 of file unix.h.
#define RAMSTART ((void *)0x00100)
Definition at line 105 of file unix.h.
#define malloc (...) NUT_malloc(__VA_ARGS__)
Definition at line 108 of file unix.h.
#define realloc (...) NUT_realloc(__VA_ARGS__)
Definition at line 109 of file unix.h.
#define free (...) NUT_free(__VA_ARGS__)
Definition at line 110 of file unix.h.
#define eeprom_rb (addr) eeprom_read_byte ((uint8_t *)(uint32_t) (addr))
Definition at line 150 of file unix.h.
#define eeprom_rw (addr) eeprom_read_word ((uint16_t *)(uint32_t) (addr))
Definition at line 151 of file unix.h.
#define eeprom_wb (addr, val) eeprom_write_byte ((uint8_t *)(uint32_t) (addr), (val))
Definition at line 152 of file unix.h.
#define E2END 0x0FFF
Definition at line 154 of file unix.h.
#define eeprom_is_ready () TRUE
always returns 1, as eeprom = unix_file is always ready
Definition at line 159 of file unix.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
IRQ_TIMER0
IRQ_UART0_RX
IRQ_UART1_RX
IRQ_UART2_RX
IRQ_MAX
Definition at line 92 of file unix.h.
Function Documentation
void emulation_options_parse (int argc, char * argv[])
Definition at line 79 of file options.c.
References atoi(), uart_options_t::bautrate, uart_options_t::device, uart_options_t::flowcontrol, printf, strcmp(), strdup(), strncmp(), emulation_options_t::uart_options, uart_options_t::usbnum, and emulation_options_t::verbose.
Referenced by main().
Variable Documentation
emulation_options_t emulation_options
Definition at line 60 of file options.c.
Referenced by main().
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/