Nut/OS API
unix_devs.c File Reference
Defines
#define NO_STDIO_NUT_WRAPPER
Functions
char * dtostre (double f, char *str, uint8_t prec, uint8_t flags)
char * dtostrf (double f, char width, char prec, char *str)
unsigned int resolve (char *)
int UnixDevIOCTL (NUTDEVICE *dev, int req, void *conf)
Perform USART control functions.
Variables
pthread_attr_t unix_devs_attr
pthread_mutex_t unix_devs_mutex
pthread_cond_t unix_devs_cv
NUTDEVICE devDebug0
Debug device 0 information structure.
NUTDEVICE devDebug1
Debug device 1 information structure.
NUTDEVICE devUart0
uart device 0 information structure.
NUTDEVICE devUart1
uart device 1 information structure.
NUTDEVICE devUart2
uart device 2 information structure.
NUTDEVICE devUsartAvr0
usartavr device 0 information structure.
NUTDEVICE devUsartAvr1
usartavr device 1 information structure.
NUTDEVICE devUsartAvr2
usartavr device 2 information structure.
Define Documentation
#define NO_STDIO_NUT_WRAPPER
Definition at line 45 of file unix_devs.c.
Function Documentation
char * dtostre (double f, char * str, uint8_t prec, uint8_t flags)
Definition at line 115 of file unix_devs.c.
References sprintf.
Referenced by _putf().
char * dtostrf (double f, char width, char prec, char * str)
Definition at line 121 of file unix_devs.c.
References sprintf.
Referenced by _putf().
unsigned int resolve (char * ip_addr)
Definition at line 268 of file unix_devs.c.
References inet_addr(), and memcpy().
int UnixDevIOCTL (NUTDEVICE * dev, int req, void * conf)
Perform USART control functions.
This function is called by the ioctl() function of the C runtime library.
Parameters:
dev Identifies the device that receives the device-control function.
req Requested control function. May be set to one of the following constants:
UART_SETSPEED
UART_GETSPEED
UART_SETDATABITS
UART_GETDATABITS
UART_SETSTOPBITS
UART_GETSTOPBITS
UART_SETPARITY
UART_GETPARITY
UART_SETFLOWCONTROL
UART_GETFLOWCONTROL
UART_SETBLOCKREAD
UART_GETBLOCKREAD
UART_SETSTATUS
UART_GETSTATUS
conf Points to a buffer that contains any data required for the given control function or receives data from that function.
Returns:
0 on success, -1 otherwise.
Warning:
Timeout values are given in milliseconds and are limited to the granularity of the system timer. To disable timeout, set the parameter to NUT_WAIT_INFINITE.
Definition at line 781 of file unix_devs.c.
References errno, printf, UART_GETBLOCKREAD, UART_GETDATABITS, UART_GETFLOWCONTROL, UART_GETPARITY, UART_GETSPEED, UART_GETSTATUS, UART_GETSTOPBITS, UART_HS_MODEM, UART_HS_RTSCTS, UART_HS_SOFT, UART_SETBLOCKREAD, UART_SETCOOKEDMODE, UART_SETDATABITS, UART_SETFLOWCONTROL, UART_SETPARITY, UART_SETRXBUFHWMARK, UART_SETRXBUFLWMARK, UART_SETRXBUFSIZ, UART_SETSPEED, UART_SETSTATUS, UART_SETSTOPBITS, UART_SETTXBUFHWMARK, UART_SETTXBUFLWMARK, UART_SETTXBUFSIZ, and USART_MF_BLOCKREAD.
Variable Documentation
pthread_attr_t unix_devs_attr
Definition at line 102 of file unix_devs.c.
pthread_mutex_t unix_devs_mutex
Definition at line 105 of file unix_devs.c.
pthread_cond_t unix_devs_cv
Definition at line 108 of file unix_devs.c.
© 2000-2007 by egnite Software GmbH - visit http://www.ethernut.de/